const DATA_URL='../data/live-tv.json';
const STATUS_URL='../data/live-tv-status.json';
const $=s=>document.querySelector(s);let channels=[],health={},hls=null,current=null;
const video=$('#video'),message=$('#playerMessage'),cards=$('#channels');
async function loadData(){try{const [a,b]=await Promise.all([fetch(`${DATA_URL}?v=${Date.now()}`,{cache:'no-store'}),fetch(`${STATUS_URL}?v=${Date.now()}`,{cache:'no-store'}).catch(()=>null)]);if(!a.ok)throw 0;const d=await a.json();channels=d.channels||[];if(b&&b.ok){const s=await b.json();(s.results||[]).forEach(x=>health[x.id]=x.status)}render();setCount('तयार')}catch(e){cards.innerHTML='<div class="source-note">च्यानल सूची लोड हुन सकेन। केही बेरपछि फेरि प्रयास गर्नुहोस्।</div>';setCount('डेटा उपलब्ध छैन')}}
function setCount(t){$('#liveCount').textContent=t}
function statusText(id){return health[id]==='online'?'LIVE उपलब्ध':health[id]==='offline'?'अहिले उपलब्ध छैन':'जाँच नभएको'}
function statusClass(id){return health[id]||'unknown'}
function render(){const q=($('#search').value||'').trim().toLowerCase(),g=$('#groupFilter').value;const list=channels.filter(c=>(g==='all'||c.group===g)&&(!q||`${c.name} ${c.group}`.toLowerCase().includes(q)));cards.innerHTML=list.map(c=>`<button class="channel ${current?.id===c.id?'selected':''}" data-id="${escapeHtml(c.id)}"><img class="logo" src="${escapeAttr(c.logo)}" alt="" loading="lazy" onerror="this.style.visibility='hidden'"><span class="channel-main"><span class="channel-name">${escapeHtml(c.name)}</span><span class="channel-meta"><i class="dot ${statusClass(c.id)}"></i><span>${statusText(c.id)}</span></span></span></button>`).join('')||'<div class="source-note">च्यानल भेटिएन।</div>';cards.querySelectorAll('.channel').forEach(b=>b.addEventListener('click',()=>selectChannel(channels.find(c=>c.id===b.dataset.id))))}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function escapeAttr(s){return escapeHtml(s).replace(/`/g,'&#96;')}
function stop(){if(hls){hls.destroy();hls=null}video.pause();video.removeAttribute('src');video.load()}
function selectChannel(c){if(!c)return;current=c;render();stop();message.hidden=false;message.textContent='Stream लोड हुँदैछ…';$('#nowName').textContent=c.name;$('#nowStatus').textContent='HLS stream जाँच हुँदैछ';const a=$('#openStream');a.href=c.stream;a.hidden=false;if(window.Hls&&Hls.isSupported()){hls=new Hls({enableWorker:true,lowLatencyMode:true,backBufferLength:30});hls.loadSource(c.stream);hls.attachMedia(video);hls.on(Hls.Events.MANIFEST_PARSED,()=>{message.hidden=true;$('#nowStatus').textContent='LIVE stream तयार छ';markCard(c.id,'online')});hls.on(Hls.Events.ERROR,(_,d)=>{if(d.fatal){message.hidden=false;message.textContent='यो stream अहिले चल्न सकेन। Alternate stream वा official page प्रयोग गर्नुहोस्।';$('#nowStatus').textContent='Stream unavailable';markCard(c.id,'offline')}})}else if(video.canPlayType('application/vnd.apple.mpegurl')){video.src=c.stream;video.addEventListener('loadedmetadata',()=>{message.hidden=true;$('#nowStatus').textContent='LIVE stream तयार छ';markCard(c.id,'online')},{once:true});video.addEventListener('error',()=>{message.hidden=false;message.textContent='यो stream browser मा उपलब्ध छैन।';$('#nowStatus').textContent='Stream unavailable';markCard(c.id,'offline')},{once:true})}else message.textContent='तपाईंको browser ले HLS support गर्दैन। Chrome/Edge/Safari प्रयोग गर्नुहोस्।'}
function markCard(id,status){health[id]=status;const b=cards.querySelector(`[data-id="${CSS.escape(id)}"]`);if(!b)return;const dot=b.querySelector('.dot'),txt=b.querySelector('.channel-meta span');dot.className=`dot ${status}`;txt.textContent=status==='online'?'LIVE उपलब्ध':status==='offline'?'अहिले उपलब्ध छैन':'जाँच नभएको'}
function checkStream(c){return new Promise(resolve=>{if(!window.Hls||!Hls.isSupported()){markCard(c.id,'unknown');resolve(false);return}const test=new Hls({enableWorker:true,lowLatencyMode:true});let done=false;const finish=ok=>{if(done)return;done=true;clearTimeout(timer);test.destroy();markCard(c.id,ok?'online':'offline');resolve(ok)};const timer=setTimeout(()=>finish(false),6000);test.on(Hls.Events.MANIFEST_PARSED,()=>finish(true));test.on(Hls.Events.ERROR,(_,d)=>{if(d.fatal)finish(false)});test.loadSource(c.stream)})}
async function healthCheck(){setCount('Stream जाँच हुँदैछ…');render();let ok=0;for(const c of channels){if(await checkStream(c))ok++;}setCount(`${ok}/${channels.length} streams उपलब्ध`)}
$('#search').addEventListener('input',render);$('#groupFilter').addEventListener('change',render);$('#refreshBtn').addEventListener('click',healthCheck);loadData();