const DATA_URL='https://raw.githubusercontent.com/LaxmanNepal/LaxmanNepalApps/refs/heads/main/TV/list.json';
const STATUS_URL='../data/live-tv-status.json';
const $=s=>document.querySelector(s);let channels=[],health={},hls=null,current=null,wakeLock=null;
const video=$('#video'),message=$('#playerMessage'),cards=$('#channels');
async function requestWakeLock(){try{if('wakeLock' in navigator&&!wakeLock){wakeLock=await navigator.wakeLock.request('screen');wakeLock.addEventListener('release',()=>{wakeLock=null})}}catch(e){wakeLock=null}}
async function releaseWakeLock(){try{if(wakeLock){await wakeLock.release();wakeLock=null}}catch(e){wakeLock=null}}
async function enterTVFullscreen(){try{if(!document.fullscreenElement)await video.requestFullscreen?.();if(screen.orientation?.lock)await screen.orientation.lock('landscape').catch(()=>{})}catch(e){}await requestWakeLock()}
async function exitTVFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen()}catch(e){}try{screen.orientation?.unlock?.()}catch(e){}await releaseWakeLock()}
video.addEventListener('dblclick',()=>{if(document.fullscreenElement)exitTVFullscreen();else enterTVFullscreen()});document.addEventListener('fullscreenchange',async()=>{if(document.fullscreenElement){await requestWakeLock();try{await screen.orientation?.lock?.('landscape')}catch(e){}}else{try{screen.orientation?.unlock?.()}catch(e){}await releaseWakeLock()}});document.addEventListener('visibilitychange',async()=>{if(document.visibilityState==='visible'&&document.fullscreenElement)await requestWakeLock()});
async function loadData(){try{const [a,b]=await Promise.all([fetch(`${DATA_URL}?v=${Date.now()}`,{cache:'no-store'}),fetch(`${STATUS_URL}?v=${Date.now()}`,{cache:'no-store'}).catch(()=>null)]);if(!a.ok)throw 0;const raw=await a.json();const list=Array.isArray(raw)?raw:(Array.isArray(raw.channels)?raw.channels:[]);channels=list.map((c,i)=>({id:String(c.id||c.title||`channel-${i}`).toLowerCase().replace(/[^a-z0-9]+/g,'-'),name:String(c.title||'Unnamed Channel'),logo:c.image||'',stream:c.m3u8||'',official:c.link||'',group:guessGroup(c.title||'')})).filter(c=>c.stream);if(b&&b.ok){const s=await b.json();(s.results||[]).forEach(x=>health[x.id]=x.status)}render();setCount(`${channels.length} च्यानल`)}catch(e){cards.innerHTML='<div class="source-note">Live TV data लोड हुन सकेन। फेरि प्रयास गर्नुहोस्।</div>';setCount('डेटा उपलब्ध छैन')}}
function guessGroup(name){const n=name.toLowerCase();if(/nepal|kantipur|ntv|himalaya|image|ap1|news24|sagarmatha|avenues|tv today|capital|mithila/.test(n))return 'nepal';if(/sony|star|zee|colors|dd |doordarshan|bharat|aaj tak|times now|news18|india|republic|abp|tv9/.test(n))return 'hindi';if(/b4u|zoom|9xm|music|mtv/.test(n))return 'music';if(/aastha|pashupatinath|spiritual|devotional/.test(n))return 'religious';return 'all'}
function setCount(t){$('#liveCount').textContent=t}function statusText(id){return health[id]==='online'?'LIVE उपलब्ध':health[id]==='offline'?'अहिले उपलब्ध छैन':'जाँच नभएको'}function statusClass(id){return health[id]||'unknown'}
function render(){const q=($('#search').value||'').trim().toLowerCase(),g=$('#groupFilter').value;const list=channels.filter(c=>(g==='all'||c.group===g)&&(!q||`${c.name} ${c.group}`.toLowerCase().includes(q)));cards.innerHTML=list.map(c=>`<button class="channel ${current?.id===c.id?'selected':''}" data-id="${escapeHtml(c.id)}"><img class="logo" src="${escapeAttr(c.logo||'')}" alt="" loading="lazy" onerror="this.style.visibility='hidden'"><span class="channel-main"><span class="channel-name">${escapeHtml(c.name)}</span><span class="channel-meta"><i class="dot ${statusClass(c.id)}"></i><span>${statusText(c.id)}</span></span></span></button>`).join('')||'<div class="source-note">च्यानल भेटिएन।</div>';cards.querySelectorAll('.channel').forEach(b=>b.addEventListener('click',()=>selectChannel(channels.find(c=>c.id===b.dataset.id))))}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function escapeAttr(s){return escapeHtml(s).replace(/`/g,'&#96;')}
function stop(){if(hls){hls.destroy();hls=null}video.pause();video.removeAttribute('src');video.load()}
function fail(c,text='यो stream अहिले चल्न सकेन। Official page खोल्नुहोस्।'){message.hidden=false;message.textContent=text;$('#nowStatus').textContent='Stream unavailable';markCard(c.id,'offline')}
function selectChannel(c){if(!c)return;current=c;render();stop();message.hidden=false;message.textContent='Stream लोड हुँदैछ…';$('#nowName').textContent=c.name;$('#nowStatus').textContent='HLS stream जाँच हुँदैछ';const a=$('#openStream');a.href=c.official||c.stream;a.textContent=c.official?'Source ↗':'Stream URL ↗';a.hidden=false;if(!c.stream)return fail(c,'यो च्यानलको HLS URL छैन।');if(window.Hls&&Hls.isSupported()){hls=new Hls({enableWorker:true,lowLatencyMode:true,maxBufferLength:20,backBufferLength:30});hls.loadSource(c.stream);hls.attachMedia(video);hls.on(Hls.Events.MANIFEST_PARSED,()=>{message.hidden=true;$('#nowStatus').textContent='LIVE stream तयार छ';markCard(c.id,'online');video.play().catch(()=>{});requestWakeLock()});hls.on(Hls.Events.ERROR,(_,d)=>{if(d.fatal)fail(c)})}else if(video.canPlayType('application/vnd.apple.mpegurl')){video.src=c.stream;video.addEventListener('loadedmetadata',()=>{message.hidden=true;$('#nowStatus').textContent='LIVE stream तयार छ';markCard(c.id,'online');video.play().catch(()=>{});requestWakeLock()},{once:true});video.addEventListener('error',()=>fail(c,'यो HLS stream browser मा उपलब्ध छैन।'),{once:true})}else fail(c,'तपाईंको browser ले HLS support गर्दैन।')}
function markCard(id,status){health[id]=status;const b=cards.querySelector(`[data-id="${CSS.escape(id)}"]`);if(!b)return;const dot=b.querySelector('.dot'),txt=b.querySelector('.channel-meta span');dot.className=`dot ${status}`;txt.textContent=status==='online'?'LIVE उपलब्ध':status==='offline'?'अहिले उपलब्ध छैन':'जाँच नभएको'}
function checkStream(c){return new Promise(resolve=>{if(!c.stream||!window.Hls||!Hls.isSupported()){markCard(c.id,'unknown');resolve(false);return}const test=new Hls({enableWorker:true,lowLatencyMode:true,maxBufferLength:10});let done=false;const finish=ok=>{if(done)return;done=true;clearTimeout(timer);test.destroy();markCard(c.id,ok?'online':'offline');resolve(ok)};const timer=setTimeout(()=>finish(false),7000);test.on(Hls.Events.MANIFEST_PARSED,()=>finish(true));test.on(Hls.Events.ERROR,(_,d)=>{if(d.fatal)finish(false)});test.loadSource(c.stream)})}
async function healthCheck(){setCount('Stream जाँच हुँदैछ…');let ok=0;for(const c of channels){if(await checkStream(c))ok++;}setCount(`${ok}/${channels.length} streams उपलब्ध`)}
$('#search').addEventListener('input',render);$('#groupFilter').addEventListener('change',render);$('#refreshBtn').addEventListener('click',healthCheck);loadData();