const N={months:['बैशाख','जेठ','असार','साउन','भदौ','असोज','कात्तिक','मंसिर','पुष','माघ','फागुन','चैत'],enMonths:['Baisakh','Jestha','Ashadh','Shrawan','Bhadra','Ashwin','Kartik','Mangsir','Poush','Magh','Falgun','Chaitra'],week:['आइतबार','सोमबार','मंगलबार','बुधबार','बिहीबार','शुक्रबार','शनिबार'],nums:['०','१','२','३','४','५','६','७','८','९']};
const ROUTE={patro:'calendar',panchanga:'panchang',parba:'festivals',saith:'saait',rashifal:'rashifal',news:'news',converter:'converter'};
const np=n=>String(n).replace(/\d/g,d=>N.nums[d]),pad=n=>String(n).padStart(2,'0');
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const adText=d=>d?new Intl.DateTimeFormat('en-US',{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'}).format(new Date(`${d}T00:00:00Z`)):'—';
let DATA={year:2083,days:[],lengths:[]},YEARS=[],INDEX=null,currentYear=2083,viewMonth=4,selectedIndex=0;
function route(){const p=location.pathname.split('/').filter(Boolean),i=p.indexOf('nepali-patro');return i>=0&&p[i+1]?p[i+1].toLowerCase():''}
function root(){return document.querySelector('base')?.href||new URL('./',location.href).href}
function go(r){location.href=r?new URL(`${r}/`,root()).href:new URL('./',root()).href}
function day(m,d){return DATA.days.find(x=>x.bs.month===m&&x.bs.day===d)}
function eventNames(x){const values=[];if(Array.isArray(x?.events))values.push(...x.events);if(x?.festival)values.push(x.festival);return [...new Set(values.map(v=>String(v||'').trim()).filter(Boolean))]}
function eventText(x){return eventNames(x).join(' · ')}
function hasEvent(x){return eventNames(x).length>0}
function selected(){return DATA.days[selectedIndex]||DATA.days[0]}
const PANCHANG_FIELDS=[['वार',x=>x.weekday?.nepali,true],['तिथि',x=>x.tithi?.name,true],['नक्षत्र',x=>x.nakshatra?.name,true],['सूर्योदय',x=>x.sun?.sunrise,true],['सूर्यास्त',x=>x.sun?.sunset,false],['चन्द्रोदय',x=>x.moon?.rise,false],['चन्द्रास्त',x=>x.moon?.set,false],['राहुकाल',x=>x.rahuKaal?.start&&x.rahuKaal?.end?x.rahuKaal.start+' – '+x.rahuKaal.end:null,false]];
function valuePresent(v){return v!==null&&v!==undefined&&String(v).trim()!==''}
function panchangQuality(x){const required=PANCHANG_FIELDS.filter(f=>f[2]),optional=PANCHANG_FIELDS.filter(f=>!f[2]);const missingRequired=required.filter(f=>!valuePresent(f[1](x))).map(f=>f[0]),missingOptional=optional.filter(f=>!valuePresent(f[1](x))).map(f=>f[0]);const score=Math.round(((required.length-missingRequired.length)*2+(optional.length-missingOptional.length))/(required.length*2+optional.length)*100);return {score,missingRequired,missingOptional,complete:missingRequired.length===0}}
function qualityLabel(q){return q.complete?(q.score>=85?'पूर्ण':'आंशिक'):'अपूर्ण'}
function renderDataQuality(){const e=document.querySelector('#dataQuality'),x=selected();if(!e||!x)return;const q=panchangQuality(x);const text=q.complete?(q.score>=85?'पञ्चाङ्ग डेटा पूर्ण छ।':'केही वैकल्पिक विवरण उपलब्ध छैनन्।'):'महत्वपूर्ण पञ्चाङ्ग डेटा अपूर्ण छ: '+q.missingRequired.join(', ')+'।';e.className='data-quality '+(q.complete?(q.score>=85?'good':'partial'):'warning');e.textContent='डेटा गुणस्तर: '+qualityLabel(q)+' ('+q.score+'%) — '+text}
function todayIndex(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kathmandu',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),y=+p.find(x=>x.type==='year').value,m=+p.find(x=>x.type==='month').value,d=+p.find(x=>x.type==='day').value;return DATA.days.findIndex(x=>x.ad.year===y&&x.ad.month===m&&x.ad.day===d)}
function renderClock(){const e=document.querySelector('#clock');if(e)e.textContent=new Intl.DateTimeFormat('ne-NP',{timeZone:'Asia/Kathmandu',weekday:'long',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:true}).format(new Date())}
function renderToday(){const x=selected();if(!x)return;const set=(q,v)=>{const e=document.querySelector(q);if(e)e.textContent=v??'—'};set('#todayBs',x.bs.display);set('#todayAd',adText(x.ad.date));set('#todayWeekday',x.weekday?.nepali);set('#todayTithi',x.tithi?.name||'तिथि डेटा उपलब्ध छैन');set('#todayPaksha',x.tithi?.paksha?`पक्ष: ${x.tithi.paksha}`:'');set('#sunrise',x.sun?.sunrise||'—');set('#sunset',x.sun?.sunset||'—');set('#nakshatra',x.nakshatra?.name||'—');set('#moon',x.moon?.phase||'—');set('#todayFestivalBadge',eventText(x))}
function renderCalendar(){const y=document.querySelector('#yearSelect'),m=document.querySelector('#monthSelect'),g=document.querySelector('#calendarGrid');if(!y||!m||!g)return;y.innerHTML=YEARS.map(v=>`<option value="${v}">${np(v)}</option>`).join('');y.value=currentYear;m.innerHTML=N.months.map((v,i)=>`<option value="${i+1}">${v}</option>`).join('');m.value=viewMonth;g.innerHTML='';const f=day(viewMonth,1);for(let i=0;i<(f?.weekday?.index||0);i++)g.insertAdjacentHTML('beforeend','<div class="day empty"></div>');const count=DATA.lengths?.[viewMonth-1]||DATA.days.filter(x=>x.bs.month===viewMonth).length;for(let d=1;d<=count;d++){const x=day(viewMonth,d);if(!x)continue;const ti=todayIndex(),today=ti>=0&&DATA.days[ti]===x,sel=DATA.days[selectedIndex]===x;g.insertAdjacentHTML('beforeend',`<button class="day ${today?'today ':''}${hasEvent(x)?'holiday ':''}${sel?'selected ':''}" data-day="${d}" aria-label="${esc(x.bs.display)}"><span class="bs">${np(d)}</span><span class="ad">${x.ad.day} ${new Intl.DateTimeFormat('en-US',{month:'short',timeZone:'UTC'}).format(new Date(`${x.ad.date}T00:00:00Z`))}</span>${x.festival?`<span class="event">${esc(x.festival)}</span>`:''}${x.holiday?'<i class="holiday-mark">●</i>':''}</button>`)}g.querySelectorAll('button.day').forEach(b=>b.onclick=()=>selectDay(viewMonth,+b.dataset.day))}
function selectDay(m,d){const i=DATA.days.findIndex(x=>x.bs.month===m&&x.bs.day===d);if(i<0)return;selectedIndex=i;viewMonth=m;renderAll();if(route()!=='patro')go('patro');else document.querySelector('#dayDetail')?.scrollIntoView({behavior:'smooth',block:'start'})}
function renderPanchang(){const x=selected(),g=document.querySelector('#panchangGrid');if(!x||!g)return;const rows=[['वार',x.weekday?.nepali],['तिथि',x.tithi?.name],['तिथि समाप्ति',x.tithi?.end],['पक्ष',x.tithi?.paksha],['नक्षत्र',x.nakshatra?.name],['नक्षत्र समाप्ति',x.nakshatra?.end],['योग',x.yoga?.name],['योग समाप्ति',x.yoga?.end],['करण',x.karana?.name],['करण समाप्ति',x.karana?.end],['राशि',x.rashi],['सूर्योदय',x.sun?.sunrise],['सूर्यास्त',x.sun?.sunset],['राहुकाल',x.rahuKaal?`${x.rahuKaal.start} – ${x.rahuKaal.end}`:'—'],['चन्द्रोदय',x.moon?.rise],['चन्द्रास्त',x.moon?.set],['चन्द्र अवस्था',x.moon?.phase],['नेपाल संवत्',x.nepalSambat],['पर्व',eventText(x)||'—'],['डेटा गुणस्तर',qualityLabel(panchangQuality(x))+' ('+panchangQuality(x).score+'%)']];g.innerHTML=rows.map(([a,b])=>`<div class="info-card"><span>${esc(a)}</span><b>${esc(b||'डेटा उपलब्ध छैन')}</b></div>`).join('')}
function until(s){return Math.max(0,Math.round((new Date(`${s}T00:00:00Z`)-new Date(`${selected().ad.date}T00:00:00Z`))/86400000))}
function renderEvents(){const e=document.querySelector('#eventList');if(!e)return;const rows=DATA.days.filter(x=>hasEvent(x)||x.holiday).filter(x=>x.ad.date>=selected().ad.date).slice(0,18);e.innerHTML=rows.length?rows.map(x=>`<article class="event"><div class="date">${esc(x.bs.display)} · ${x.ad.date}</div><h3>${esc(eventText(x)||'बिदा')}</h3><p>${x.holiday?'🇳🇵 बिदा':'🎉 पर्व'} · ${until(x.ad.date)} दिन बाँकी</p></article>`).join(''):'<div class="news-empty">पर्व तथा बिदा डेटा उपलब्ध छैन।</div>'}
function renderSaait(){const e=document.querySelector('#saaitGrid');if(!e)return;e.innerHTML=`<div class="info-card"><span>पञ्चाङ्ग स्रोत</span><b>तिथि, नक्षत्र, योग, करण र पर्वका प्रमाणित स्थिर डेटा उपलब्ध छन्।</b></div><div class="info-card"><span>साइतबारे</span><b>विवाह, गृहप्रवेश आदि मुहूर्त स्थान, लग्न र परम्परा अनुसार फरक हुन्छन्। प्रमाणित स्थानीय साइत नआएसम्म अनुमानित समयलाई साइत भनेर देखाइएको छैन।</b></div><div class="info-card"><span>आज</span><b>${esc(selected().bs.display)} · ${esc(eventText(selected())||'विशेष पर्व छैन')}</b></div>`}
const Z=[['♈','मेष'],['♉','वृष'],['♊','मिथुन'],['♋','कर्कट'],['♌','सिंह'],['♍','कन्या'],['♎','तुला'],['♏','वृश्चिक'],['♐','धनु'],['♑','मकर'],['♒','कुम्भ'],['♓','मीन']];const ZT=['नयाँ योजना अघि प्राथमिकता स्पष्ट गर्नुहोस्।','आर्थिक निर्णयमा धैर्य र तथ्यलाई प्राथमिकता दिनुहोस्।','सम्पर्क र संवादबाट अवसर आउन सक्छ।','परिवार र जिम्मेवारीबीच सन्तुलन राख्नुहोस्।','आत्मविश्वास राम्रो छ, तर हतार नगर्नुहोस्।','सानो विवरणमा ध्यान दिँदा परिणाम राम्रो हुनेछ।','सम्बन्धमा स्पष्ट र शान्त संवाद उपयोगी हुनेछ।','प्रमाण नजाँची निर्णय नगर्नुहोस्।','नयाँ कुरा सिक्ने ऊर्जा बढ्न सक्छ।','नियमित मेहनतको परिणाम देखिन थाल्नेछ।','नयाँ विचारलाई व्यवहारिक योजनामा बदल्नुहोस्।','आराम, सिर्जनशीलता र कामबीच सन्तुलन राख्नुहोस्।'];
function renderZodiac(){const e=document.querySelector('#zodiacGrid');if(!e)return;e.innerHTML=Z.map(([s,n],i)=>`<article class="zodiac"><span class="symbol">${s}</span><b>${n}</b><p>${ZT[i]}</p><small>मनोरञ्जनात्मक राशिफल</small></article>`).join('')}
function renderDetail(){const x=selected(),t=document.querySelector('#detailTitle'),g=document.querySelector('#detailGrid');if(!x||!t||!g)return;t.textContent=x.bs.display;const rows=[['ईस्वी मिति',adText(x.ad.date)],['वार',x.weekday?.nepali],['तिथि',x.tithi?.name],['पक्ष',x.tithi?.paksha],['तिथि समाप्ति',x.tithi?.end],['नक्षत्र',x.nakshatra?.name],['नक्षत्र समाप्ति',x.nakshatra?.end],['योग',x.yoga?.name],['करण',x.karana?.name],['राशि',x.rashi],['सूर्योदय',x.sun?.sunrise],['सूर्यास्त',x.sun?.sunset],['चन्द्रोदय',x.moon?.rise],['चन्द्रास्त',x.moon?.set],['नेपाल संवत्',x.nepalSambat],['पर्व/बिदा',eventText(x)||'कुनै विशेष पर्व छैन'],['पञ्चाङ्ग डेटा',qualityLabel(panchangQuality(x))+' ('+panchangQuality(x).score+'%)']];g.innerHTML=rows.map(([a,b])=>`<div class="info-card"><span>${esc(a)}</span><b>${esc(b||'डेटा उपलब्ध छैन')}</b></div>`).join('')}
function renderConverter(){const r=document.querySelector('#convertResult'),bs=document.querySelector('#bsInput'),ad=document.querySelector('#adInput');if(!r||!bs||!ad||!INDEX)return;const show=v=>r.innerHTML=v;document.querySelector('#bsConvert').onclick=()=>{const raw=bs.value.trim().replace(/[०-९]/g,d=>N.nums.indexOf(d)).replace(/[\/\.]/g,'-');const [y,m,d]=raw.split('-').map(Number),k=`${y}-${pad(m)}-${pad(d)}`,x=INDEX.bs.get(k);if(!x)return show('<span class="error">मान्य BS मिति लेख्नुहोस्। समर्थित दायरा २०४०–२१०० BS हो।</span>');ad.value=x.ad;show(`<strong>${np(y)}-${np(pad(m))}-${np(pad(d))}</strong> → <strong>${adText(x.ad)}</strong>`)};document.querySelector('#adConvert').onclick=()=>{const k=ad.value,x=INDEX.ad.get(k);if(!x)return show('<span class="error">यो AD मिति २०४०–२१०० BS दायराभन्दा बाहिर छ।</span>');bs.value=`${x.year}-${pad(x.month)}-${pad(x.day)}`;show(`<strong>${adText(k)}</strong> → <strong>${N.months[x.month-1]} ${np(x.day)}, ${np(x.year)}</strong>`)}}
function renderAll(){renderToday();renderCalendar();renderPanchang();renderEvents();renderSaait();renderZodiac();renderDetail();renderDataQuality()}
async function loadYear(year,keep=true){const old=viewMonth;const r=await fetch(`data/calendar/${year}.json`,{cache:'force-cache'});if(!r.ok)throw Error(`calendar ${year} unavailable`);DATA=await r.json();currentYear=year;viewMonth=keep?old:1;selectedIndex=Math.max(0,DATA.days.findIndex(x=>x.bs.month===viewMonth&&x.bs.day===1));renderAll()}
async function loadIndexes(){const [y,c]=await Promise.all([fetch('data/years.json').then(r=>r.json()),fetch('data/conversion-index.json').then(r=>r.json())]);YEARS=Array.from({length:y.maxYear-y.minYear+1},(_,i)=>y.minYear+i);INDEX={bs:new Map(),ad:new Map()};for(const x of c.items){const [year,month,day]=x.bs.split('-').map(Number);INDEX.bs.set(x.bs,{ad:x.ad,year,month,day});INDEX.ad.set(x.ad,{year,month,day})}}
function applyRoute(){const r=route(),section=ROUTE[r];if(!r)return;document.querySelectorAll('main > section').forEach(s=>s.classList.add('route-hidden'));if(section)document.getElementById(section)?.classList.remove('route-hidden');if(r==='patro')document.getElementById('dayDetail')?.classList.remove('route-hidden');document.body.classList.add('feature-route')}
function init(){document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>go(b.dataset.section==='today'?'':b.dataset.section));document.querySelector('#prevMonth').onclick=async()=>{if(viewMonth>1){viewMonth--;selectedIndex=DATA.days.findIndex(x=>x.bs.month===viewMonth&&x.bs.day===1);renderAll()}};document.querySelector('#nextMonth').onclick=async()=>{if(viewMonth<12){viewMonth++;selectedIndex=DATA.days.findIndex(x=>x.bs.month===viewMonth&&x.bs.day===1);renderAll()}};document.querySelector('#yearSelect').onchange=e=>loadYear(+e.target.value);document.querySelector('#monthSelect').onchange=e=>{viewMonth=+e.target.value;selectedIndex=DATA.days.findIndex(x=>x.bs.month===viewMonth&&x.bs.day===1);renderAll()};document.querySelector('#todayBtn').onclick=()=>{const i=todayIndex();if(i>=0){selectedIndex=i;viewMonth=DATA.days[i].bs.month;renderAll()}};document.querySelector('#closeDetail').onclick=()=>go('patro');document.querySelector('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('patro-theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('patro-theme')==='dark')document.body.classList.add('dark');document.querySelector('#searchBtn').onclick=()=>document.querySelector('#searchOverlay').classList.remove('hidden');document.querySelector('#closeSearch').onclick=()=>document.querySelector('#searchOverlay').classList.add('hidden');document.querySelector('#searchInput').oninput=e=>searchPatro(e.target.value);document.querySelector('#yearNow').textContent=new Date().getFullYear();renderClock();setInterval(renderClock,1000);renderConverter();applyRoute()}
function searchPatro(q){const root=document.querySelector('#searchResults');if(!root)return;q=q.trim().toLocaleLowerCase('ne');if(!q){root.innerHTML='';return}const hits=DATA.days.filter(x=>`${x.bs.display} ${x.ad.date} ${x.weekday?.nepali} ${eventText(x)} ${x.tithi?.name||''} ${x.nakshatra?.name||''}`.toLocaleLowerCase('ne').includes(q)).slice(0,20);root.innerHTML=hits.length?hits.map(x=>`<div class="search-result" data-m="${x.bs.month}" data-d="${x.bs.day}"><b>${esc(x.bs.display)}</b><br><small>${esc(x.ad.date)} · ${esc(eventText(x)||x.tithi?.name||x.weekday?.nepali)}</small></div>`).join(''):'<p class="muted">कुनै नतिजा भेटिएन।</p>';root.querySelectorAll('.search-result').forEach(e=>e.onclick=()=>selectDay(+e.dataset.m,+e.dataset.d))}
async function boot(){try{await loadIndexes();const ti=await fetch('data/calendar/2083.json').then(r=>r.ok?r.json():null);if(ti){DATA=ti;currentYear=2083;viewMonth=ti.days[Math.max(0,todayIndex())]?.bs.month||4;selectedIndex=Math.max(0,todayIndex())}else await loadYear(2083,false);init();renderAll()}catch(e){console.error(e);const t=document.querySelector('#toast');if(t)t.textContent='पात्रो डेटा build हुँदैछ। GitHub Actions सफल भएपछि पुनः खोल्नुहोस्।';init()}}
document.addEventListener('DOMContentLoaded',boot);
