const N={months:['बैशाख','जेठ','असार','साउन','भदौ','असोज','कात्तिक','मंसिर','पुष','माघ','फागुन','चैत'],enMonths:['Baisakh','Jestha','Ashadh','Shrawan','Bhadra','Ashwin','Kartik','Mangsir','Poush','Magh','Falgun','Chaitra'],week:['आइतबार','सोमबार','मंगलबार','बुधबार','बिहीबार','शुक्रबार','शनिबार'],weekShort:['आइत','सोम','मंगल','बुध','बिही','शुक्र','शनि'],nums:['०','१','२','३','४','५','६','७','८','९']};
const DATA={year:2083,start:'2026-04-14',lengths:[31,31,32,31,31,31,30,29,30,29,30,30],panchang:{'2083-5-5':{tithi:'नवमी, २३:४७ बजेपछि दशमी',paksha:'श्रावण शुक्लपक्ष',nakshatra:'अनुराधा, १३:२९ बजेपछि ज्येष्ठा',yoga:'ऐन्द्र, ०७:११ बजेपछि वैधृति',karana:'वालव, १०:५१ बजेपछि कौलव, २३:४७ बजेउप्रान्त गर',moon:'वृश्चिक',sunrise:'०५:३७',sunset:'१८:३५',dayLength:'१२:५८',special:'थकाली थालो पर्व'}},events:[
{bs:'भदौ ७, २०८३',ad:'Aug 23, 2026',title:'पुत्रदा एकादशी व्रत',type:'पर्व',key:'2083-5-7'},
{bs:'भदौ ९, २०८३',ad:'Aug 25, 2026',title:'राष्ट्रिय धर्मसभा दिवस',type:'दिवस',key:'2083-5-9'},
{bs:'भदौ १२, २०८३',ad:'Aug 28, 2026',title:'जनै पूर्णिमा / रक्षा बन्धन / ऋषितर्पणी / क्वाति खाने दिन',type:'पर्व',key:'2083-5-12'},
{bs:'भदौ १३, २०८३',ad:'Aug 29, 2026',title:'गाईजात्रा (काठमाडौं उपत्यका)',type:'पर्व',key:'2083-5-13'},
{bs:'भदौ १४, २०८३',ad:'Aug 30, 2026',title:'रोपाईं जात्रा',type:'पर्व',key:'2083-5-14'},
{bs:'भदौ १८, २०८३',ad:'Sep 3, 2026',title:'गौरा सप्तमी',type:'पर्व',key:'2083-5-18'},
{bs:'भदौ १९, २०८३',ad:'Sep 4, 2026',title:'श्रीकृष्ण जन्माष्टमी / गौरा पर्व',type:'पर्व',key:'2083-5-19'},
{bs:'भदौ २०, २०८३',ad:'Sep 5, 2026',title:'गूङा नवमी / राधाकृष्ण रथयात्रा',type:'पर्व',key:'2083-5-20'},
{bs:'भदौ २८, २०८३',ad:'Sep 13, 2026',title:'हरितालिका तीज / गणेश चतुर्थी व्रत / राष्ट्रिय बाल दिवस',type:'पर्व',key:'2083-5-28'},
{bs:'भदौ ३१, २०८३',ad:'Sep 16, 2026',title:'विश्वकर्मा पूजा / कन्या संक्रान्ति / राष्ट्रिय विज्ञान दिवस',type:'पर्व',key:'2083-5-31'}],zodiac:[['♈','मेष','नयाँ काममा ध्यान केन्द्रित गर्नुहोस्।'],['♉','वृष','आर्थिक निर्णयमा धैर्य उपयोगी हुनेछ।'],['♊','मिथुन','सम्पर्क र संवादबाट अवसर आउन सक्छ।'],['♋','कर्कट','परिवारसँग समय बिताउनु राम्रो हुनेछ।'],['♌','सिंह','आत्मविश्वास बढ्ने दिन हो।'],['♍','कन्या','कामलाई प्राथमिकताअनुसार अघि बढाउनुहोस्।'],['♎','तुला','सम्बन्धमा स्पष्ट संवाद आवश्यक छ।'],['♏','वृश्चिक','हतारमा निर्णय नगर्नुहोस्।'],['♐','धनु','नयाँ योजना सुरु गर्न प्रेरणा मिल्नेछ।'],['♑','मकर','मेहनतको परिणाम क्रमशः देखिनेछ।'],['♒','कुम्भ','नयाँ विचारलाई व्यवहारमा उतार्नुहोस्।'],['♓','मीन','आराम र कामबीच सन्तुलन राख्नुहोस्।']]};
let viewYear=2083,viewMonth=4;const todayAD=new Date('2026-08-21T12:00:00');let selected={y:2083,m:4,d:5};
const pad=n=>String(n).padStart(2,'0');const np=n=>String(n).replace(/\d/g,d=>N.nums[d]);
function dateFor(y,m,d){if(y===2083){let base=new Date('2026-04-14T00:00:00');for(let i=0;i<m;i++)base.setDate(base.getDate()+DATA.lengths[i]);base.setDate(base.getDate()+d-1);return base}return null}
function key(y,m,d){return `${y}-${m+1}-${d}`}
function adText(date){return date?date.toLocaleDateString('en-US',{year:'numeric',month:'short',day:'numeric'}):'—'}
function renderToday(){const k=key(selected.y,selected.m,selected.d),p=DATA.panchang[k]||{};const date=dateFor(selected.y,selected.m,selected.d);document.querySelector('#todayBs').textContent=`${N.months[selected.m]} ${np(selected.d)}, ${np(selected.y)}`;document.querySelector('#todayAd').textContent=adText(date);document.querySelector('#todayWeekday').textContent=date?N.week[date.getDay()]:'—';document.querySelector('#todayTithi').textContent=p.tithi||'पञ्चाङ्ग डेटा उपलब्ध छैन';document.querySelector('#todayPaksha').textContent=p.paksha||'';document.querySelector('#sunrise').textContent=p.sunrise||'—';document.querySelector('#sunset').textContent=p.sunset||'—';document.querySelector('#nakshatra').textContent=p.nakshatra||'—';document.querySelector('#moon').textContent=p.moon||'—';document.querySelector('#todayFestivalBadge').textContent=p.special||''}
function renderCalendar(){document.querySelector('#yearSelect').innerHTML='<option value="2083">२०८३</option>';document.querySelector('#monthSelect').innerHTML=N.months.map((x,i)=>`<option value="${i}">${x}</option>`).join('');document.querySelector('#monthSelect').value=viewMonth;document.querySelector('#yearSelect').value=viewYear;document.querySelector('#weekdays').innerHTML=N.weekShort.map(x=>`<div>${x}</div>`).join('');const grid=document.querySelector('#calendarGrid');grid.innerHTML='';const first=dateFor(viewYear,viewMonth,1);const offset=first.getDay();for(let i=0;i<offset;i++)grid.insertAdjacentHTML('beforeend','<div class="day empty"></div>');for(let d=1;d<=DATA.lengths[viewMonth];d++){const dt=dateFor(viewYear,viewMonth,d),k=key(viewYear,viewMonth,d),ev=DATA.events.find(e=>e.key===k);const isToday=viewYear===2083&&viewMonth===4&&d===5;grid.insertAdjacentHTML('beforeend',`<button class="day ${isToday?'today ':''}${ev?'holiday':''}" data-day="${d}"><span class="bs">${np(d)}</span><span class="ad">${dt.getDate()} ${dt.toLocaleString('en-US',{month:'short'})}</span>${ev?`<span class="event">${ev.title}</span>`:''}</button>`)}grid.querySelectorAll('.day:not(.empty)').forEach(b=>b.onclick=()=>selectDay(Number(b.dataset.day)))}
function selectDay(d){selected={y:viewYear,m:viewMonth,d};renderToday();renderDetail();document.querySelector('#dayDetail').classList.remove('hidden');document.querySelector('#dayDetail').scrollIntoView({behavior:'smooth'});}
function renderPanchang(){const p=DATA.panchang[key(selected.y,selected.m,selected.d)]||{};const items=[['तिथि',p.tithi],['पक्ष',p.paksha],['नक्षत्र',p.nakshatra],['योग',p.yoga],['करण',p.karana],['चन्द्र राशि',p.moon],['सूर्योदय',p.sunrise],['सूर्यास्त',p.sunset],['दिनमान',p.dayLength],['दिन विशेष',p.special],['राहुकाल','स्थानअनुसार गणना आवश्यक'],['चौघडिया','स्थानअनुसार गणना आवश्यक']];document.querySelector('#panchangGrid').innerHTML=items.map(([a,b])=>`<div class="info-card"><span>${a}</span><b>${b||'डेटा उपलब्ध छैन'}</b></div>`).join('')}
function renderEvents(){document.querySelector('#eventList').innerHTML=DATA.events.slice(0,9).map(e=>`<article class="event"><div class="date">${e.bs} · ${e.ad}</div><h3>${e.title}</h3><p>${e.type} · ${daysUntil(e.ad)} दिन बाँकी</p></article>`).join('')}
function daysUntil(s){const d=new Date(s);return Math.max(0,Math.ceil((d-todayAD)/86400000))}
function renderSaait(){const a=[['विवाह','शुभ मुहूर्त डेटा क्रमशः थपिनेछ'],['गृह प्रवेश','शुभ साइत डेटा उपलब्ध भएपछि देखाइनेछ'],['व्रतबन्ध','स्थान र परम्पराअनुसार फरक हुन सक्छ'],['नामकरण','विश्वसनीय स्थिर डेटा आवश्यक']];document.querySelector('#saaitGrid').innerHTML=a.map(x=>`<div class="info-card"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}
function renderZodiac(){document.querySelector('#zodiacGrid').innerHTML=DATA.zodiac.map(z=>`<article class="zodiac"><span class="symbol">${z[0]}</span><b>${z[1]}</b><p>${z[2]}</p></article>`).join('')}
function renderDetail(){const date=dateFor(selected.y,selected.m,selected.d),p=DATA.panchang[key(selected.y,selected.m,selected.d)]||{},ev=DATA.events.filter(e=>e.key===key(selected.y,selected.m,selected.d));document.querySelector('#detailTitle').textContent=`${N.months[selected.m]} ${np(selected.d)}, ${np(selected.y)}`;const items=[['AD',adText(date)],['वार',date?N.week[date.getDay()]:'—'],['तिथि',p.tithi],['पक्ष',p.paksha],['नक्षत्र',p.nakshatra],['योग',p.yoga],['करण',p.karana],['सूर्योदय',p.sunrise],['सूर्यास्त',p.sunset],['चन्द्र राशि',p.moon],['पर्व',ev.map(e=>e.title).join(' / ')||'कुनै विशेष पर्व छैन'],['विशेष',p.special||'—']];document.querySelector('#detailGrid').innerHTML=items.map(x=>`<div class="info-card"><span>${x[0]}</span><b>${x[1]||'डेटा उपलब्ध छैन'}</b></div>`).join('')}
function renderConverter(){document.querySelector('#bsConvert').onclick=()=>{const v=document.querySelector('#bsInput').value.trim().split('-').map(Number);if(v.length!==3||v[0]!==2083||v[1]<1||v[1]>12||v[2]<1||v[2]>DATA.lengths[v[1]-1])return showToast('हाल २०८३ सालको रूपान्तरण डेटा उपलब्ध छ।');const d=dateFor(2083,v[1]-1,v[2]);document.querySelector('#convertResult').textContent=`${np(v[0])}-${np(v[1])}-${np(v[2])} = ${adText(d)}`};document.querySelector('#adConvert').onclick=()=>{const d=new Date(document.querySelector('#adInput').value+'T00:00:00');if(isNaN(d))return showToast('सही AD मिति छान्नुहोस्।');const base=new Date('2026-04-14T00:00:00');const diff=Math.floor((d-base)/86400000);if(diff<0||diff>=365)return showToast('हाल २०८३ सालको रूपान्तरण डेटा उपलब्ध छ।');let rem=diff,m=0;while(rem>=DATA.lengths[m]){rem-=DATA.lengths[m];m++}document.querySelector('#convertResult').textContent=`${d.toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'})} = ${np(2083)}-${np(m+1)}-${np(rem+1)}`}}
function nav(id){const el=document.getElementById(id);if(!el)return;el.scrollIntoView({behavior:'smooth'});document.querySelectorAll('.desktop-nav button').forEach(b=>b.classList.toggle('active',b.dataset.section===id))}
function renderSearch(q){const out=document.querySelector('#searchResults');if(!q){out.innerHTML='';return}const x=q.toLowerCase();const results=[...DATA.events.filter(e=>(e.title+e.bs+e.ad).toLowerCase().includes(x)).map(e=>`<div class="search-result"><b>${e.title}</b><small>${e.bs} · ${e.ad}</small></div>`),...N.months.map((m,i)=>({m,i})).filter(a=>a.m.toLowerCase().includes(x)).map(a=>`<div class="search-result" data-month="${a.i}"><b>${a.m} २०८३</b><small>मासिक पात्रो</small></div>`)] ;out.innerHTML=results.length?results.join(''):'<p class="muted">कुनै नतिजा भेटिएन।</p>';out.querySelectorAll('[data-month]').forEach(e=>e.onclick=()=>{viewMonth=Number(e.dataset.month);renderCalendar();document.querySelector('#searchOverlay').classList.add('hidden');nav('calendar')})}
function showToast(s){const t=document.querySelector('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function tick(){document.querySelector('#clock').textContent=new Date().toLocaleTimeString('ne-NP',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}
function init(){document.querySelector('#yearNow').textContent=new Date().getFullYear();document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>nav(b.dataset.section));document.querySelector('#prevMonth').onclick=()=>{if(viewMonth>0){viewMonth--}else showToast('यस संस्करणमा २०८३ सालको सीमा छ।');renderCalendar()};document.querySelector('#nextMonth').onclick=()=>{if(viewMonth<11)viewMonth++;else showToast('यस संस्करणमा २०८३ सालको सीमा छ।');renderCalendar()};document.querySelector('#monthSelect').onchange=e=>{viewMonth=Number(e.target.value);renderCalendar()};document.querySelector('#todayBtn').onclick=()=>{viewYear=2083;viewMonth=4;selected={y:2083,m:4,d:5};renderCalendar();renderToday();nav('today')};document.querySelector('#closeDetail').onclick=()=>document.querySelector('#dayDetail').classList.add('hidden');document.querySelector('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('patro-theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('patro-theme')==='dark')document.body.classList.add('dark');document.querySelector('#searchBtn').onclick=()=>{document.querySelector('#searchOverlay').classList.remove('hidden');document.querySelector('#searchInput').focus()};document.querySelector('#closeSearch').onclick=()=>document.querySelector('#searchOverlay').classList.add('hidden');document.querySelector('#searchInput').oninput=e=>renderSearch(e.target.value);renderCalendar();renderToday();renderPanchang();renderEvents();renderSaait();renderZodiac();renderDetail();renderConverter();tick();setInterval(tick,1000)}document.addEventListener('DOMContentLoaded',init);
