const N={months:['बैशाख','जेठ','असार','साउन','भदौ','असोज','कात्तिक','मंसिर','पुष','माघ','फागुन','चैत'],enMonths:['Baisakh','Jestha','Ashadh','Shrawan','Bhadra','Ashwin','Kartik','Mangsir','Poush','Magh','Falgun','Chaitra'],week:['आइतबार','सोमबार','मंगलबार','बुधबार','बिहीबार','शुक्रबार','शनिबार'],weekShort:['आइत','सोम','मंगल','बुध','बिही','शुक्र','शनि'],nums:['०','१','२','३','४','५','६','७','८','९']};
const np=n=>String(n).replace(/\d/g,d=>N.nums[d]);
const LENGTHS=[31,31,32,31,31,30,31,29,30,29,30,30];
let DATA={year:2083,days:[],lengths:LENGTHS};let viewMonth=4,selectedIndex=0;
const pad=n=>String(n).padStart(2,'0');const dateKey=(y,m,d)=>`${y}-${pad(m)}-${pad(d)}`;
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
function fallbackData(){const days=[];let ad=new Date(Date.UTC(2026,3,14));for(let m=1;m<=12;m++){for(let d=1;d<=LENGTHS[m-1];d++){const key=dateKey(ad.getUTCFullYear(),ad.getUTCMonth()+1,ad.getUTCDate());days.push({bs:{year:2083,month:m,day:d,monthNepali:N.months[m-1],monthRoman:N.enMonths[m-1],display:`${N.months[m-1]} ${np(d)}, ${np(2083)}`},ad:{date:key,year:ad.getUTCFullYear(),month:ad.getUTCMonth()+1,day:ad.getUTCDate()},weekday:{index:ad.getUTCDay(),nepali:N.week[ad.getUTCDay()]},tithi:{name:'',paksha:null,end:null},nakshatra:{name:'',pada:null,end:null},yoga:{name:'',end:null},karana:{name:'',end:null},sun:{sunrise:null,sunset:null},rahuKaal:null,moonPhase:null,festival:'',holiday:ad.getUTCDay()===6,source:{calendar:'fallback'}});ad.setUTCDate(ad.getUTCDate()+1)}}return{year:2083,days,lengths:LENGTHS}}
function dayFor(m,d){return DATA.days.find(x=>x.bs.month===m&&x.bs.day===d)}function selectedDay(){return DATA.days[selectedIndex]||DATA.days[0]}
function formatAd(d){return d?new Intl.DateTimeFormat('en-US',{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'}).format(new Date(`${d}T00:00:00Z`)):'—'}
function todayIndex(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kathmandu',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const y=Number(p.find(x=>x.type==='year').value),m=Number(p.find(x=>x.type==='month').value),d=Number(p.find(x=>x.type==='day').value);return DATA.days.findIndex(x=>x.ad.year===y&&x.ad.month===m&&x.ad.day===d)}
function renderClock(){const el=document.querySelector('#clock');if(el)el.textContent=new Intl.DateTimeFormat('ne-NP',{timeZone:'Asia/Kathmandu',weekday:'long',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:true}).format(new Date())}
function renderToday(){const x=selectedDay();if(!x)return;document.querySelector('#todayBs').textContent=x.bs.display;document.querySelector('#todayAd').textContent=formatAd(x.ad.date);document.querySelector('#todayWeekday').textContent=x.weekday.nepali;document.querySelector('#todayTithi').textContent=x.tithi?.name||'तिथि डेटा उपलब्ध छैन';document.querySelector('#todayPaksha').textContent=x.tithi?.paksha?`पक्ष: ${x.tithi.paksha}`:'';document.querySelector('#sunrise').textContent=x.sun?.sunrise||'—';document.querySelector('#sunset').textContent=x.sun?.sunset||'—';document.querySelector('#nakshatra').textContent=x.nakshatra?.name||'—';document.querySelector('#moon').textContent=x.moonPhase?.name||'—';document.querySelector('#todayFestivalBadge').textContent=x.festival||''}
function renderCalendar(){const year=document.querySelector('#yearSelect'),month=document.querySelector('#monthSelect');if(!year||!month)return;year.innerHTML='<option value="2083">२०८३</option>';month.innerHTML=N.months.map((v,i)=>`<option value="${i+1}">${v}</option>`).join('');month.value=viewMonth;const grid=document.querySelector('#calendarGrid');grid.innerHTML='';const first=dayFor(viewMonth,1);for(let i=0;i<(first?.weekday?.index||0);i++)grid.insertAdjacentHTML('beforeend','<div class="day empty"></div>');for(let d=1;d<=LENGTHS[viewMonth-1];d++){const x=dayFor(viewMonth,d),isToday=x&&DATA.days[todayIndex()]===x,isSel=x&&DATA.days[selectedIndex]===x;grid.insertAdjacentHTML('beforeend',`<button class="day ${isToday?'today ':''}${x?.festival?'holiday ':''}${isSel?'selected ':''}" data-day="${d}"><span class="bs">${np(d)}</span><span class="ad">${x?.ad.day||'—'} ${x?new Intl.DateTimeFormat('en-US',{month:'short',timeZone:'UTC'}).format(new Date(`${x.ad.date}T00:00:00Z`)):''}</span>${x?.festival?`<span class="event">${esc(x.festival)}</span>`:''}${x?.holiday?'<i class="holiday-mark">●</i>':''}</button>`)}grid.querySelectorAll('button.day').forEach(b=>b.onclick=()=>selectDay(viewMonth,Number(b.dataset.day)))}
function selectDay(m,d){const i=DATA.days.findIndex(x=>x.bs.month===m&&x.bs.day===d);if(i<0)return;selectedIndex=i;viewMonth=m;renderAll();document.querySelector('#dayDetail')?.scrollIntoView({behavior:'smooth',block:'start'})}
function renderPanchang(){const x=selectedDay(),p=[['वार',x.weekday?.nepali],['तिथि',x.tithi?.name],['पक्ष',x.tithi?.paksha],['नक्षत्र',x.nakshatra?.pada?`${x.nakshatra.name} (पाद ${x.nakshatra.pada})`:x.nakshatra?.name],['योग',x.yoga?.name],['करण',x.karana?.name],['सूर्योदय',x.sun?.sunrise],['सूर्यास्त',x.sun?.sunset],['राहुकाल',x.rahuKaal?`${x.rahuKaal.start} – ${x.rahuKaal.end}`:'—'],['चन्द्र अवस्था',x.moonPhase?.name],['चन्द्र प्रकाश',x.moonPhase?.illuminated!=null?`${Math.round(x.moonPhase.illuminated*100)}%`:'—'],['दिन विशेष',x.festival||'—']];document.querySelector('#panchangGrid').innerHTML=p.map(([a,b])=>`<div class="info-card"><span>${esc(a)}</span><b>${esc(b||'डेटा उपलब्ध छैन')}</b></div>`).join('')}
function renderEvents(){const upcoming=DATA.days.filter(x=>x.festival||x.holiday).filter(x=>x.ad.date>=selectedDay().ad.date).slice(0,12);document.querySelector('#eventList').innerHTML=upcoming.length?upcoming.map(x=>`<article class="event"><div class="date">${esc(x.bs.display)} · ${esc(x.ad.date)}</div><h3>${esc(x.festival||'साप्ताहिक बिदा')}</h3><p>${x.holiday?'बिदा':'पर्व'} · ${daysUntil(x.ad.date)} दिन बाँकी</p></article>`).join(''):'<div class="news-empty">आगामी पर्व/बिदा डेटा उपलब्ध छैन।</div>'}
function daysUntil(s){const a=new Date(`${selectedDay().ad.date}T00:00:00Z`),b=new Date(`${s}T00:00:00Z`);return Math.max(0,Math.round((b-a)/86400000))}
function renderSaait(){const rows=DATA.days.filter(x=>x.festival&&/विवाह|व्रतबन्ध|पास्नी|गृह प्रवेश|नामकरण/.test(x.festival));document.querySelector('#saaitGrid').innerHTML=rows.length?rows.slice(0,20).map(x=>`<div class="info-card"><span>${x.bs.display}</span><b>${esc(x.festival)}</b></div>`).join(''):'<div class="info-card"><span>साइत</span><b>विश्वसनीय स्थिर साइत डेटा उपलब्ध भएपछि यहाँ देखाइनेछ।</b></div>'}
const Z=[['♈','मेष'],['♉','वृष'],['♊','मिथुन'],['♋','कर्कट'],['♌','सिंह'],['♍','कन्या'],['♎','तुला'],['♏','वृश्चिक'],['♐','धनु'],['♑','मकर'],['♒','कुम्भ'],['♓','मीन']];
function renderZodiac(){const text=['आज नयाँ योजना बनाउँदा स्पष्ट प्राथमिकता राख्नुहोस्।','आर्थिक निर्णयमा धैर्य र तथ्यलाई प्राथमिकता दिनुहोस्।','सम्पर्क र संवादबाट उपयोगी अवसर आउन सक्छ।','परिवार र व्यक्तिगत जिम्मेवारीबीच सन्तुलन राख्नुहोस्।','आत्मविश्वास राम्रो छ, तर निर्णयमा संयम राख्नुहोस्।','सानो विवरणमा ध्यान दिँदा काम राम्रो बन्नेछ।','सम्बन्धमा स्पष्ट र शान्त संवाद उपयोगी हुनेछ।','हतारमा निर्णय नगर्नुहोस्; प्रमाण जाँच गर्नुहोस्।','नयाँ कुरा सिक्ने वा सुरु गर्ने ऊर्जा बढ्न सक्छ।','नियमित मेहनतको परिणाम विस्तारै देखिनेछ।','नयाँ विचारलाई व्यवहारिक योजनामा बदल्नुहोस्।','आराम, सिर्जनशीलता र कामबीच सन्तुलन राख्नुहोस्।'];document.querySelector('#zodiacGrid').innerHTML=Z.map(([s,n],i)=>`<article class="zodiac"><span class="symbol">${s}</span><b>${n}</b><p>${text[i]}</p></article>`).join('')}
function renderDetail(){const x=selectedDay(),p=[['ईस्वी मिति',formatAd(x.ad.date)],['वार',x.weekday.nepali],['तिथि',x.tithi?.name],['पक्ष',x.tithi?.paksha],['नक्षत्र',x.nakshatra?.name],['योग',x.yoga?.name],['करण',x.karana?.name],['सूर्योदय',x.sun?.sunrise],['सूर्यास्त',x.sun?.sunset],['राहुकाल',x.rahuKaal?`${x.rahuKaal.start} – ${x.rahuKaal.end}`:'—'],['पर्व/बिदा',x.festival||'कुनै विशेष पर्व छैन'],['चन्द्र अवस्था',x.moonPhase?.name||'—']];document.querySelector('#detailTitle').textContent=x.bs.display;document.querySelector('#detailGrid').innerHTML=p.map(([a,b])=>`<div class="info-card"><span>${esc(a)}</span><b>${esc(b||'डेटा उपलब्ध छैन')}</b></div>`).join('')}
function renderConverter(){const result=document.querySelector('#convertResult');const show=x=>result.innerHTML=x;document.querySelector('#bsConvert').onclick=()=>{const raw=document.querySelector('#bsInput').value.trim().replace(/[०-९]/g,d=>N.nums.indexOf(d)).replace(/[\/\.]/g,'-');const [y,m,d]=raw.split('-').map(Number);const x=DATA.days.find(v=>v.bs.year===y&&v.bs.month===m&&v.bs.day===d);if(!x)return show('<span style="color:#b91c1c">२०८३ को मान्य मिति लेख्नुहोस्, जस्तै 2083-05-05।</span>');document.querySelector('#adInput').value=x.ad.date;show(`<strong>${x.bs.display}</strong> → <strong>${formatAd(x.ad.date)}</strong><br><small>${x.weekday.nepali} · ${x.tithi?.name||''}</small>`)};document.querySelector('#adConvert').onclick=()=>{const raw=document.querySelector('#adInput').value;const x=DATA.days.find(v=>v.ad.date===raw);if(!x)return show('<span style="color:#b91c1c">यो AD मिति २०८३ BS को दायराभन्दा बाहिर छ।</span>');document.querySelector('#bsInput').value=`${x.bs.year}-${pad(x.bs.month)}-${pad(x.bs.day)}`;show(`<strong>${formatAd(raw)}</strong> → <strong>${x.bs.display}</strong><br><small>${x.weekday.nepali} · ${x.tithi?.name||''}</small>`)}}
function renderAll(){renderToday();renderCalendar();renderPanchang();renderEvents();renderSaait();renderZodiac();renderDetail()}
function navigateSection(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'})}
function initUI(){document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>navigateSection(b.dataset.section));document.querySelector('#prevMonth').onclick=()=>{if(viewMonth>1){viewMonth--;selectedIndex=DATA.days.findIndex(x=>x.bs.month===viewMonth&&x.bs.day===1);renderAll()}};document.querySelector('#nextMonth').onclick=()=>{if(viewMonth<12){viewMonth++;selectedIndex=DATA.days.findIndex(x=>x.bs.month===viewMonth&&x.bs.day===1);renderAll()}};document.querySelector('#monthSelect').onchange=e=>{viewMonth=Number(e.target.value);selectedIndex=DATA.days.findIndex(x=>x.bs.month===viewMonth&&x.bs.day===1);renderAll()};document.querySelector('#todayBtn').onclick=()=>{const i=todayIndex();if(i>=0){selectedIndex=i;viewMonth=DATA.days[i].bs.month;renderAll();navigateSection('today')}};document.querySelector('#closeDetail').onclick=()=>navigateSection('calendar');document.querySelector('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('patro-theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('patro-theme')==='dark')document.body.classList.add('dark');document.querySelector('#searchBtn').onclick=()=>{document.querySelector('#searchOverlay').classList.remove('hidden');document.querySelector('#searchInput').focus()};document.querySelector('#closeSearch').onclick=()=>document.querySelector('#searchOverlay').classList.add('hidden');document.querySelector('#searchInput').oninput=e=>searchPatro(e.target.value);document.querySelector('#yearNow').textContent=new Date().getFullYear();renderClock();setInterval(renderClock,1000);renderConverter()}
function searchPatro(q){const root=document.querySelector('#searchResults');q=q.trim().toLocaleLowerCase('ne');if(!q){root.innerHTML='';return}const hits=DATA.days.filter(x=>`${x.bs.display} ${x.ad.date} ${x.weekday.nepali} ${x.festival||''} ${x.tithi?.name||''}`.toLocaleLowerCase('ne').includes(q)).slice(0,15);root.innerHTML=hits.length?hits.map(x=>`<div class="search-result" data-m="${x.bs.month}" data-d="${x.bs.day}"><b>${esc(x.bs.display)}</b><br><small>${esc(x.ad.date)} · ${esc(x.festival||x.tithi?.name||x.weekday.nepali)}</small></div>`).join(''):'<p class="muted">कुनै नतिजा भेटिएन।</p>';root.querySelectorAll('.search-result').forEach(r=>r.onclick=()=>{selectDay(Number(r.dataset.m),Number(r.dataset.d));document.querySelector('#searchOverlay').classList.add('hidden')})}
async function boot(){try{const r=await fetch('data/calendar/2083.json?'+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('calendar data unavailable');DATA=await r.json();if(!Array.isArray(DATA.days)||DATA.days.length!==365)throw new Error('2083 dataset must contain exactly 365 days')}catch(e){console.warn('[Nepali Patro] generated data not available yet; using fallback calendar',e);DATA=fallbackData()}const i=todayIndex();selectedIndex=i>=0?i:0;viewMonth=selectedDay().bs.month;initUI();renderAll()}
document.addEventListener('DOMContentLoaded',boot);
