(()=>{'use strict';
const NUMS='०१२३४५६७८९';let mode='bs';let Converter=null;
const $=id=>document.getElementById(id);
const toEn=v=>String(v).replace(/[०-९]/g,d=>String(NUMS.indexOf(d)));
const toNp=v=>String(v).replace(/\d/g,d=>NUMS[d]);
const pad=n=>String(n).padStart(2,'0');
const fail=m=>{$('error').textContent=m;$('error').hidden=false;$('result').hidden=true};
const clearError=()=>{$('error').hidden=true};
const ok=(title,sub,meta='')=>{$('result').innerHTML=`<span class="big">${title}</span><span class="sub">${sub}</span>${meta}`;$('result').hidden=false;clearError()};
function parseParts(v){const p=toEn(v.trim()).replace(/[/.\s]+/g,'-').split('-').filter(Boolean).map(Number);return p.length===3&&p.every(Number.isInteger)?p:null}
function validBs(y,m,d){return y>=1975&&y<=2099&&m>=1&&m<=12&&d>=1&&d<=32}
function validAd(y,m,d){const x=new Date(Date.UTC(y,m-1,d));return x.getUTCFullYear()===y&&x.getUTCMonth()===m-1&&x.getUTCDate()===d}
function makeMeta(weekday,ad,bs){return `<div class="meta"><div><b>वार</b><span>${weekday}</span></div><div><b>AD</b><span>${ad}</span></div><div><b>BS</b><span>${bs}</span></div></div>`}
function draw(){const f=$('form');f.innerHTML=mode==='bs'?`<div class="field"><label for="date">वि.सं. मिति</label><input id="date" inputmode="numeric" autocomplete="off" placeholder="२०८३-०५-१०" aria-label="वि.सं. मिति"></div><div class="actions"><button class="convert" id="go" type="button">AD मा रूपान्तरण गर्नुहोस्</button><button class="swap" id="today" type="button">आज</button></div>`:`<div class="field"><label for="date">ईस्वी मिति</label><input id="date" type="date" aria-label="ईस्वी मिति"></div><div class="actions"><button class="convert" id="go" type="button">BS मा रूपान्तरण गर्नुहोस्</button><button class="swap" id="today" type="button">आज</button></div>`;$('go').onclick=convert;$('today').onclick=fillToday;$('date').addEventListener('keydown',e=>{if(e.key==='Enter')convert()})}
function fillToday(){const now=new Date();if(mode==='ad'){$('date').value=`${now.getFullYear()}-${pad(now.getMonth()+1)}-${pad(now.getDate())}`;convert();return}try{const b=new Converter(`${now.getFullYear()}-${pad(now.getMonth()+1)}-${pad(now.getDate())}`).toBs();$('date').value=`${toNp(b.year)}-${toNp(pad(b.month))}-${toNp(pad(b.date))}`;convert()}catch(e){fail('आजको BS मिति निकाल्न सकिएन।')}}
function convert(){if(typeof Converter!=='function')return fail('रूपान्तरण इन्जिन लोड हुन सकेन। पेज reload गरेर पुनः प्रयास गर्नुहोस्।');clearError();$('result').hidden=true;try{if(mode==='bs'){const p=parseParts($('date').value);if(!p)return fail('सही ढाँचा प्रयोग गर्नुहोस्: २०८३-०५-१०');const[y,m,d]=p;if(!validBs(y,m,d))return fail('हाल यो converter ले BS १९७५–२०९९ मात्र समर्थन गर्छ।');const x=new Converter(`${y}-${pad(m)}-${pad(d)}`).toAd();if(!x||!x.year)return fail('यो BS मिति रूपान्तरण हुन सकेन।');const ad=`${x.year}-${pad(x.month)}-${pad(x.date)}`,bs=`${y}-${pad(m)}-${pad(d)}`;ok(ad,`वि.सं. ${toNp(bs)}`,makeMeta(x.day,ad,toNp(bs)))}else{const value=$('date').value;if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return fail('ईस्वी मिति छान्नुहोस्।');const [y,m,d]=value.split('-').map(Number);if(!validAd(y,m,d))return fail('मान्य Gregorian मिति छान्नुहोस्।');const x=new Converter(value).toBs();if(!x||!x.year)return fail('यो AD मिति रूपान्तरण हुन सकेन।');const bs=`${x.year}-${pad(x.month)}-${pad(x.date)}`,ad=`${y}-${pad(m)}-${pad(d)}`;ok(toNp(bs),`ईस्वी ${ad}`,makeMeta(x.day,ad,toNp(bs)))}}catch(e){fail(e&&e.message?`मिति रूपान्तरण हुन सकेन: ${e.message}`:'अमान्य मिति।')}}
function setMode(next){mode=next;$('bsTab').classList.toggle('active',mode==='bs');$('adTab').classList.toggle('active',mode==='ad');draw();$('result').hidden=true;clearError()}
function init(){if(typeof window.DateConverter==='function'){Converter=window.DateConverter;$('status').textContent='रूपान्तरण इन्जिन तयार छ';draw();$('bsTab').onclick=()=>setMode('bs');$('adTab').onclick=()=>setMode('ad')}else{$('status').textContent='रूपान्तरण इन्जिन लोड भएन';fail('Converter library लोड भएन। CDN उपलब्ध नभए page reload गर्नुहोस्।')}}
document.addEventListener('DOMContentLoaded',init);
})();