(()=>{'use strict';
const NUMS='०१२३४५६७८९';let mode='bs';let engine=null;
const $=id=>document.getElementById(id);
const toEn=v=>String(v).replace(/[०-९]/g,d=>String(NUMS.indexOf(d)));
const toNp=v=>String(v).replace(/\d/g,d=>NUMS[d]);
const pad=n=>String(n).padStart(2,'0');
const fail=m=>{$('error').textContent=m;$('error').hidden=false;$('result').hidden=true};
const clearError=()=>{$('error').hidden=true};
const ok=(title,sub,meta='')=>{$('result').innerHTML=`<span class="big">${title}</span><span class="sub">${sub}</span>${meta}`;$('result').hidden=false;clearError()};
function parseParts(v){const p=toEn(v.trim()).replace(/[/.\s]+/g,'-').split('-').filter(Boolean).map(Number);return p.length===3&&p.every(Number.isInteger)?p:null}
function validateBs(y,m,d){if(y<1970||y>2100||m<1||m>12||d<1||d>32)return false;return true}
function draw(){const f=$('form');f.innerHTML=mode==='bs'?`<div class="field"><label for="date">वि.सं. मिति</label><input id="date" inputmode="numeric" autocomplete="off" placeholder="२०८३-०५-१०" aria-label="वि.सं. मिति"></div><div class="actions"><button class="convert" id="go" type="button">AD मा रूपान्तरण गर्नुहोस्</button><button class="swap" id="today" type="button">आज</button></div>`:`<div class="field"><label for="date">ईस्वी मिति</label><input id="date" type="date" aria-label="ईस्वी मिति"></div><div class="actions"><button class="convert" id="go" type="button">BS मा रूपान्तरण गर्नुहोस्</button><button class="swap" id="today" type="button">आज</button></div>`;
$('go').onclick=convert;$('today').onclick=fillToday;$('date').addEventListener('keydown',e=>{if(e.key==='Enter')convert()});
}
function fillToday(){const now=new Date();if(mode==='ad'){$('date').value=`${now.getFullYear()}-${pad(now.getMonth()+1)}-${pad(now.getDate())}`;convert();return}try{const n=new engine(now);const b=n.getBS();$('date').value=`${toNp(b.year)}-${toNp(pad(b.month+1))}-${toNp(pad(b.date))}`;convert()}catch(e){fail('आजको BS मिति निकाल्न सकिएन।')}}
function convert(){if(!engine)return fail('रूपान्तरण इन्जिन तयार भएको छैन। पेज refresh गरेर पुनः प्रयास गर्नुहोस्।');clearError();$('result').hidden=true;
try{if(mode==='bs'){const p=parseParts($('date').value);if(!p)return fail('सही ढाँचा प्रयोग गर्नुहोस्: २०८३-०५-१०');const[y,m,d]=p;if(!validateBs(y,m,d))return fail('BS वर्ष १९७०–२१००, महिना १–१२ र दिन १–३२ भित्र हुनुपर्छ।');const n=new engine(y,m-1,d);const a=n.getAD();const js=n.toJsDate();if(!a||!a.year)return fail('यो BS मिति रूपान्तरण डेटामा उपलब्ध छैन।');const ad=`${a.year}-${pad(a.month+1)}-${pad(a.date)}`;ok(ad,`वि.सं. ${toNp(y)}-${toNp(pad(m))}-${toNp(pad(d))}`,`<div class="meta"><div><b>वार</b><span>${js.toLocaleDateString('ne-NP',{weekday:'long'})}</span></div><div><b>AD</b><span>${ad}</span></div><div><b>BS</b><span>${toNp(y)}/${toNp(pad(m))}/${toNp(pad(d))}</span></div></div>`)}else{const value=$('date').value;if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return fail('ईस्वी मिति छान्नुहोस्।');const [y,m,d]=value.split('-').map(Number);const n=new engine(new Date(y,m-1,d));const b=n.getBS();if(!b||!b.year)return fail('यो AD मिति रूपान्तरण डेटामा उपलब्ध छैन।');const bs=`${b.year}-${pad(b.month+1)}-${pad(b.date)}`;ok(toNp(bs),`ईस्वी ${value}`,`<div class="meta"><div><b>वार</b><span>${new Date(y,m-1,d).toLocaleDateString('ne-NP',{weekday:'long'})}</span></div><div><b>AD</b><span>${value}</span></div><div><b>BS</b><span>${toNp(bs)}</span></div></div>`)}}catch(e){fail(e&&e.message?`मिति रूपान्तरण हुन सकेन: ${e.message}`:'अमान्य मिति।')}}
function setMode(next){mode=next;$('bsTab').classList.toggle('active',mode==='bs');$('adTab').classList.toggle('active',mode==='ad');draw();$('result').hidden=true;clearError();}
function init(){try{engine=window.NepaliDate||window.nepaliDateConverter||window.default;if(typeof engine!=='function')throw Error('NepaliDate library not found');$('status').textContent='रूपान्तरण इन्जिन तयार छ • बाह्य API आवश्यक छैन';draw();$('bsTab').onclick=()=>setMode('bs');$('adTab').onclick=()=>setMode('ad');}catch(e){$('status').textContent='रूपान्तरण इन्जिन लोड भएन';fail('रूपान्तरण library लोड हुन सकेन। Internet connection जाँच गरेर refresh गर्नुहोस्।')}}
document.addEventListener('DOMContentLoaded',init);
})();