const NP={today:new Date(),fmt:d=>new Intl.DateTimeFormat('ne-NP',{dateStyle:'full'}).format(d),pad:n=>String(n).padStart(2,'0')};function set(id,v){const e=document.getElementById(id);if(e)e.innerHTML=v}function neTime(){return new Intl.DateTimeFormat('ne-NP',{timeZone:'Asia/Kathmandu',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date())}
(()=>{function enhance(){const all=document.querySelector('#all-tools');if(!all||all.dataset.enhanced)return;all.dataset.enhanced='1';const grid=all.querySelector('.grid');if(!grid)return;
const catalog=[
['मुख्य पात्रो सेवाहरू',[['पूर्ण पात्रो','📅','महिना र वर्षअनुसार नेपाली पात्रो।','/patro/'],['दैनिक पञ्चाङ्ग','☀️','तिथि, नक्षत्र, योग, करण र दैनिक समय।','/panchanga/'],['BS ↔ AD Converter','⇄','बिक्रम संवत् र ईस्वी मिति रूपान्तरण।','/converter/'],['दैनिक राशिफल','♈','१२ राशिको दैनिक राशिफल।','/rashifal/'],['पर्व तथा बिदा','🎉','नेपाली पर्व, उत्सव र सार्वजनिक बिदा।','/parba/'],['शुभ साइत','✨','शुभ मुहूर्त र साइत सम्बन्धी जानकारी।','/saith/']]],
['ज्योतिष तथा संस्कृति',[['जन्मकुण्डली','🪐','जन्म विवरणबाट विस्तृत कुण्डली तयार गर्नुहोस्।','/jyotish/'],['आजको इतिहास','📜','आजकै दिनसँग जोडिएका इतिहास र संस्कृति।','/itihas-aaja/']]],
['नेपालका उपयोगी सेवाहरू',[['नेपाल समाचार','📰','प्रमुख नेपाली समाचारहरू एकै ठाउँमा।','/news/'],['सुनको मूल्य','🪙','नेपालको दैनिक सुन तथा चाँदीको मूल्य।','/gold-price/'],['विदेशी मुद्रा','💱','विदेशी मुद्राको विनिमय दर हेर्नुहोस्।','/forex/'],['बैंक ब्याजदर','🏦','बचत र मुद्दती निक्षेपका बैंक दरहरू।','/interest-rate/']]]
];
const existing=[...grid.querySelectorAll(':scope > a.card')];const byName=new Map(existing.map(c=>[(c.querySelector('h3')?.textContent||'').trim(),c]));existing.forEach(c=>c.remove());
const wrap=document.createElement('div');wrap.className='np-tool-groups';catalog.forEach(([title,names],i)=>{const section=document.createElement('section');section.className='np-tool-group';section.dataset.group=['core','astro','more'][i]||'more';const h=document.createElement('div');h.className='np-tool-group-head';h.innerHTML='<h3>'+title+'</h3><span>'+names.length+' सेवा</span>';section.appendChild(h);const g=document.createElement('div');g.className='np-tool-grid';names.forEach(([name,icon,desc,path])=>{let card=byName.get(name);if(!card){card=document.createElement('a');card.className='card';card.href='/Nepali-Patro'+path;card.innerHTML='<span class="pill">'+icon+' '+name+'</span><h3>'+name+'</h3><p class="muted">'+desc+'</p>'}else{card.querySelector('.pill')?.insertAdjacentText('afterbegin',icon+' ');card.querySelector('p')?.classList.add('muted')}g.appendChild(card)});section.appendChild(g);wrap.appendChild(section)});grid.replaceWith(wrap);
all.querySelector('.np-heading')?.insertAdjacentHTML('afterend','<div class="np-tool-filter" role="tablist" aria-label="सेवा श्रेणी"><button type="button" class="active" data-tool-filter="all">सबै</button><button type="button" data-tool-filter="core">मुख्य</button><button type="button" data-tool-filter="astro">ज्योतिष</button><button type="button" data-tool-filter="more">नेपाल</button></div>');const sections=[...wrap.children];all.querySelectorAll('[data-tool-filter]').forEach(b=>b.addEventListener('click',()=>{all.querySelectorAll('[data-tool-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.toolFilter;sections.forEach(s=>s.hidden=f!=='all'&&s.dataset.group!==f)}));document.querySelectorAll('a[href*="/Nepali-Patro/calendar/"]').forEach(a=>{a.href=a.href.replace('/calendar/','/patro/')});const nav=document.querySelector('.np-header nav');if(nav&&!nav.querySelector('[data-tools-link]')){const a=document.createElement('a');a.href='#all-tools';a.textContent='सबै सेवाहरू';a.dataset.toolsLink='1';nav.appendChild(a)}const mobile=document.querySelector('#mobileMenu');if(mobile&&!mobile.querySelector('[data-tools-link]')){const a=document.createElement('a');a.href='#all-tools';a.textContent='🧰 सबै उपकरण तथा सेवाहरू';a.dataset.toolsLink='1';a.addEventListener('click',()=>{document.querySelector('#mobileMenuClose')?.click()});mobile.appendChild(a)}}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance,{once:true});else enhance()})();