(()=>{
'use strict';
const ROOT='https://apps.laxmannepal.com.np/Nepali-Patro/';
const MONTHS=['बैशाख','जेठ','असार','साउन','भदौ','असोज','कात्तिक','मंसिर','पुष','माघ','फागुन','चैत'];
const WEEK=['आइत','सोम','मंगल','बुध','बिही','शुक्र','शनि'];
const Z=[['♈','मेष'],['♉','वृष'],['♊','मिथुन'],['♋','कर्कट'],['♌','सिंह'],['♍','कन्या'],['♎','तुला'],['♏','वृश्चिक'],['♐','धनु'],['♑','मकर'],['♒','कुम्भ'],['♓','मीन']];
const nep=n=>String(n??'').replace(/\d/g,d=>'०१२३४५६७८९'[d]);
const ascii=n=>String(n??'').replace(/[०-९]/g,d=>'०१२३४५६७८९'.indexOf(d));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const todayAD=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kathmandu'}).format(new Date());
const findToday=days=>days.find(x=>x?.ad?.date===todayAD())||days[0];
const cacheKey=p=>`${ROOT}${p}`;
async function loadJSON(path,{ttl=300000,force=false}={}){
  const key=cacheKey(path); const now=Date.now();
  if(!force){try{const raw=sessionStorage.getItem(`np:${path}`);if(raw){const x=JSON.parse(raw);if(now-x.time<ttl)return x.data}}catch{}}
  const r=await fetch(`${key}?v=${Math.floor(now/ttl)}`,{cache:'default'}); if(!r.ok)throw Error(`${path}: ${r.status}`);
  const data=await r.json(); try{sessionStorage.setItem(`np:${path}`,JSON.stringify({time:now,data}))}catch{} return data;
}
function injectStyles(){if(document.getElementById('npRuntimeStyles'))return;const s=document.createElement('style');s.id='npRuntimeStyles';s.textContent=`#calendarPreview{width:100%;overflow:hidden}.np-home-cal-grid{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:5px}.np-home-cal-cell{min-width:0;min-height:48px;text-decoration:none;color:inherit;border:1px solid #e5e7eb;border-radius:9px;padding:6px;display:block;box-sizing:border-box;overflow:hidden}.np-home-cal-cell b{font-size:14px}.np-home-cal-cell small,.np-home-cal-cell span{display:block;color:#68707d;font-size:8px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.np-home-cal-cell span{color:#b91c1c}.np-finance-panel{overflow:hidden}.np-forex-grid,.np-gold-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.np-forex-item,.np-gold-item{border:1px solid #e5e7eb;border-radius:14px;padding:12px;background:#fff}.np-forex-item{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:4px 9px}.np-forex-flag{font-size:25px;grid-row:span 2}.np-forex-item div{min-width:0}.np-forex-item div small{display:block;font-size:10px;color:#68707d;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.np-forex-item strong{font-size:13px;text-align:right}.np-gold-item{display:flex;align-items:center;justify-content:space-between;gap:10px}.np-gold-name b,.np-gold-name small{display:block}.np-gold-name small{color:#68707d;font-size:10px;margin-top:3px}.np-gold-price{text-align:right}.np-gold-price strong{display:block;font-size:20px}.np-gold-price small{font-size:10px;color:#68707d}.np-finance-loading,.np-finance-empty{padding:18px;text-align:center;color:#68707d}@media(max-width:900px){.np-forex-grid,.np-gold-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.np-home-cal-grid{gap:3px}.np-home-cal-cell{min-height:42px;padding:4px}.np-home-cal-cell b{font-size:12px}.np-home-cal-cell small,.np-home-cal-cell span{font-size:7px}.np-forex-grid,.np-gold-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function renderCalendar(data,x){const e=document.getElementById('calendarPreview');if(!e)return;const y=x.bs.year,m=x.bs.month,days=data.days.filter(d=>d.bs.year===y&&d.bs.month===m),first=days.find(d=>d.bs.day===1),count=data.lengths?.[m-1]||days.length;let h=`<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px;gap:8px"><strong>${MONTHS[m-1]} ${nep(y)}</strong><span style="color:#68707d;font-size:11px">${nep(count)} दिन</span></div><div class="np-home-cal-grid">${WEEK.map(v=>`<div style="text-align:center;color:#68707d;font-size:10px;font-weight:800;padding:5px">${v}</div>`).join('')}`;for(let i=0;i<(first?.weekday?.index||0);i++)h+='<div></div>';for(const q of days){const selected=q.ad.date===x.ad.date;h+=`<a class="np-home-cal-cell" href="${ROOT}calendar/?year=${q.bs.year}&month=${q.bs.month}&date=${q.ad.date}" style="border-color:${selected?'#fecaca':'#e5e7eb'};background:${selected?'#fff1f2':'#fff'}"><b>${nep(q.bs.day)}</b><small>${esc(q.ad.day||'')}</small>${q.festival?`<span>${esc(q.festival)}</span>`:''}</a>`}e.innerHTML=h+'</div>'}
function render(data){const days=data.days||[],x=findToday(days);if(!x)return;injectStyles();const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v??'डेटा उपलब्ध छैन'};set('todayBs',x.bs?.display||`${nep(x.bs?.year)} ${MONTHS[(x.bs?.month||1)-1]} ${nep(x.bs?.day)}`);set('todayAd',x.ad?.date||'');const p=document.getElementById('panchangaPreview');if(p){const rows=[['वार',x.weekday?.nepali],['तिथि',x.tithi?.name],['पक्ष',x.tithi?.paksha],['नक्षत्र',x.nakshatra?.name],['योग',x.yoga?.name],['करण',x.karana?.name],['सूर्योदय',x.sun?.sunrise],['सूर्यास्त',x.sun?.sunset],['राशि',x.rashi],['पर्व',x.festival]];p.innerHTML=rows.map(r=>`<div class="np-stat"><small>${esc(r[0])}</small><b>${esc(r[1]||'—')}</b></div>`).join('')}renderCalendar(data,x);const parba=document.getElementById('parbaPreview');if(parba){const rows=days.filter(d=>d.festival||d.holiday).filter(d=>d.ad.date>=x.ad.date).slice(0,3);parba.innerHTML=rows.length?rows.map(d=>`<article class="np-event"><small>${esc(d.bs.display)}</small><b>${esc(d.festival||'बिदा')}</b><span>${d.holiday?'🇳🇵 बिदा':'🎉 पर्व'}</span></article>`).join(''):'<div class="np-event">आगामी पर्व डेटा उपलब्ध छैन।</div>'}const rash=document.getElementById('rashifalPreview');if(rash)rash.innerHTML=Z.map(a=>`<a href="${ROOT}rashifal/?date=${encodeURIComponent(x.ad.date)}"><i>${a[0]}</i><b>${a[1]}</b><span>दैनिक राशिफल</span></a>`).join('');
  loadSecondary();
}
async function loadSecondary(){
  const news=document.getElementById('newsPreview');
  if(news){try{const j=await loadJSON('feeds/news.json',{ttl:180000});const items=(Array.isArray(j)?j:(j.items||[])).filter(x=>x?.title&&x?.articleUrl).sort((a,b)=>new Date(b.publishedTime||0)-new Date(a.publishedTime||0)).slice(0,6);news.innerHTML=items.length?`<div class="np-news-feature"><small>मुख्य समाचार</small><h3>${esc(items[0].title)}</h3><p>${esc(items[0].description||'पूरा समाचार पढ्नुहोस्।')}</p><a class="np-primary" href="${esc(items[0].articleUrl)}" target="_blank" rel="noopener">पूरा समाचार →</a></div><div class="np-news-list">${items.slice(1).map(n=>`<a class="np-news-item" href="${esc(n.articleUrl)}" target="_blank" rel="noopener"><b>${esc(n.title)}</b></a>`).join('')}</div>`:'<div class="np-finance-empty">समाचार उपलब्ध छैन।</div>'}catch{news.innerHTML='<div class="np-finance-empty">समाचार डेटा अहिले उपलब्ध छैन।</div>'}}
  const fx=document.getElementById('forexPreview'); if(fx)try{const j=await loadJSON('feeds/forex.json',{ttl:900000});const rates=(j.rates||[]).slice(0,6);fx.innerHTML=`<div class="np-forex-grid">${rates.map(r=>`<div class="np-forex-item"><span class="np-forex-flag">💱</span><div><b>${esc(r.currency||'')}</b><small>${esc(r.name||'विदेशी मुद्रा')}</small></div><strong>${esc(r.buy??'—')}</strong></div>`).join('')}</div>`}catch{fx.innerHTML='<div class="np-finance-empty">विदेशी मुद्रा डेटा उपलब्ध छैन।</div>'}
  const gold=document.getElementById('goldPreview'); if(gold)try{const j=await loadJSON('feeds/gold_silver.json',{ttl:900000});gold.innerHTML=`<div class="np-gold-grid"><div class="np-gold-item"><div class="np-gold-name"><b>छापावाल सुन</b><small>${esc(j.gold?.unit||'प्रति तोला')}</small></div><div class="np-gold-price"><strong>रु. ${esc(j.gold?.price||'—')}</strong></div></div><div class="np-gold-item"><div class="np-gold-name"><b>चाँदी</b><small>${esc(j.silver?.unit||'प्रति तोला')}</small></div><div class="np-gold-price"><strong>रु. ${esc(j.silver?.price||'—')}</strong></div></div></div>`}catch{gold.innerHTML='<div class="np-finance-empty">सुन तथा चाँदीको डेटा उपलब्ध छैन।</div>'}
}
async function boot(){try{const data=await loadJSON('data/calendar/2083.json',{ttl:86400000});render(data)}catch(e){console.error('Nepali Patro homepage:',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
