(()=>{'use strict';
const ROOT='https://apps.laxmannepal.com.np/Nepali-Patro/';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money=n=>{const x=Number(n);return Number.isFinite(x)?x.toLocaleString('ne-NP',{maximumFractionDigits:2}):'—'};
async function get(file){const r=await fetch(`${ROOT}${file}`,{cache:'no-cache'});if(!r.ok)throw Error(`${file} HTTP ${r.status}`);return r.json()}
function ensureRoot(){let root=document.querySelector('#financePreview');if(root)return root;const section=[...document.querySelectorAll('main .np-section')].find(s=>/बैंक ब्याजदर/.test(s.textContent||''));if(!section)return null;root=document.createElement('div');root.id='financePreview';root.setAttribute('aria-live','polite');section.querySelector('.np-panel')?.appendChild(root);if(!root.parentNode)return null;const style=document.createElement('style');style.textContent='.finance-preview-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-top:14px}.finance-preview-grid a{display:flex;flex-direction:column;gap:5px;padding:14px;border:1px solid #e8eaee;border-radius:16px;text-decoration:none;background:#fff;color:#17181b}.finance-preview-grid span{font-size:12px;font-weight:700}.finance-preview-grid strong{font-size:17px;color:#991b1b}.finance-preview-grid small{font-size:10px;color:#737b86}.finance-preview-empty{font-size:12px;color:#737b86}@media(max-width:700px){.finance-preview-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:420px){.finance-preview-grid{grid-template-columns:1fr}}';document.head.appendChild(style);return root}
function render(data){const root=ensureRoot();if(!root)return;const g=data.gold||{},p=data.petroleum||{},f=data.forex||{};const usd=(f.rates||[]).find(x=>x.currency==='USD'),kwd=(f.rates||[]).find(x=>x.currency==='KWD');root.innerHTML=`<div class="finance-preview-grid"><a href="${ROOT}gold-price/"><span>🪙 सुन</span><strong>रु. ${esc(g.gold?.price||'—')}</strong><small>${esc(g.updatedAt||g.date_ad||'')}</small></a><a href="${ROOT}petroleum-price/"><span>⛽ पेट्रोल</span><strong>रु. ${money(p.latest?.petrol)}/L</strong><small>${esc(p.latest?.effective_label||p.date_ad||'')}</small></a><a href="${ROOT}forex/"><span>💵 USD</span><strong>रु. ${money(usd?.sell)}</strong><small>बिक्री दर · ${esc(f.date_ad||'')}</small></a><a href="${ROOT}forex/"><span>🇰🇼 KWD</span><strong>रु. ${money(kwd?.sell)}</strong><small>बिक्री दर · ${esc(f.date_ad||'')}</small></a></div>`}
async function load(){const root=ensureRoot();if(!root)return;root.innerHTML='<p class="finance-preview-empty">वित्तीय डेटा लोड हुँदैछ…</p>';try{const [gold,petroleum,forex]=await Promise.all([get('feeds/gold_silver.json'),get('feeds/petroleum_prices.json'),get('feeds/forex.json')]);const data={gold,petroleum,forex,updatedAt:gold.updatedAt||forex.date_ad||petroleum.date_ad||''};window.NepaliPatroHome?.set('finance',data);render(data)}catch(error){console.error('[Nepali Patro finance]',error);window.NepaliPatroHome?.set('finance',{error});root.innerHTML='<p class="finance-preview-empty">वित्तीय डेटा अहिले उपलब्ध छैन। विस्तृत दरका लागि सम्बन्धित सेवा खोल्नुहोस्।</p>'}}
function init(){load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
