(()=>{'use strict';
const ROOT='https://apps.laxmannepal.com.np/Nepali-Patro/';
const MONTHS={1:'baishakh',2:'jestha',3:'ashar',4:'shrawan',5:'bhadra',6:'ashoj',7:'kartik',8:'mangsir',9:'poush',10:'magh',11:'fagun',12:'chaitra'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function get(url){const r=await fetch(url,{cache:'no-cache'});if(!r.ok)throw Error(`${url} HTTP ${r.status}`);return r.json()}
function today(){const p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kathmandu',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return{year:+p.year,month:+p.month,day:+p.day,iso:`${p.year}-${p.month}-${p.day}`}}
async function findDay(iso,adYear){for(const y of [adYear+57,adYear+56]){if(y<2040||y>2100)continue;try{const j=await get(`${ROOT}data/calendar/${y}.json`);const d=(j.days||[]).find(x=>x.ad?.date===iso);if(d)return d}catch(e){}}return null}
function icon(e){if(e.type==='birth')return'🎂';if(e.type==='death')return'🕯️';if(e.domain==='hindu-dharma')return'🕉️';if(e.domain==='nepal')return'🇳🇵';if(e.domain==='world')return'🌍';if(e.type==='heritage')return'🏛️';return'📜'}
function inject(){if(document.getElementById('homepage-history-style'))return;const s=document.createElement('style');s.id='homepage-history-style';s.textContent=`#historyPreview{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(260px,.75fr);gap:12px}.hp-history-feature,.hp-history-side{display:flex;gap:14px;border:1px solid var(--np-line,#e5e7eb);border-radius:18px;padding:18px;background:var(--np-card,#fff);text-decoration:none;color:var(--np-text,#172033);transition:transform .2s ease,box-shadow .2s ease}.hp-history-feature:hover,.hp-history-side:hover{transform:translateY(-2px);box-shadow:0 12px 30px rgba(15,23,42,.08)}.hp-history-icon{font-size:32px;flex:0 0 44px}.hp-history-body{min-width:0}.hp-history-kicker{font-size:11px;font-weight:800;color:#9a3412}.hp-history-title{margin:5px 0 7px;font-size:21px;line-height:1.3}.hp-history-summary{margin:0;color:#64748b;font-size:13px;line-height:1.7}.hp-history-side{align-items:center;padding:15px}.hp-history-side .hp-history-title{font-size:16px;margin:3px 0}.hp-history-meta{margin-top:10px;font-size:11px;color:#94a3b8}.hp-history-cta{display:inline-flex;align-items:center;gap:5px;margin-top:12px;font-size:12px;font-weight:800;color:#9a3412}.hp-history-empty{padding:20px;border:1px dashed #cbd5e1;border-radius:16px;color:#64748b;font-size:13px;background:var(--np-card,#fff);grid-column:1/-1}@media(max-width:700px){#historyPreview{grid-template-columns:1fr}.hp-history-feature{padding:15px}.hp-history-title{font-size:18px}.hp-history-side{padding:13px}}@media(prefers-color-scheme:dark){.hp-history-feature:hover,.hp-history-side:hover{box-shadow:0 12px 30px rgba(0,0,0,.2)}}`;document.head.appendChild(s)}
function render(hist,day){const root=document.getElementById('historyPreview');if(!root)return;const events=[...(hist?.events||[]),...(hist?.births||[]),...(hist?.deaths||[])].filter((e,i,a)=>i===a.findIndex(x=>[x.domain,x.type,x.year,x.title].join('|')===[e.domain,e.type,e.year,e.title].join('|')));const important=[...events].sort((a,b)=>(Number(b.importance)||0)-(Number(a.importance)||0));const first=important[0], second=important.slice(1,3);const festival=typeof day?.festival==='string'?day.festival:'';if(!first&&!festival){root.innerHTML='<div class="hp-history-empty">आजको इतिहासका लागि सामग्री उपलब्ध छैन। विस्तृत इतिहासमा हेर्नुहोस्।</div>';return}root.innerHTML=`${first?`<a class="hp-history-feature" href="${ROOT}itihas-aaja/"><div class="hp-history-icon">${icon(first)}</div><div class="hp-history-body"><div class="hp-history-kicker">आजकै दिन · ${esc(first.category||'इतिहास')}</div><h3 class="hp-history-title">${esc(first.title||'ऐतिहासिक घटना')}</h3><p class="hp-history-summary">${esc(first.summary||'आजकै दिनसँग सम्बन्धित उल्लेखनीय ऐतिहासिक विवरण।')}</p><div class="hp-history-meta">${first.year_bs?`वि.सं. ${esc(first.year_bs)}`:first.year?`वर्ष ${esc(first.year)}`:'ऐतिहासिक अभिलेख'}${first.confidence==='high'?' · ✓ प्रमाणित':''}</div><span class="hp-history-cta">पूरा इतिहास पढ्नुहोस् →</span></div></a>`:''}<div>${second.map(e=>`<a class="hp-history-side" href="${ROOT}itihas-aaja/"><div class="hp-history-icon">${icon(e)}</div><div class="hp-history-body"><div class="hp-history-kicker">${esc(e.category||'इतिहास')}</div><h3 class="hp-history-title">${esc(e.title||'ऐतिहासिक घटना')}</h3><div class="hp-history-meta">${e.year_bs?`वि.सं. ${esc(e.year_bs)}`:e.year?`वर्ष ${esc(e.year)}`:'आजकै दिन'}</div></div></a>`).join('')}${festival?`<a class="hp-history-side" href="${ROOT}parba/"><div class="hp-history-icon">🎉</div><div class="hp-history-body"><div class="hp-history-kicker">आजको संस्कृति</div><h3 class="hp-history-title">${esc(festival)}</h3><div class="hp-history-meta">आजको पर्व / परम्परा</div></div></a>`:''}</div>`}
async function load(){const root=document.getElementById('historyPreview');if(!root)return;inject();root.innerHTML='<div class="hp-history-empty">📜 आजको इतिहास लोड हुँदैछ…</div>';try{const t=today();const day=await findDay(t.iso,t.year);let hist=null;if(day?.bs?.month&&day?.bs?.day){hist=await get(`${ROOT}data/itihas/${MONTHS[+day.bs.month]}/${+day.bs.day}.json`).catch(()=>null)}render(hist,day);window.NepaliPatroHome?.set('history',{day,hist});window.NepaliPatroHome?.source('history',{status:hist?'ready':'stale',updatedAt:hist?.last_researched||new Date().toISOString(),error:null})}catch(error){console.error('[Nepali Patro history]',error);window.NepaliPatroHome?.source('history',{status:'error',error});root.innerHTML='<div class="hp-history-empty">📜 आजको इतिहास अहिले उपलब्ध छैन। विस्तृत इतिहासमा पुनः प्रयास गर्नुहोस्।</div>'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load();
})();
