(()=>{'use strict';
if(window.NepaliPatroHome?.version>=21)return;
const home=window.NepaliPatroHome||{};
const ready=()=>{document.documentElement.classList.add('np-v5-ready');};
const isHome=()=>location.pathname.replace(/\/+$/,'/')==='/Nepali-Patro/';
if(!isHome())return;
const add=(tag,attrs={})=>{const el=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));return el};
const progress=add('div',{class:'np-v5-progress','aria-hidden':'true'});document.body.appendChild(progress);
const updateProgress=()=>{const d=document.documentElement;const max=d.scrollHeight-d.clientHeight;progress.style.transform=`scaleX(${max>0?d.scrollTop/max:0})`};
addEventListener('scroll',updateProgress,{passive:true});addEventListener('resize',updateProgress,{passive:true});updateProgress();
const lazyImages=()=>document.querySelectorAll('img:not([loading])').forEach(img=>{if(!img.closest('.today-main-card'))img.loading='lazy';img.decoding='async'});
lazyImages();
const observe=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;entry.target.classList.add('ui-visible');observe.unobserve(entry.target)}),{rootMargin:'120px 0px',threshold:.01});
document.querySelectorAll('.np-section').forEach(el=>{el.classList.add('ui-reveal');observe.observe(el)});
const counts=[['parbaPreview','.festivals-card h3'],['rashifalPreview','.zodiac-card h3'],['newsPreview','.secondary-main-news h3']];
const countCards=()=>counts.forEach(([id,heading])=>{const box=document.getElementById(id),title=document.querySelector(heading);if(!box||!title||title.querySelector('.np-v5-section-count'))return;const count=box.querySelectorAll('a,article,li,.np-card,.news-item').length;if(count)title.insertAdjacentHTML('beforeend',`<span class="np-v5-section-count">${count}</span>`)});
const markOnline=()=>{document.documentElement.classList.toggle('np-v5-offline',!navigator.onLine)};addEventListener('online',markOnline);addEventListener('offline',markOnline);markOnline();
let deferredPrompt=null;const install=add('button',{class:'np-v5-install',type:'button','aria-label':'नेपाली पात्रो एप स्थापना गर्नुहोस्'});install.textContent='＋ एप स्थापना';document.body.appendChild(install);
addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;install.classList.add('is-visible')});install.addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;install.classList.remove('is-visible')});addEventListener('appinstalled',()=>install.classList.remove('is-visible'));
const registerSW=async()=>{if(!('serviceWorker'in navigator))return;try{const reg=await navigator.serviceWorker.register('sw.js',{scope:'./'});if(reg.waiting){reg.waiting.postMessage({type:'SKIP_WAITING'})}reg.addEventListener('updatefound',()=>{const worker=reg.installing;if(worker)worker.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)worker.postMessage({type:'SKIP_WAITING'})})})}catch(err){console.warn('[Nepali Patro] service worker unavailable',err)}};
const idle=window.requestIdleCallback||((fn)=>setTimeout(fn,800));idle(()=>{registerSW();lazyImages();countCards();ready()});
const enrich=()=>{document.querySelectorAll('.np-heading h2,.today-section-header h2').forEach(h=>h.setAttribute('tabindex','-1'))};addEventListener('DOMContentLoaded',enrich,{once:true});
window.NepaliPatroHomeV5={version:5,ready,registerSW,updateProgress};
})();
