(()=>{
'use strict';
const ROOT='https://apps.laxmannepal.com.np/Nepali-Patro/';
const MONTHS=['बैशाख','जेठ','असार','साउन','भदौ','असोज','कात्तिक','मंसिर','पुष','माघ','फागुन','चैत'];
const WEEK=['आइत','सोम','मंगल','बुध','बिही','शुक्र','शनि'];
const Z=[['♈','मेष'],['♉','वृष'],['♊','मिथुन'],['♋','कर्कट'],['♌','सिंह'],['♍','कन्या'],['♎','तुला'],['♏','वृश्चिक'],['♐','धनु'],['♑','मकर'],['♒','कुम्भ'],['♓','मीन']];
const nep=n=>String(n??'').replace(/\d/g,d=>'०१२३४५६७८९'[d]);
const ascii=n=>String(n??'').replace(/[०-९]/g,d=>'०१२३४५६७८९'.indexOf(d));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const numberNp=n=>{const s=ascii(n).replace(/,/g,'').trim(),v=Number(s);return Number.isFinite(v)?v.toLocaleString('ne-NP',{maximumFractionDigits:2}):String(n??'—')};
const todayAD=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kathmandu'}).format(new Date());
const findToday=days=>days.find(x=>x?.ad?.date===todayAD())||days[0];
function ensureForexSection(){if(document.getElementById('forexPreview'))return;const sections=[...document.querySelectorAll('main .np-section')];const anchor=sections.find(s=>s.querySelector('#newsPreview'))||sections.at(-1);if(!anchor)return;const sec=document.createElement('section');sec.className='np-section np-forex-section';sec.innerHTML=`<div class="np-heading"><div><small>नेपाल राष्ट्र बैंक</small><h2>आजको विदेशी मुद्रा दर</h2></div><a href="${ROOT}forex/">विस्तृत दर →</a></div><div class="np-panel np-forex-panel"><div id="forexPreview"><div class="np-finance-loading">विदेशी मुद्रा दर लोड हुँदैछ…</div></div></div>`;anchor.insertAdjacentElement('afterend',sec);const style=document.createElement('style');style.textContent='.np-forex-panel{overflow:hidden}.np-finance-date{font-size:12px;color:#68707d;margin-bottom:14px}.np-forex-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.np-forex-item{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:4px 9px;border:1px solid #e5e7eb;border-radius:14px;padding:12px;background:#fff}.np-forex-flag{font-size:25px;grid-row:span 2}.np-forex-item div{min-width:0}.np-forex-item b,.np-forex-item div small{display:block}.np-forex-item b{font-size:14px}.np-forex-item div small{font-size:10px;color:#68707d;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.np-forex-item strong{font-size:13px;text-align:right}.np-forex-label{font-size:9px;color:#68707d;text-align:right}.np-finance-action{display:block;text-align:center;margin:18px auto 0;max-width:290px}.np-finance-empty,.np-finance-loading{padding:18px;text-align:center;color:#68707d}@media(max-width:900px){.np-forex-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:520px){.np-forex-grid{grid-template-columns:1fr}.np-forex-item{grid-template-columns:auto 1fr auto}.np-forex-item strong{font-size:12px}}';document.head.appendChild(style)}
function injectCalendarResponsive(){if(document.getElementById('homepageCalendarResponsive'))return;const style=document.createElement('style');style.id='homepageCalendarResponsive';style.textContent=`#calendarPreview{width:100%;overflow:hidden}#calendarPreview .np-home-cal-grid{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:5px;width:100%}#calendarPreview .np-home-cal-cell{min-width:0;min-height:48px;text-decoration:none;color:inherit;border:1px solid #e5e7eb;background:#fff;border-radius:9px;padding:6px;display:block;box-sizing:border-box;overflow:hidden}#calendarPreview .np-home-cal-cell b{font-size:14px}#calendarPreview .np-home-cal-cell small{display:block;color:#68707d;font-size:8px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}#calendarPreview .np-home-cal-cell span{display:block;color:#b91c1c;font-size:8px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}@media(max-width:600px){#calendarPreview .np-home-cal-grid{gap:3px}#calendarPreview .np-home-cal-cell{min-height:42px;padding:4px;border-radius:7px}#calendarPreview .np-home-cal-cell b{font-size:12px}#calendarPreview .np-home-cal-cell small,#calendarPreview .np-home-cal-cell span{font-size:7px}#calendarPreview .np-home-cal-week{font-size:9px!important;padding:4px 1px!important}}@media(max-width:390px){#calendarPreview .np-home-cal-grid{gap:2px}#calendarPreview .np-home-cal-cell{min-height:39px;padding:3px}#calendarPreview .np-home-cal-cell b{font-size:11px}#calendarPreview .np-home-cal-cell small,#calendarPreview .np-home-cal-cell span{font-size:6px}}`;document.head.appendChild(style)}
function render(data){const days=data.days||[],x=findToday(days);if(!x)return;const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v??'डेटा उपलब्ध छैन'};set('todayBs',x.bs?.display||`${nep(x.bs?.year)} ${MONTHS[(x.bs?.month||1)-1]} ${nep(x.bs?.day)}`);set('todayAd',x.ad?.date||'');const p=document.getElementById('panchangaPreview');if(p){const rows=[['वार',x.weekday?.nepali],['तिथि',x.tithi?.name],['पक्ष',x.tithi?.paksha],['नक्षत्र',x.nakshatra?.name],['योग',x.yoga?.name],['करण',x.karana?.name],['सूर्योदय',x.sun?.sunrise],['सूर्यास्त',x.sun?.sunset],['राशि',x.rashi],['पर्व',x.festival]];p.innerHTML=rows.map(r=>`<div class="np-stat"><small>${esc(r[0])}</small><b>${esc(r[1]||'—')}</b></div>`).join('')}renderCalendar(data,x);renderParba(days,x);renderRashifal(x);renderNews();ensureForexSection();renderForex()}
function renderCalendar(data,x){const e=document.getElementById('calendarPreview');if(!e)return;injectCalendarResponsive();const y=x.bs.year,m=x.bs.month,first=data.days.find(d=>d.bs.year===y&&d.bs.month===m&&d.bs.day===1),count=data.lengths?.[m-1]||data.days.filter(d=>d.bs.year===y&&d.bs.month===m).length;let h=`<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px;gap:8px"><strong>${MONTHS[m-1]} ${nep(y)}</strong><span style="color:#68707d;font-size:11px;white-space:nowrap">${nep(count)} दिन</span></div><div class="np-home-cal-grid">${WEEK.map(v=>`<div class="np-home-cal-week" style="text-align:center;color:#68707d;font-size:10px;font-weight:800;padding:5px;min-width:0">${v}</div>`).join('')}`;for(let i=0;i<(first?.weekday?.index||0);i++)h+='<div></div>';for(let d=1;d<=count;d++){const q=data.days.find(a=>a.bs.year===y&&a.bs.month===m&&a.bs.day===d);if(!q)continue;const selected=q.ad.date===x.ad.date;h+=`<a class="np-home-cal-cell" href="${ROOT}calendar/?year=${y}&month=${m}&date=${q.ad.date}" style="border-color:${selected?'#fecaca':'#e5e7eb'};background:${selected?'#fff1f2':'#fff'}"><b>${nep(d)}</b><small>${q.ad.day||''}</small>${q.festival?`<span>${esc(q.festival)}</span>`:''}</a>`}e.innerHTML=h+'</div>'}
function renderParba(days,x){const e=document.getElementById('parbaPreview');if(!e)return;const rows=days.filter(d=>d.festival||d.holiday).filter(d=>d.ad.date>=x.ad.date).slice(0,3);e.innerHTML=rows.length?rows.map(d=>`<article class="np-event"><small>${esc(d.bs.display)}</small><b>${esc(d.festival||'बिदा')}</b><span>${d.holiday?'🇳🇵 बिदा':'🎉 पर्व'}</span></article>`).join(''):'<div class="np-event">आगामी पर्व डेटा उपलब्ध छैन।</div>'}
function renderRashifal(x){const e=document.getElementById('rashifalPreview');if(!e)return;e.innerHTML=Z.map(a=>`<a href="${ROOT}rashifal/?date=${encodeURIComponent(x.ad.date)}"><i>${a[0]}</i><b>${a[1]}</b><span>दैनिक राशिफल</span></a>`).join('')}
async function renderNews(){const e=document.getElementById('newsPreview');if(!e)return;try{const r=await fetch(`${ROOT}feeds/news.json?ts=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error('news');const j=await r.json();const items=Array.isArray(j)?j:(j.items||j.articles||j.news||[]);const a=items.filter(x=>x.title||x.headline).sort((u,v)=>new Date(v.publishedTime||v.published||0)-new Date(u.publishedTime||u.published||0)).slice(0,6);if(!a.length)throw Error('empty');const updated=j.updatedAt?new Date(j.updatedAt):null;e.innerHTML=`<a class="np-news-feature" href="${ROOT}news/"><small>मुख्य समाचार${updated&&!isNaN(updated)?` · ${updated.toLocaleString('ne-NP',{timeZone:'Asia/Kathmandu',hour:'2-digit',minute:'2-digit'})}`:''}</small><h3>${esc(a[0].title||a[0].headline)}</h3><p>${esc(a[0].description||a[0].summary||'पूरा समाचार पढ्नुहोस्।')}</p></a><div class="np-news-list">${a.slice(1).map(n=>`<a class="np-news-item" href="${ROOT}news/"><b>${esc(n.title||n.headline)}</b><p>${esc(n.sourceName||n.source||n.publisher||'समाचार स्रोत')}</p></a>`).join('')}</div>`}catch{e.innerHTML='<div class="np-news-feature"><small>समाचार</small><h3>समाचार डेटा अहिले उपलब्ध छैन।</h3><p>समाचार केन्द्र खोल्नुहोस्।</p></div>'}}
async function renderForex(){const e=document.getElementById('forexPreview');if(!e)return;try{const r=await fetch(`${ROOT}feeds/forex.json?ts=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error('forex');const j=await r.json();const rates=Array.isArray(j)?j:(j.rates||j.data||[]);const preferred=['USD','EUR','GBP','AED','SAR','KWD','INR'];const list=preferred.map(c=>rates.find(x=>String(x.currency||x.code||'').toUpperCase()===c)).filter(Boolean);if(!list.length)throw Error('empty');const date=`${j.date_bs||''}${j.date_ad?` · ${j.date_ad}`:''}`;e.innerHTML=`<div class="np-finance-date">${esc(date)}</div><div class="np-forex-grid">${list.map(x=>`<div class="np-forex-item"><span class="np-forex-flag">${esc(x.flag||'💱')}</span><div><b>${esc(x.currency||x.code)}</b><small>${esc(x.name||'')}</small></div><strong>रू. ${esc(numberNp(x.buy??x.buying??0))}</strong><small class="np-forex-label">खरिद</small><strong>रू. ${esc(numberNp(x.sell??x.selling??0))}</strong><small class="np-forex-label">बिक्री</small></div>`).join('')}</div><a class="np-primary np-finance-action" href="${ROOT}forex/">सबै विदेशी मुद्रा दर हेर्नुहोस् →</a>`}catch(err){console.error('[Nepali Patro forex]',err);e.innerHTML=`<div class="np-finance-empty">विदेशी मुद्रा दर अहिले उपलब्ध छैन। <a href="${ROOT}forex/">Forex खोल्नुहोस् →</a></div>`}}
function clock(){const e=document.getElementById('nepalClock');if(e)e.textContent='🇳🇵 नेपाल समय · '+new Intl.DateTimeFormat('ne-NP',{timeZone:'Asia/Kathmandu',weekday:'long',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:true}).format(new Date())}
async function boot(){try{const r=await fetch(`${ROOT}data/calendar/2083.json?v=homepage-20260823`,{cache:'no-store'});if(!r.ok)throw Error('calendar data unavailable');render(await r.json())}catch(err){console.error('[Nepali Patro homepage]',err);['todayBs','todayAd'].forEach(id=>{const e=document.getElementById(id);if(e)e.textContent='डेटा लोड हुन सकेन'});const p=document.getElementById('panchangaPreview');if(p)p.innerHTML='<div class="np-stat"><small>स्थिति</small><b>पात्रो डेटा उपलब्ध छैन</b></div>'}}
document.addEventListener('DOMContentLoaded',()=>{clock();setInterval(clock,1000);boot()});
})();