(()=>{
const months=['बैशाख','जेठ','असार','साउन','भदौ','असोज','कात्तिक','मंसिर','पुष','माघ','फागुन','चैत'];
const w=['आइत','सोम','मंगल','बुध','बिही','शुक्र','शनि'];
const z=[['♈','मेष'],['♉','वृष'],['♊','मिथुन'],['♋','कर्कट'],['♌','सिंह'],['♍','कन्या'],['♎','तुला'],['♏','वृश्चिक'],['♐','धनु'],['♑','मकर'],['♒','कुम्भ'],['♓','मीन']];
const ROOT='https://apps.laxmannepal.com.np/Nepali-Patro/';
const FEEDS_JS='https://raw.githubusercontent.com/LaxmanNepal/Nepali-Patro/main/feeds/feeds.js';
const NEWS_PROXY='https://api.allorigins.win/raw?url=';
const nep=n=>String(n).replace(/\d/g,d=>'०१२३४५६७८९'[d]);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const wait=()=>{if(typeof DATA==='undefined'||!DATA?.days?.length){setTimeout(wait,250);return}init()};
const eventNames=x=>{const values=[];if(Array.isArray(x?.events))values.push(...x.events);if(x?.festival)values.push(x.festival);return [...new Set(values.map(v=>String(v||'').trim()).filter(Boolean))]};
const eventText=x=>eventNames(x).join(' · ');
const hasEvent=x=>eventNames(x).length>0;
const todayIndex=()=>DATA.days.findIndex(x=>x.ad.date===new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kathmandu'}));
function init(){const days=DATA.days,x=days[todayIndex()]||days[0];document.getElementById('todayBs').textContent=x.bs.display;document.getElementById('todayAd').textContent=x.ad.date;const p=document.getElementById('panchangaPreview');if(p){const rows=[['वार',x.weekday?.nepali],['तिथि',x.tithi?.name],['नक्षत्र',x.nakshatra?.name],['योग',x.yoga?.name],['सूर्योदय',x.sun?.sunrise],['सूर्यास्त',x.sun?.sunset],['राशि',x.rashi],['पर्व',eventText(x)]];p.innerHTML=rows.map(r=>`<div class="np-stat"><small>${r[0]}</small><b>${esc(r[1]||'डेटा उपलब्ध छैन')}</b></div>`).join('')}renderCalendar(x);renderEvents(days,x);renderRashi(x);loadNews();renderFinance();if(localStorage.getItem('np-theme')==='dark')document.body.classList.add('dark')}
function renderCalendar(x){const e=document.getElementById('calendarPreview');if(!e)return;const y=x.bs.year,m=x.bs.month,first=DATA.days.find(d=>d.bs.year===y&&d.bs.month===m&&d.bs.day===1),count=DATA.lengths?.[m-1]||DATA.days.filter(d=>d.bs.year===y&&d.bs.month===m).length;let h=`<div style="display:flex;justify-content:space-between;margin-bottom:14px"><strong>${months[m-1]} ${nep(y)}</strong><span style="color:#68707d;font-size:11px">${nep(count)} दिन</span></div><div style="display:grid;grid-template-columns:repeat(7,1fr);gap:5px">${w.map(v=>`<div style="text-align:center;color:#68707d;font-size:10px;font-weight:800;padding:5px">${v}</div>`).join('')}`;for(let i=0;i<(first?.weekday?.index||0);i++)h+='<div></div>';for(let d=1;d<=count;d++){const day=DATA.days.find(a=>a.bs.year===y&&a.bs.month===m&&a.bs.day===d);if(!day)continue;const today=day.ad.date===x.ad.date;h+=`<a href="panchanga/?date=${day.ad.date}" style="min-height:48px;text-decoration:none;color:inherit;border:1px solid ${today?'#fecaca':'#e5e7eb'};background:${today?'#fff1f2':'#fff'};border-radius:9px;padding:6px;display:block"><b style="font-size:14px">${nep(d)}</b><small style="display:block;color:#68707d;font-size:8px">${day.ad.day}</small>${day.festival?`<span style="display:block;color:#b91c1c;font-size:8px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${esc(day.festival)}</span>`:''}</a>`}e.innerHTML=h+'</div>'}
function renderEvents(days,x){const e=document.getElementById('parbaPreview');if(!e)return;const rows=days.filter(d=>hasEvent(d)||d.holiday).filter(d=>d.ad.date>=x.ad.date).slice(0,3);e.innerHTML=rows.length?rows.map(d=>`<article class="np-event"><small>${esc(d.bs.display)}</small><b>${esc(eventText(d)||'बिदा')}</b><span>${d.holiday?'🇳🇵 बिदा':'🎉 पर्व'}</span></article>`).join(''):'<div class="np-event">आगामी पर्व डेटा उपलब्ध छैन।</div>'}
function renderRashi(x){const e=document.getElementById('rashifalPreview');if(!e)return;e.innerHTML=z.map(a=>`<a href="rashifal/?date=${x.ad.date}"><i>${a[0]}</i><b>${a[1]}</b><span>दैनिक राशिफल</span></a>`).join('')}
function categoryFor(key){return {all:'national',sports:'sports',finance:'business',tech:'technology',entertainment:'entertainment'}[key]||'national'}
function clean(s){return String(s??'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()}
function xmlText(node,selectors){for(const s of selectors){const el=node.querySelector(s);if(el?.textContent?.trim())return el.textContent.trim()}return ''}
function xmlAttr(node,selectors,attr){for(const s of selectors){const el=node.querySelector(s);const v=el?.getAttribute(attr);if(v)return v}return ''}
async function fetchText(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.text()}
async function fetchFeed(url){try{const r=await fetch(url,{cache:'no-store'});if(r.ok){const t=await r.text();if(/<\s*(rss|feed|rdf:RDF)/i.test(t))return t}}catch(e){}const r=await fetch(`${NEWS_PROXY}${encodeURIComponent(url)}`,{cache:'no-store'});if(!r.ok)throw new Error(`Feed unavailable: ${r.status}`);return r.text()}
function parseFeed(xml,url,category){const doc=new DOMParser().parseFromString(xml,'text/xml');if(doc.querySelector('parsererror'))throw new Error('Invalid XML');const sourceName=xmlText(doc,['channel > title','feed > title'])||new URL(url).hostname.replace(/^www\./,'');return [...doc.querySelectorAll('item,entry')].map(n=>{const title=xmlText(n,['title']);const description=xmlText(n,['description','summary','content']);const articleUrl=xmlAttr(n,['link[rel="alternate"]','link'],'href')||xmlText(n,['link','guid']);const imageUrl=xmlAttr(n,['media\\:content','media\\:thumbnail','enclosure'],'url')||xmlAttr(n,['image','thumbnail'],'href');const publishedTime=xmlText(n,['pubDate','published','updated']);return title&&articleUrl?{title:clean(title),description:clean(description),imageUrl,sourceName,publishedTime,articleUrl,category}:null}).filter(Boolean)}
async function loadNews(){const e=document.getElementById('newsPreview');if(!e)return;try{const text=await fetchText(`${FEEDS_JS}?v=${Date.now()}`);const config=new Function(`${text}\n;return MASTER_FEEDS;`)();if(!config||typeof config!=='object')throw new Error('Invalid feeds.js');const jobs=[];for(const [key,urls] of Object.entries(config)){for(const url of Array.isArray(urls)?urls:[])jobs.push({url,category:categoryFor(key)})}const results=await Promise.allSettled(jobs.map(async j=>parseFeed(await fetchFeed(j.url),j.url,j.category)));const seen=new Set();const items=results.flatMap(r=>r.status==='fulfilled'?r.value:[]).filter(n=>{const k=(n.articleUrl||n.title).toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>new Date(b.publishedTime)-new Date(a.publishedTime)).slice(0,5);if(!items.length)throw new Error('No news');e.innerHTML=`<a class="np-news-feature" href="news/"><small>मुख्य समाचार</small><h3>${esc(items[0].title)}</h3><p>${esc(items[0].description||'पूरा समाचार पढ्नुहोस्।')}</p></a><div class="np-news-list">${items.slice(1).map(n=>`<a class="np-news-item" href="${esc(n.articleUrl)}" target="_blank" rel="noopener"><b>${esc(n.title)}</b><p>${esc(n.sourceName)}</p></a>`).join('')}</div>`}catch(error){console.error('Homepage news:',error);e.innerHTML='<div class="np-news-feature"><small>समाचार</small><h3>समाचार डेटा अहिले उपलब्ध छैन।</h3><p>समाचार केन्द्र खोल्नुहोस्।</p></div>'}}
function financeMount(){if(!document.querySelector('link[data-finance-css]')){const l=document.createElement('link');l.rel='stylesheet';l.href=`${ROOT}css/finance.css?v=20260823-01`;l.dataset.financeCss='1';document.head.appendChild(l)}let f=document.getElementById('financePreview');if(!f){f=document.createElement('section');f.id='financePreview';f.className='np-section';const main=document.querySelector('main');const anchor=document.querySelector('#newsPreview')?.closest('.np-section');(anchor?anchor.nextElementSibling?.nextElementSibling:main?.lastElementChild)?.before(f)}return f}
async function renderFinance(){const root=financeMount();if(!root)return;try{const [gr,fr]=await Promise.all([fetch(`${ROOT}feeds/gold_silver.json?ts=${Date.now()}`,{cache:'no-store'}),fetch(`${ROOT}feeds/forex.json?ts=${Date.now()}`,{cache:'no-store'})]);const g=await gr.json(),fx=await fr.json();const rates=fx.rates||[],usd=rates.find(x=>x.currency==='USD'),eur=rates.find(x=>x.currency==='EUR');root.innerHTML=`<div class="np-heading"><div><small>बजार तथा वित्त</small><h2>आजको सुन, चाँदी र विदेशी मुद्रा</h2></div></div><div class="finance-showcase"><div class="finance-showcase-head"><div><h3>आजको सुन, चाँदीको दर</h3><small>${esc(g.date_bs||'')} ${g.date_ad?'- '+esc(g.date_ad):''}</small></div></div><div class="finance-rate-row"><div class="finance-icon">🥇</div><div><h3>${esc(g.gold?.type||'छापावाल')}</h3><small>${esc(g.gold?.unit||'प्रति तोला')}</small></div><div><div class="finance-price">रू. ${esc(g.gold?.price||'—')}</div><span class="finance-change">${g.gold?.trend==='down'?'📉':'📈'} (${esc(g.gold?.change||'—')})</span></div></div><div class="finance-rate-row"><div class="finance-icon">🥈</div><div><h3>${esc(g.silver?.type||'चाँदी')}</h3><small>${esc(g.silver?.unit||'प्रति तोला')}</small></div><div><div class="finance-price">रू. ${esc(g.silver?.price||'—')}</div><span class="finance-change">${g.silver?.trend==='down'?'📉':'📈'} (${esc(g.silver?.change||'—')})</span></div></div><a class="finance-more" href="${ROOT}gold-price/">थप मूल्य हेर्नुहोस्</a></div><div class="finance-showcase" style="margin-top:14px"><div class="finance-showcase-head"><div><h3>मुद्रा रूपान्तरण</h3><small>नेपाल राष्ट्र बैंकको स्थानीय दर</small></div><span class="finance-date">${esc(fx.date_bs||'')} ${fx.date_ad?'- '+esc(fx.date_ad):''}</span></div><div class="finance-rate-row"><div class="finance-icon">💱</div><div><h3>१ U.S. Dollar</h3><small>खरिद दर</small></div><div class="finance-price">रू. ${usd?usd.buy:'—'}</div></div><div class="finance-rate-row"><div class="finance-icon">💶</div><div><h3>१ Euro</h3><small>खरिद दर</small></div><div class="finance-price">रू. ${eur?eur.buy:'—'}</div></div><a class="finance-more" href="${ROOT}forex/">विदेशी मुद्रा दरहरू हेर्नुहोस्</a></div>`}catch(e){root.innerHTML='<div class="np-panel"><p>वित्तीय दरको स्थानीय डेटा अहिले उपलब्ध छैन।</p></div>';console.error(e)}}
window.addEventListener('load',wait);
})();