(()=>{'use strict';
const ROOT='https://apps.laxmannepal.com.np/Nepali-Patro/';
if(location.pathname.replace(/\/+$/,'/')!==ROOT)return;
const CACHE='np-home-cache-v2:';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const np=n=>String(n??'').replace(/\d/g,d=>'०१२३४५६७८९'[d]);
const money=n=>{const x=Number(n);return Number.isFinite(x)?x.toLocaleString('ne-NP',{maximumFractionDigits:2}):'—'};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function get(file,key=file){
  const url=ROOT+file;
  try{
    const ctl=new AbortController();const timer=setTimeout(()=>ctl.abort(),7000);
    const r=await fetch(url,{cache:'no-store',signal:ctl.signal});clearTimeout(timer);
    if(!r.ok)throw Error(`${r.status} ${file}`);
    const data=await r.json();
    try{localStorage.setItem(CACHE+key,JSON.stringify({at:Date.now(),data}))}catch{}
    return {data,fresh:true,at:Date.now()};
  }catch(error){
    try{const cached=JSON.parse(localStorage.getItem(CACHE+key)||'null');if(cached?.data)return {data:cached.data,fresh:false,at:cached.at,error:String(error)}}catch{}
    throw error;
  }
}
function css(){if(document.getElementById('daily-home-css'))return;const s=document.createElement('style');s.id='daily-home-css';s.textContent=`.daily-home-section{background:#fff;border:1px solid #e8eaee;border-radius:24px;padding:22px;margin:18px auto;box-shadow:0 8px 28px rgba(15,23,42,.05)}.daily-home-head{display:flex;justify-content:space-between;align-items:end;gap:12px;margin-bottom:16px}.daily-home-head small{display:block;color:#8a919b;font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.08em}.daily-home-head h2{margin:4px 0 0;font-size:21px}.daily-home-head a{color:#991b1b;text-decoration:none;font-size:12px;font-weight:800}.daily-cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.daily-card{border:1px solid #e8eaee;border-radius:18px;padding:15px;background:#fff}.daily-card .icon{font-size:22px}.daily-card b{display:block;margin-top:8px;font-size:13px}.daily-card strong{display:block;margin-top:5px;font-size:19px;color:#991b1b}.daily-card small{display:block;color:#737b86;font-size:10px;margin-top:5px}.daily-card a{display:block;margin-top:10px;color:#991b1b;font-size:10px;font-weight:800;text-decoration:none}.trend-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.trend-item{display:flex;gap:11px;align-items:flex-start;padding:13px;border:1px solid #e8eaee;border-radius:15px;text-decoration:none;color:#17181b}.trend-item .num{width:28px;height:28px;border-radius:9px;background:#fff1f2;color:#991b1b;display:grid;place-items:center;font-weight:800;flex:none}.trend-item strong{display:block;font-size:12px;line-height:1.5}.trend-item small{display:block;color:#8a919b;font-size:9px;margin-top:4px}.today-nepal-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.today-box{border:1px solid #e8eaee;border-radius:18px;padding:16px;background:#fff}.today-box h3{font-size:13px;margin:0 0 7px}.today-box p{font-size:11px;line-height:1.7;color:#5f6873;margin:0}.today-box a{display:inline-block;margin-top:10px;color:#991b1b;text-decoration:none;font-size:10px;font-weight:800}.daily-empty{padding:20px;text-align:center;color:#7b8490;font-size:12px}.daily-source{margin-top:10px;color:#8a919b;font-size:9px;text-align:right}@media(max-width:850px){.daily-cards{grid-template-columns:repeat(2,1fr)}.today-nepal-grid{grid-template-columns:1fr}.trend-list{grid-template-columns:1fr}}@media(max-width:520px){.daily-home-section{padding:16px;border-radius:18px}.daily-home-head h2{font-size:18px}.daily-cards{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function cleanup(){document.getElementById('financeHomeModules')?.remove();document.querySelectorAll('main .np-section').forEach(s=>{const h=s.querySelector('h2');if(h&&/प्रमुख समाचार|आजका प्रमुख समाचार/.test(h.textContent||''))s.remove()})}
function section(id,kicker,title,href){let s=document.getElementById(id);if(s)return s;const main=document.querySelector('main');if(!main)return null;s=document.createElement('section');s.id=id;s.className='daily-home-section';s.innerHTML=`<div class="daily-home-head"><div><small>${kicker}</small><h2>${title}</h2></div>${href?`<a href="${ROOT}${href}">सबै हेर्नुहोस् →</a>`:''}</div><div class="daily-home-body"></div>`;const anchor=[...main.querySelectorAll('.np-section')].find(x=>/आजको राशिफल/.test(x.textContent||''));(anchor||main.lastElementChild)?.insertAdjacentElement('afterend',s);return s}
function status(name,r){window.NepaliPatroHome?.source(name,{status:r.fresh?'fresh':'stale',updatedAt:r.at,error:r.error||null})}
let currentDay='';
async function loadCalendar(){
 try{
  const r=await get('data/calendar/2083.json','calendar-2083');const j=r.data;const days=Array.isArray(j.days)?j.days:[];
  const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kathmandu',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const y=+parts.find(x=>x.type==='year').value,m=+parts.find(x=>x.type==='month').value,d=+parts.find(x=>x.type==='day').value;currentDay=`${y}-${m}-${d}`;
  const x=days.find(v=>v?.ad?.year===y&&v?.ad?.month===m&&v?.ad?.day===d)||days[0];if(!x)throw Error('calendar-empty');
  const set=(q,v)=>{const e=document.querySelector(q);if(e)e.textContent=v??'—'};
  set('#todayBs',x.bs?.display);set('#todayAd',x.ad?.date?new Date(`${x.ad.date}T00:00:00Z`).toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'}):'—');
  const clock=()=>{const e=document.querySelector('#nepalClock');if(e)e.textContent=`🇳🇵 नेपाल समय · ${new Intl.DateTimeFormat('ne-NP',{timeZone:'Asia/Kathmandu',weekday:'long',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:true}).format(new Date())}`};clock();clearInterval(window.__npClock);window.__npClock=setInterval(clock,1000);
  const p=document.querySelector('#panchangaPreview');if(p)p.innerHTML=[['वार',x.weekday?.nepali],['तिथि',x.tithi?.name],['पक्ष',x.tithi?.paksha],['नक्षत्र',x.nakshatra?.name],['योग',x.yoga?.name],['करण',x.karana?.name],['सूर्योदय',x.sun?.sunrise],['सूर्यास्त',x.sun?.sunset]].map(([a,b])=>`<div class="np-stat"><span>${esc(a)}</span><strong>${esc(b||'—')}</strong></div>`).join('');
  const cal=document.querySelector('#calendarPreview');if(cal){const md=days.filter(v=>v.bs?.month===x.bs.month);cal.innerHTML=`<div class="daily-home-section" style="margin:0;padding:16px"><div class="daily-home-head"><div><small>${esc(x.bs.year)}</small><h2>${esc(x.bs.monthNepali||'आजको महिना')}</h2></div><span class="muted">${np(md.length)} दिन</span></div><div class="daily-cards">${md.map(v=>`<a class="daily-card" href="${ROOT}patro/" style="text-decoration:none;color:inherit"><b>${esc(v.bs?.display)}</b><strong>${np(v.ad?.day)} ${new Date(`${v.ad?.date}T00:00:00Z`).toLocaleDateString('en-US',{month:'short',timeZone:'UTC'})}</strong>${v.festival?`<small>🎉 ${esc(v.festival)}</small>`:''}</a>`).join('')}</div><div class="daily-source">पूर्वगणित पात्रो डेटा · ${esc(j.generatedAt||'')}</div></div>`}
  const parba=document.querySelector('#parbaPreview');if(parba){const events=[...(x.events||[])];parba.innerHTML=events.length?events.map(e=>`<article class="daily-card"><span class="icon">🎉</span><b>${esc(e)}</b><small>${x.holiday?'🇳🇵 बिदा':'आजको पर्व'}</small></article>`).join(''):`<div class="daily-empty">आज विशेष पर्व उपलब्ध छैन।</div>`}
  status('calendar',r);return x;
 }catch(e){document.querySelectorAll('#todayBs,#todayAd,#panchangaPreview,#calendarPreview,#parbaPreview').forEach(el=>{if(el&&!el.textContent.trim())el.innerHTML='<div class="daily-empty">पात्रो डेटा अहिले उपलब्ध छैन।</div>'});window.NepaliPatroHome?.source('calendar',{status:'error',updatedAt:null,error:String(e)});return null}
}
async function finance(){const s=section('daily-finance','Live Nepal Data','वित्तीय अपडेट','');const b=s?.querySelector('.daily-home-body');if(!b)return;try{const [g,p,f]=await Promise.all([get('feeds/gold_silver.json','gold'),get('feeds/petroleum_prices.json','petroleum'),get('feeds/forex.json','forex')]);const usd=(f.data.rates||[]).find(x=>x.currency==='USD'),kwd=(f.data.rates||[]).find(x=>x.currency==='KWD');b.innerHTML=`<div class="daily-cards"><div class="daily-card"><span class="icon">🪙</span><b>छापावाल सुन</b><strong>रु. ${esc(g.data.gold?.price||'—')}</strong><small>${esc(g.data.updatedAt||g.data.date_ad||'')}</small><a href="${ROOT}gold-price/">सुन तथा चाँदी →</a></div><div class="daily-card"><span class="icon">⛽</span><b>पेट्रोल</b><strong>रु. ${money(p.data.latest?.petrol)}/L</strong><small>NOC · ${esc(p.data.latest?.effective_label||p.data.date_ad||'')}</small><a href="${ROOT}petroleum-price/">पेट्रोलियम →</a></div><div class="daily-card"><span class="icon">💵</span><b>USD / NPR</b><strong>रु. ${money(usd?.sell)}</strong><small>बिक्री दर · ${esc(f.data.date_ad||'')}</small><a href="${ROOT}forex/">सबै मुद्रा →</a></div><div class="daily-card"><span class="icon">🇰🇼</span><b>KWD / NPR</b><strong>रु. ${money(kwd?.sell)}</strong><small>बिक्री दर · ${esc(f.data.date_ad||'')}</small><a href="${ROOT}forex/">KWD हेर्नुहोस् →</a></div></div>`;status('finance',{fresh:g.fresh&&p.fresh&&f.fresh,at:Math.min(g.at,p.at,f.at),error:[g.error,p.error,f.error].filter(Boolean).join('; ')||null})}catch(e){b.innerHTML='<div class="daily-empty">वित्तीय डेटा अहिले उपलब्ध छैन।</div>';window.NepaliPatroHome?.source('finance',{status:'error',updatedAt:null,error:String(e)})}}
async function trending(){const s=section('daily-trending','Daily Nepal','🔥 अहिले चर्चामा','news/');const b=s?.querySelector('.daily-home-body');if(!b)return;try{const r=await get('feeds/news.json','news');const j=r.data;const items=(Array.isArray(j)?j:(j.items||[])).filter(x=>x?.title&&x?.articleUrl).slice(0,6);b.innerHTML=items.length?`<div class="trend-list">${items.map((x,i)=>`<a class="trend-item" href="${esc(x.articleUrl)}" target="_blank" rel="noopener"><span class="num">${np(i+1)}</span><span><strong>${esc(x.title)}</strong><small>${esc(x.source||x.publisher||'नेपाल समाचार')}</small></span></a>`).join('')}</div>`:'<div class="daily-empty">आजका चर्चित विषयहरू उपलब्ध छैनन्।</div>';status('news',r)}catch(e){b.innerHTML='<div class="daily-empty">चर्चामा रहेका समाचार लोड हुन सकेनन्।</div>';window.NepaliPatroHome?.source('news',{status:'error',updatedAt:null,error:String(e)})}}
function todayNepal(){const s=section('daily-nepal','Daily Utility','🇳🇵 आज नेपालमा','');const b=s?.querySelector('.daily-home-body');if(!b)return;const parba=document.getElementById('parbaPreview'),rash=document.getElementById('rashifalPreview');b.innerHTML=`<div class="today-nepal-grid"><div class="today-box"><h3>🎉 आजका पर्व</h3><p>${esc(parba?.innerText?.replace(/\s+/g,' ').trim().slice(0,260)||'आजका पर्व तथा बिदा हेर्नुहोस्।')}</p><a href="${ROOT}parba/">सबै पर्व →</a></div><div class="today-box"><h3>📜 इतिहासमा आज</h3><p>आजकै दिन नेपालका इतिहास, संस्कृति र सम्पदासँग सम्बन्धित जानकारी पढ्नुहोस्।</p><a href="${ROOT}itihas-aaja/">इतिहास पढ्नुहोस् →</a></div><div class="today-box"><h3>♈ आजको राशिफल</h3><p>${rash?'१२ राशिका दैनिक राशिफल उपलब्ध छन्।':'दैनिक राशिफल हेर्नुहोस्।'}</p><a href="${ROOT}rashifal/">राशिफल →</a></div></div>`}
function scheduleMidnight(){clearTimeout(window.__npDayTimer);const now=new Date(),next=new Date(now);next.setHours(0,1,0,0);if(next<=now)next.setDate(next.getDate()+1);window.__npDayTimer=setTimeout(()=>{if(document.visibilityState!=='hidden')location.reload();else scheduleMidnight()},next-now)}
function run(){css();cleanup();loadCalendar().then(()=>{todayNepal();scheduleMidnight()});Promise.allSettled([finance(),trending()])}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else setTimeout(run,100);
})();