const NEWS_STATE={items:[],filtered:[],category:'all',source:'all',sort:'latest',query:'',visible:12,loadingMore:false};
const NEWS_CATEGORIES={all:'सबै',national:'राष्ट्रिय',politics:'राजनीति',business:'अर्थतन्त्र',sports:'खेलकुद',technology:'प्रविधि',entertainment:'मनोरञ्जन'};
const NEWS_BASE='https://apps.laxmannepal.com.np/Nepali-Patro/';
const NEWS_FEEDS_JS='https://raw.githubusercontent.com/LaxmanNepal/Nepali-Patro/main/feeds/feeds.js';
const NEWS_FALLBACK_IMAGE=`${NEWS_BASE}assets/news-placeholder.svg`;
const NEWS_PROXY='https://api.allorigins.win/raw?url=';
const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const cleanNewsText=s=>String(s??'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
const newsDate=s=>{const d=new Date(s);return Number.isNaN(d.getTime())?0:d.getTime()};
const npDigits=n=>String(n).replace(/\d/g,d=>'०१२३४५६७८९'[d]);
function relativeNepali(s){const t=new Date(s).getTime();if(!t)return '';let sec=Math.max(0,Math.floor((Date.now()-t)/1000));if(sec<60)return 'अहिले';let min=Math.floor(sec/60);if(min<60)return `${npDigits(min)} मिनेट अघि`;let hr=Math.floor(min/60);if(hr<24)return `${npDigits(hr)} घण्टा अघि`;let day=Math.floor(hr/24);if(day<7)return `${npDigits(day)} दिन अघि`;let week=Math.floor(day/7);if(week<5)return `${npDigits(week)} हप्ता अघि`;let month=Math.floor(day/30);if(month<12)return `${npDigits(month)} महिना अघि`;return `${npDigits(Math.floor(day/365))} वर्ष अघि`}
function initials(name){return escapeHTML(String(name||'समाचार').trim().slice(0,1))}
function sourceBadge(n){return `<span class="latest-news-source-fallback">${initials(n.sourceName)}</span>`}
function safeImage(url){return url?escapeHTML(url):NEWS_FALLBACK_IMAGE}
function loadLatestNewsStyles(){if(document.querySelector('link[data-latest-news-style]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href=`${NEWS_BASE}css/latest-news.css?v=20260824-02`;l.dataset.latestNewsStyle='1';document.head.appendChild(l)}
async function fetchText(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.text()}
async function fetchFeedXML(url){try{const r=await fetch(url,{cache:'no-store'});if(r.ok){const t=await r.text();if(/<\s*(rss|feed|rdf:RDF)/i.test(t))return t}}catch(e){}const r=await fetch(`${NEWS_PROXY}${encodeURIComponent(url)}`,{cache:'no-store'});if(!r.ok)throw new Error(`Feed unavailable: ${r.status}`);return r.text()}
function xmlText(node,selectors){for(const s of selectors){const el=node.querySelector(s);if(el?.textContent?.trim())return el.textContent.trim()}return ''}
function xmlAttr(node,selectors,attr){for(const s of selectors){const el=node.querySelector(s);const v=el?.getAttribute(attr);if(v)return v}return ''}
function parseRSS(xml,url,category){const doc=new DOMParser().parseFromString(xml,'text/xml');if(doc.querySelector('parsererror'))throw new Error('Invalid RSS/XML');const sourceName=xmlText(doc,['channel > title','feed > title'])||new URL(url).hostname.replace(/^www\./,'');return [...doc.querySelectorAll('item,entry')].map(n=>{const title=xmlText(n,['title']);const description=xmlText(n,['description','summary','content']);const articleUrl=xmlAttr(n,['link[rel="alternate"]','link'],'href')||xmlText(n,['link','guid']);const imageUrl=xmlAttr(n,['media\\:content','media\\:thumbnail','enclosure'],'url')||xmlAttr(n,['image','thumbnail'],'href');const publishedTime=xmlText(n,['pubDate','published','updated']);return title&&articleUrl?{title:cleanNewsText(title),description:cleanNewsText(description),imageUrl,sourceLogo:'',sourceName,publishedTime,articleUrl,category}:null}).filter(Boolean)}
function categoryFor(key){return {all:'national',sports:'sports',finance:'business',tech:'technology',entertainment:'entertainment'}[key]||'national'}
async function loadFeedConfig(){const text=await fetchText(`${NEWS_FEEDS_JS}?v=${Date.now()}`);const getFeeds=new Function(`${text}\n;return MASTER_FEEDS;`);const config=getFeeds();if(!config||typeof config!=='object')throw new Error('Invalid feeds.js configuration');return config}
async function loadNews(){try{const config=await loadFeedConfig();const jobs=[];for(const [key,urls] of Object.entries(config)){for(const url of (Array.isArray(urls)?urls:[]))jobs.push({url,category:categoryFor(key)})}const results=await Promise.allSettled(jobs.map(async j=>parseRSS(await fetchFeedXML(j.url),j.url,j.category)));const items=results.flatMap(r=>r.status==='fulfilled'?r.value:[]);const seen=new Set();NEWS_STATE.items=items.filter(n=>{const k=(n.articleUrl||n.title).toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>newsDate(b.publishedTime)-newsDate(a.publishedTime));if(!NEWS_STATE.items.length)throw new Error('No news returned from feeds.js sources')}catch(e){NEWS_STATE.items=[];console.error('News feed error:',e)}buildNewsSources();renderHomepageNews();renderNewsHub();setupInfiniteScroll()}
function buildNewsSources(){const box=document.querySelector('#newsSourceFilter');if(!box)return;const sources=[...new Set(NEWS_STATE.items.map(n=>n.sourceName).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ne'));box.innerHTML='<option value="all">सबै स्रोत</option>'+sources.map(s=>`<option value="${escapeHTML(s)}">${escapeHTML(s)}</option>`).join('')}
function filterNews(){let a=NEWS_STATE.items.filter(n=>NEWS_STATE.category==='all'||n.category===NEWS_STATE.category).filter(n=>NEWS_STATE.source==='all'||n.sourceName===NEWS_STATE.source);if(NEWS_STATE.query){const q=NEWS_STATE.query.toLocaleLowerCase('ne');a=a.filter(n=>`${n.title} ${n.description} ${n.sourceName}`.toLocaleLowerCase('ne').includes(q))}a.sort((x,y)=>NEWS_STATE.sort==='oldest'?newsDate(x.publishedTime)-newsDate(y.publishedTime):newsDate(y.publishedTime)-newsDate(x.publishedTime));NEWS_STATE.filtered=a;return a}
function newsCard(n,featured=false){return `<article class="news-card ${featured?'featured':''}"><a class="news-card-link" href="${escapeHTML(n.articleUrl)}" target="_blank" rel="noopener noreferrer"><img class="news-card-image" src="${safeImage(n.imageUrl)}" loading="lazy" alt="${escapeHTML(n.title)}" onerror="this.onerror=null;this.src='${NEWS_FALLBACK_IMAGE}'"><div class="news-card-body"><h3>${escapeHTML(n.title)}</h3>${n.description?`<p>${escapeHTML(n.description)}</p>`:''}<div class="news-meta"><span class="news-source">${sourceBadge(n)}<b>${escapeHTML(n.sourceName)}</b></span><time datetime="${escapeHTML(n.publishedTime)}">${relativeNepali(n.publishedTime)}</time></div></div></a></article>`}
function renderHomepageNews(){const root=document.querySelector('#newsPreview');if(!root)return;const latest=NEWS_STATE.items.slice(0,6);if(!latest.length){root.innerHTML='<div class="latest-news-empty"><strong>ताजा समाचार</strong><br>feeds.js का RSS स्रोतबाट अहिले समाचार प्राप्त भएन।</div>';return}const [first,...rest]=latest;root.innerHTML=`<div class="latest-news-card" aria-label="ताजा समाचार"><div class="latest-news-heading"><div><small>नेपालका नयाँ अपडेट</small><h2>ताजा समाचार</h2></div><span>${npDigits(latest.length)} नयाँ</span></div><article class="latest-news-featured">${newsCard(first,true)}</article><div class="latest-news-list">${rest.map(n=>newsCard(n)).join('')}</div><a class="latest-news-more" href="${NEWS_BASE}news/">थप समाचार पढ्नुहोस् <span>→</span></a></div>`}
function renderNewsHub(){const root=document.querySelector('#newsGrid'),count=document.querySelector('#newsCount');if(!root)return;const a=filterNews();if(count)count.textContent=a.length?`${a.length.toLocaleString('ne-NP')} समाचार`:'समाचार उपलब्ध छैन';const shown=a.slice(0,NEWS_STATE.visible);root.innerHTML=shown.length?shown.map(n=>newsCard(n)).join(''):'<div class="news-empty">तपाईंको खोज वा फिल्टरसँग मिल्ने समाचार भेटिएन।</div>';const more=document.querySelector('#loadMoreNews');if(more)more.hidden=NEWS_STATE.visible>=a.length;const sentinel=document.querySelector('#newsInfiniteSentinel');if(sentinel)sentinel.setAttribute('aria-hidden',NEWS_STATE.visible>=a.length?'true':'false')}
function loadMoreNews(){if(NEWS_STATE.loadingMore)return;const a=filterNews();if(NEWS_STATE.visible>=a.length)return;NEWS_STATE.loadingMore=true;NEWS_STATE.visible=Math.min(NEWS_STATE.visible+12,a.length);renderNewsHub();requestAnimationFrame(()=>{NEWS_STATE.loadingMore=false})}
function setupInfiniteScroll(){const root=document.querySelector('#newsGrid');if(!root||!('IntersectionObserver' in window)||document.querySelector('#newsInfiniteSentinel'))return;const s=document.createElement('div');s.id='newsInfiniteSentinel';s.style.cssText='height:1px;width:100%;grid-column:1/-1';root.after(s);new IntersectionObserver(e=>{if(e[0]?.isIntersecting)loadMoreNews()},{rootMargin:'700px 0px'}).observe(s)}
function initNews(){loadLatestNewsStyles();document.querySelectorAll('[data-news-cat]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-news-cat]').forEach(x=>x.classList.remove('active'));b.classList.add('active');NEWS_STATE.category=b.dataset.newsCat;NEWS_STATE.visible=12;const cat=document.querySelector('#newsCategoryFilter');if(cat)cat.value=NEWS_STATE.category;renderNewsHub()});const cat=document.querySelector('#newsCategoryFilter');if(cat){cat.innerHTML=Object.entries(NEWS_CATEGORIES).map(([k,v])=>`<option value="${k}">${v}</option>`).join('');cat.onchange=()=>{NEWS_STATE.category=cat.value;NEWS_STATE.visible=12;renderNewsHub()}}const src=document.querySelector('#newsSourceFilter');if(src)src.onchange=()=>{NEWS_STATE.source=src.value;NEWS_STATE.visible=12;renderNewsHub()};const sort=document.querySelector('#newsSort');if(sort)sort.onchange=()=>{NEWS_STATE.sort=sort.value;renderNewsHub()};const search=document.querySelector('#newsSearch');if(search)search.oninput=()=>{NEWS_STATE.query=search.value.trim();NEWS_STATE.visible=12;renderNewsHub()};const more=document.querySelector('#loadMoreNews');if(more)more.onclick=loadMoreNews;loadNews()}
window.addEventListener('DOMContentLoaded',initNews);