const NEWS_REFRESH_MS=180000;const NEWS_STATE={items:[],filtered:[],category:'all',source:'all',sort:'latest',query:'',visible:12,loadingMore:false,updatedAt:'',failedFeeds:0};
const NEWS_CATEGORIES={all:'सबै',national:'राष्ट्रिय',politics:'राजनीति',business:'अर्थतन्त्र',sports:'खेलकुद',technology:'प्रविधि',entertainment:'मनोरञ्जन'};
const NEWS_BASE='https://apps.laxmannepal.com.np/Nepali-Patro/';const NEWS_LOCAL_FEED=`${NEWS_BASE}feeds/news.json`;const NEWS_FALLBACK_IMAGE=`${NEWS_BASE}assets/news-placeholder.svg`;
const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const cleanNewsText=s=>String(s??'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();const newsDate=s=>{const d=new Date(s);return Number.isNaN(d.getTime())?0:d.getTime()};const npDigits=n=>String(n).replace(/\d/g,d=>'०१२३४५६७८९'[d]);
function relativeNepali(s){const t=new Date(s).getTime();if(!t)return '';let sec=Math.max(0,Math.floor((Date.now()-t)/1000));if(sec<60)return 'अहिले';let min=Math.floor(sec/60);if(min<60)return `${npDigits(min)} मिनेट अघि`;let hr=Math.floor(min/60);if(hr<24)return `${npDigits(hr)} घण्टा अघि`;let day=Math.floor(hr/24);if(day<7)return `${npDigits(day)} दिन अघि`;let week=Math.floor(day/7);if(week<5)return `${npDigits(week)} हप्ता अघि`;let month=Math.floor(day/30);if(month<12)return `${npDigits(month)} महिना अघि`;return `${npDigits(Math.floor(day/365))} वर्ष अघि`}
function initials(name){return escapeHTML(String(name||'समाचार').trim().slice(0,1))}function sourceBadge(n){return n.sourceLogo?`<img src="${escapeHTML(n.sourceLogo)}" alt="" loading="lazy" onerror="this.replaceWith(Object.assign(document.createElement('span'),{className:'latest-news-source-fallback',textContent:'${initials(n.sourceName)}'}))">`:`<span class="latest-news-source-fallback">${initials(n.sourceName)}</span>`}function safeImage(url){return url?escapeHTML(url):NEWS_FALLBACK_IMAGE}
function loadLatestNewsStyles(){if(document.querySelector('link[data-latest-news-style]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href=`${NEWS_BASE}css/latest-news.css?v=20260824-04`;l.dataset.latestNewsStyle='1';document.head.appendChild(l)}
async function fetchLocalNews(){const r=await fetch(NEWS_LOCAL_FEED,{cache:'no-cache'});if(!r.ok)throw new Error(`news.json HTTP ${r.status}`);const payload=await r.json();const items=Array.isArray(payload)?payload:(Array.isArray(payload.items)?payload.items:payload.articles);if(!Array.isArray(items))throw new Error('Invalid feeds/news.json structure');NEWS_STATE.updatedAt=payload.updatedAt||'';NEWS_STATE.failedFeeds=Number(payload.failedFeeds??payload.failedSources??0);const seen=new Set();NEWS_STATE.items=items.map(n=>({...n,title:cleanNewsText(n.title),description:cleanNewsText(n.description||n.summary),sourceName:n.sourceName||n.source||'समाचार',articleUrl:n.articleUrl||n.link})).filter(n=>n.title&&n.articleUrl).filter(n=>{const k=String(n.articleUrl).toLowerCase()||n.title.toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>newsDate(b.publishedTime)-newsDate(a.publishedTime));if(!NEWS_STATE.items.length)throw new Error('feeds/news.json contains no articles')}
function liveStatus(){const root=document.querySelector('#newsLiveStatus');if(!root)return;const d=NEWS_STATE.updatedAt?new Date(NEWS_STATE.updatedAt):null;const age=d&&!Number.isNaN(d.getTime())?Math.max(0,Math.floor((Date.now()-d.getTime())/60000)):null;root.innerHTML=`<span class="news-live-dot"></span><strong>फिड सक्रिय</strong><span>${age===null?'डेटा तयार हुँदैछ':age<1?'अहिले अपडेट गरिएको':`${npDigits(age)} मिनेट अघि अपडेट`}</span>${NEWS_STATE.failedFeeds?`<span>· ${npDigits(NEWS_STATE.failedFeeds)} स्रोत असफल</span>`:''}<button id="refreshNews" type="button" aria-label="समाचार ताजा गर्नुहोस्">↻ ताजा</button>`;const btn=document.querySelector('#refreshNews');if(btn)btn.onclick=()=>refreshNews(true)}
function updateStats(){const count=document.querySelector('#newsStatCount'),sources=document.querySelector('#newsStatSources'),fresh=document.querySelector('#newsStatFresh');if(count)count.textContent=NEWS_STATE.items.length.toLocaleString('ne-NP');if(sources)sources.textContent=new Set(NEWS_STATE.items.map(n=>n.sourceName).filter(Boolean)).size.toLocaleString('ne-NP');const recent=NEWS_STATE.items.filter(n=>Date.now()-newsDate(n.publishedTime)<6*60*60*1000).length;if(fresh)fresh.textContent=recent.toLocaleString('ne-NP')}
function buildNewsSources(){const box=document.querySelector('#newsSourceFilter');if(!box)return;const sources=[...new Set(NEWS_STATE.items.map(n=>n.sourceName).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ne'));box.innerHTML='<option value="all">सबै स्रोत</option>'+sources.map(s=>`<option value="${escapeHTML(s)}">${escapeHTML(s)}</option>`).join('');box.value=NEWS_STATE.source}
function filterNews(){let a=NEWS_STATE.items.filter(n=>NEWS_STATE.category==='all'||n.category===NEWS_STATE.category).filter(n=>NEWS_STATE.source==='all'||n.sourceName===NEWS_STATE.source);if(NEWS_STATE.query){const q=NEWS_STATE.query.toLocaleLowerCase('ne');a=a.filter(n=>`${n.title} ${n.description} ${n.sourceName}`.toLocaleLowerCase('ne').includes(q))}a.sort((x,y)=>NEWS_STATE.sort==='oldest'?newsDate(x.publishedTime)-newsDate(y.publishedTime):newsDate(y.publishedTime)-newsDate(x.publishedTime));NEWS_STATE.filtered=a;return a}
function newsCard(n,featured=false){return `<article class="news-card ${featured?'news-featured':''}"><a class="news-card-link" href="${escapeHTML(n.articleUrl)}" target="_blank" rel="noopener noreferrer"><img class="news-card-image" src="${safeImage(n.imageUrl)}" loading="lazy" alt="${escapeHTML(n.title)}" onerror="this.onerror=null;this.src='${NEWS_FALLBACK_IMAGE}'"><div class="news-card-body"><h3>${escapeHTML(n.title)}</h3>${n.description?`<p>${escapeHTML(n.description)}</p>`:''}<div class="news-meta"><span class="news-source">${sourceBadge(n)}<b>${escapeHTML(n.sourceName)}</b></span><time datetime="${escapeHTML(n.publishedTime)}">${relativeNepali(n.publishedTime)}</time></div></div></a></article>`}
function renderFeature(){const root=document.querySelector('#newsFeatureArea');if(!root)return;const a=filterNews();if(!a.length){root.innerHTML='';return}const [first,...side]=a.slice(0,4);root.innerHTML=`<div class="news-section-head"><h2>आजका मुख्य समाचार</h2><span>${relativeNepali(first.publishedTime)} मा नयाँ</span></div><div class="news-feature-grid"><div>${newsCard(first,true)}</div><div class="side-stories">${side.map(n=>newsCard(n)).join('')}</div></div>`}
function renderHomepageNews(){const root=document.querySelector('#newsPreview');if(!root)return;const latest=NEWS_STATE.items.slice(0,6);if(!latest.length){root.innerHTML='<div class="latest-news-empty"><strong>ताजा समाचार</strong><br>स्थानीय news feed मा अहिले समाचार छैन।</div>';return}const [first,...rest]=latest;root.innerHTML=`<div class="latest-news-card" aria-label="ताजा समाचार"><div class="latest-news-heading"><div><small>स्वचालित समाचार फिड</small><h2>ताजा समाचार</h2></div><span>${npDigits(latest.length)} नयाँ</span></div><article class="latest-news-featured">${newsCard(first,true)}</article><div class="latest-news-list">${rest.map(n=>newsCard(n)).join('')}</div><a class="latest-news-more" href="${NEWS_BASE}news/">थप समाचार पढ्नुहोस् <span>→</span></a></div>`}
function renderNewsHub(){const root=document.querySelector('#newsGrid'),count=document.querySelector('#newsCount');if(!root)return;const a=filterNews();if(count)count.textContent=a.length?`${a.length.toLocaleString('ne-NP')} समाचार`:'समाचार उपलब्ध छैन';const shown=a.slice(4,4+NEWS_STATE.visible);root.innerHTML=shown.length?shown.map(n=>newsCard(n)).join(''):'<div class="news-empty">तपाईंको खोज वा फिल्टरसँग मिल्ने समाचार भेटिएन।</div>';const more=document.querySelector('#loadMoreNews');if(more)more.hidden=4+NEWS_STATE.visible>=a.length;const status=document.querySelector('#newsInfiniteStatus');if(status)status.textContent=4+NEWS_STATE.visible<a.length?'थप समाचारका लागि तल स्क्रोल गर्नुहोस्':'सबै उपलब्ध समाचार देखाइयो';}
function loadMoreNews(){if(NEWS_STATE.loadingMore)return;const a=filterNews();if(4+NEWS_STATE.visible>=a.length)return;NEWS_STATE.loadingMore=true;NEWS_STATE.visible=Math.min(NEWS_STATE.visible+12,a.length-4);renderNewsHub();requestAnimationFrame(()=>NEWS_STATE.loadingMore=false)}
function setupInfiniteScroll(){const root=document.querySelector('#newsGrid');if(!root||!('IntersectionObserver' in window)||document.querySelector('#newsInfiniteSentinel'))return;const s=document.createElement('div');s.id='newsInfiniteSentinel';s.style.cssText='height:1px;width:100%;grid-column:1/-1';root.after(s);new IntersectionObserver(e=>{if(e[0]?.isIntersecting)loadMoreNews()},{rootMargin:'700px 0px'}).observe(s)}
async function refreshNews(force=false){const old=NEWS_STATE.items.map(x=>x.articleUrl).join('|');try{window.NepaliPatroHome?.source('news',{status:'loading',error:null});await fetchLocalNews();const changed=old!==NEWS_STATE.items.map(x=>x.articleUrl).join('|');NEWS_STATE.visible=12;buildNewsSources();updateStats();renderFeature();renderHomepageNews();renderNewsHub();liveStatus();window.NepaliPatroHome?.set('news',{items:NEWS_STATE.items,updatedAt:NEWS_STATE.updatedAt,failedFeeds:NEWS_STATE.failedFeeds});window.NepaliPatroHome?.source('news',{status:'ready',updatedAt:NEWS_STATE.updatedAt||new Date().toISOString(),error:null});if(force){const status=document.querySelector('#newsRefreshMessage');if(status)status.textContent=changed?'ताजा समाचार अपडेट भयो।':'नयाँ समाचार भेटिएन।'}}catch(e){console.error('Local news feed error:',e);if(NEWS_STATE.items.length){window.NepaliPatroHome?.source('news',{status:'stale',updatedAt:NEWS_STATE.updatedAt||null,error:e});renderHomepageNews();renderFeature();renderNewsHub();liveStatus();}else{window.NepaliPatroHome?.set('news',{items:[],updatedAt:NEWS_STATE.updatedAt,failedFeeds:NEWS_STATE.failedFeeds,error:e});window.NepaliPatroHome?.source('news',{status:'error',error:e})}const status=document.querySelector('#newsRefreshMessage');if(status)status.textContent='समाचार फिड अहिले उपलब्ध भएन। सुरक्षित गरिएको समाचार देखाइएको छ।'}}
function initNews(){loadLatestNewsStyles();const top=document.querySelector('#refreshTop');if(top)top.onclick=()=>refreshNews(true);document.querySelectorAll('[data-news-cat]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-news-cat]').forEach(x=>x.classList.remove('active'));b.classList.add('active');NEWS_STATE.category=b.dataset.newsCat;NEWS_STATE.visible=12;renderFeature();renderNewsHub()});const cat=document.querySelector('#newsCategoryFilter');if(cat){cat.innerHTML=Object.entries(NEWS_CATEGORIES).map(([k,v])=>`<option value="${k}">${v}</option>`).join('');cat.onchange=()=>{NEWS_STATE.category=cat.value;NEWS_STATE.visible=12;renderFeature();renderNewsHub()}}const src=document.querySelector('#newsSourceFilter');if(src)src.onchange=()=>{NEWS_STATE.source=src.value;NEWS_STATE.visible=12;renderFeature();renderNewsHub()};const sort=document.querySelector('#newsSort');if(sort)sort.onchange=()=>{NEWS_STATE.sort=sort.value;renderFeature();renderNewsHub()};const search=document.querySelector('#newsSearch');if(search)search.oninput=()=>{NEWS_STATE.query=search.value.trim();NEWS_STATE.visible=12;renderFeature();renderNewsHub()};const more=document.querySelector('#loadMoreNews');if(more)more.onclick=loadMoreNews;refreshNews(false);setupInfiniteScroll();setInterval(()=>refreshNews(false),NEWS_REFRESH_MS)}
window.addEventListener('DOMContentLoaded',initNews);
(()=>{const s=document.createElement('script');s.src='https://apps.laxmannepal.com.np/Nepali-Patro/js/news-enhancements.js?v=20260824-02';s.defer=true;document.head.appendChild(s)})();
