(()=>{
const BASE='https://apps.laxmannepal.com.np/Nepali-Patro/';
const signs=[['♈','मेष','Aries'],['♉','वृष','Taurus'],['♊','मिथुन','Gemini'],['♋','कर्कट','Cancer'],['♌','सिंह','Leo'],['♍','कन्या','Virgo'],['♎','तुला','Libra'],['♏','वृश्चिक','Scorpio'],['♐','धनु','Sagittarius'],['♑','मकर','Capricorn'],['♒','कुम्भ','Aquarius'],['♓','मीन','Pisces']];
const shift=(d,n)=>{const x=new Date(`${d}T00:00:00Z`);x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10)};
const monday=d=>{const x=new Date(`${d}T00:00:00Z`);const day=x.getUTCDay();x.setUTCDate(x.getUTCDate()-(day===0?6:day-1));return x.toISOString().slice(0,10)};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kathmandu',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const loadDaily=async date=>{const r=await fetch(`${BASE}data/rashifal/${date}.json?${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(`यो मितिको दैनिक राशिफल अझै प्रकाशित भएको छैन (${date})`);return r.json()};
const loadWeekly=async week=>{const r=await fetch(`${BASE}data/rashifal-weekly/${week}.json?${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(`यो हप्ताको साप्ताहिक राशिफल अझै प्रकाशित भएको छैन (${week})`);return r.json()};
const dailyCard=(d,i)=>{const s=signs[i],f=d.signs[i];return `<article class="rashi-card"><div class="rashi-head"><span>${s[0]}</span><div><h2>${f.nepali}</h2><small>${f.english}</small></div></div><p class="forecast-main">${esc(f.prediction)}</p><div class="lucky"><span>📅 ${esc(d.bsDate)}</span><span>📚 दैनिक राशिफल</span></div></article>`};
const weeklyCard=(d,i)=>{const s=signs[i],f=d.signs[i];return `<article class="week-card"><div class="rashi-head"><span>${s[0]}</span><div><h2>${f.nepali}</h2><small>${f.english} · साप्ताहिक</small></div></div><p class="forecast-main">${esc(f.prediction)}</p><div class="lucky"><span>📅 ${esc(d.weekLabel||`${d.weekStart} — ${d.weekEnd}`)}</span><span>📚 साप्ताहिक राशिफल</span></div></article>`};
const setActive=(weekly)=>{document.querySelector('#daily').hidden=weekly;document.querySelector('#weekly').hidden=!weekly;document.querySelector('#dailyTab').classList.toggle('active',!weekly);document.querySelector('#weeklyTab').classList.toggle('active',weekly);document.querySelector('#selectedDate').hidden=weekly;document.querySelector('#todayBtn').hidden=weekly;document.querySelector('#prev').textContent=weekly?'← अघिल्लो हप्ता':'← अघिल्लो दिन';document.querySelector('#next').textContent=weekly?'अर्को हप्ता →':'अर्को दिन →'};
async function renderDaily(date){const data=await loadDaily(date);document.querySelector('#dateTitle').textContent=`दैनिक राशिफल · ${data.bsDate}`;document.querySelector('#dateSub').textContent=`${date} · ${data.weekday||''} · स्रोत: ${data.source||'स्रोत'}`;document.querySelector('#selectedDate').value=date;document.querySelector('#daily').innerHTML=data.signs.map((_,i)=>dailyCard(data,i)).join('');document.querySelector('#prev').onclick=()=>location.href=`${location.pathname}?view=daily&date=${shift(date,-1)}`;document.querySelector('#next').onclick=()=>location.href=`${location.pathname}?view=daily&date=${shift(date,1)}`;document.querySelector('#todayBtn').onclick=()=>location.href=`${location.pathname}?view=daily&date=${today()}`;document.querySelector('#selectedDate').onchange=e=>location.href=`${location.pathname}?view=daily&date=${e.target.value}`;setActive(false)};
async function renderWeekly(week){const data=await loadWeekly(week);document.querySelector('#dateTitle').textContent=`साप्ताहिक राशिफल · ${data.weekLabel||''}`;document.querySelector('#dateSub').textContent=`${data.weekStart} — ${data.weekEnd} · स्रोत: ${data.source||'स्रोत'}`;document.querySelector('#weekly').innerHTML=data.signs.map((_,i)=>weeklyCard(data,i)).join('');document.querySelector('#prev').onclick=()=>location.href=`${location.pathname}?view=weekly&week=${shift(week,-7)}`;document.querySelector('#next').onclick=()=>location.href=`${location.pathname}?view=weekly&week=${shift(week,7)}`;setActive(true)};
async function init(){const error=document.querySelector('#rashifalError');error.hidden=true;const params=new URLSearchParams(location.search);const weekly=params.get('view')==='weekly';try{if(weekly){await renderWeekly(params.get('week')||monday(today()))}else{await renderDaily(params.get('date')||today())}}catch(e){error.textContent=e.message;error.hidden=false;setActive(weekly)}}
document.addEventListener('DOMContentLoaded',()=>{document.querySelector('#dailyTab').onclick=()=>location.href=`${location.pathname}?view=daily&date=${today()}`;document.querySelector('#weeklyTab').onclick=()=>location.href=`${location.pathname}?view=weekly&week=${monday(today())}`;init()});
})();