(()=>{
const BASE='https://apps.laxmannepal.com.np/Nepali-Patro/';
const RASHI_PATH=`${BASE}rashifal/`;
const signs=[['♈','मेष','Aries'],['♉','वृष','Taurus'],['♊','मिथुन','Gemini'],['♋','कर्कट','Cancer'],['♌','सिंह','Leo'],['♍','कन्या','Virgo'],['♎','तुला','Libra'],['♏','वृश्चिक','Scorpio'],['♐','धनु','Sagittarius'],['♑','मकर','Capricorn'],['♒','कुम्भ','Aquarius'],['♓','मीन','Pisces']];
const shift=(d,n)=>{const x=new Date(`${d}T00:00:00Z`);x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10)};
const monday=d=>{const x=new Date(`${d}T00:00:00Z`);const day=x.getUTCDay();x.setUTCDate(x.getUTCDate()-(day===0?6:day-1));return x.toISOString().slice(0,10)};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kathmandu',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const signById=id=>signs.findIndex(s=>s[2].toLowerCase()===id);
const validRashi=id=>signById(id)>=0;
const setMeta=(selector,attr,value)=>{const el=document.querySelector(selector);if(el)el.setAttribute(attr,value)};
const updateSEO=(selected,data)=>{
 const i=signById(selected), baseTitle='आजको राशिफल — १२ राशिको दैनिक राशिफल | नेपाली पात्रो', baseDesc='आजको १२ राशिको दैनिक राशिफल र साप्ताहिक राशिफल हेर्नुहोस्। नेपाल समयअनुसार मेषदेखि मीनसम्मका राशिको सामान्य ज्योतिषीय मार्गदर्शन।';
 const title=i>=0?`${signs[i][1]} राशिफल आज — दैनिक राशिफल | नेपाली पात्रो`:baseTitle;
 const desc=i>=0?`${signs[i][1]} (${signs[i][2]}) को आजको दैनिक राशिफल हेर्नुहोस्। नेपाल समयअनुसार सामान्य ज्योतिषीय मार्गदर्शन।`:baseDesc;
 document.title=title;
 setMeta('meta[name="description"]','content',desc);
 setMeta('meta[property="og:title"]','content',title);
 setMeta('meta[property="og:description"]','content',desc);
 const url=new URL(RASHI_PATH);if(i>=0)url.searchParams.set('rashi',signs[i][2].toLowerCase());
 setMeta('meta[property="og:url"]','content',url.href);
 setMeta('meta[name="twitter:title"]','content',title);
 setMeta('meta[name="twitter:description"]','content',desc);
 const ld=document.querySelector('#rfDynamicSchema');
 if(ld)ld.textContent=JSON.stringify({"@context":"https://schema.org","@type":"WebPage","name":title,"url":url.href,"description":desc,"inLanguage":"ne","isAccessibleForFree":true,"isPartOf":{"@type":"CollectionPage","url":RASHI_PATH}});
};
const ensureSEOElements=()=>{
 if(!document.querySelector('meta[name="twitter:card"]')){const m=document.createElement('meta');m.name='twitter:card';m.content='summary';document.head.appendChild(m)}
 ['twitter:title','twitter:description'].forEach(name=>{if(!document.querySelector(`meta[name="${name}"]`)){const m=document.createElement('meta');m.name=name;document.head.appendChild(m)}});
 if(!document.querySelector('#rfDynamicSchema')){const s=document.createElement('script');s.type='application/ld+json';s.id='rfDynamicSchema';document.head.appendChild(s)}
};
const ensureRashiNav=()=>{
 if(document.querySelector('#rfRashiNav'))return;
 const title=document.createElement('div');title.className='rf-section-title';title.innerHTML='<strong>राशि छिटो छान्नुहोस्</strong><span>१२ राशिहरू</span>';
 const nav=document.createElement('nav');nav.id='rfRashiNav';nav.setAttribute('aria-label','१२ राशिहरू');nav.style.cssText='display:flex;gap:7px;flex-wrap:wrap;margin:0 0 18px';
 signs.forEach(s=>{const id=s[2].toLowerCase(),a=document.createElement('a');a.href=`${RASHI_PATH}?rashi=${id}`;a.dataset.rashi=id;a.textContent=`${s[0]} ${s[1]}`;a.style.cssText='display:inline-flex;align-items:center;min-height:36px;padding:0 11px;border:1px solid #eadede;border-radius:999px;background:rgba(255,255,255,.82);color:#374151;text-decoration:none;font:600 12px/1 inherit;transition:.2s';a.addEventListener('click',()=>saveRashi(id));nav.appendChild(a)});
 const anchor=document.querySelector('#rfPersonal');if(anchor?.parentNode){anchor.parentNode.insertBefore(title,anchor);anchor.parentNode.insertBefore(nav,anchor)}
};
const syncRashiNav=selected=>document.querySelectorAll('#rfRashiNav [data-rashi]').forEach(a=>{const active=a.dataset.rashi===selected;a.setAttribute('aria-current',active?'page':'false');a.style.background=active?'#fff1f2':'rgba(255,255,255,.82)';a.style.borderColor=active?'rgba(153,27,27,.35)':'#eadede';a.style.color=active?'#991b1b':'#374151'});
const validate=(d,type,key)=>{if(!d||!Array.isArray(d.signs)||d.signs.length!==12)throw Error(type==='daily'?`दैनिक राशिफलको १२ राशिको data पूर्ण छैन (${key})`:`साप्ताहिक राशिफलको १२ राशिको data पूर्ण छैन (${key})`);const ids=d.signs.map(x=>x?.id);if(new Set(ids).size!==12||d.signs.some((x,i)=>x.id!==signs[i][2].toLowerCase()||!x.prediction||x.prediction.trim().length<40))throw Error('राशिफल snapshot मान्य छैन।');return d};
const loadDaily=async date=>{const r=await fetch(`${BASE}data/rashifal/${encodeURIComponent(date)}.json?${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(date>today()?`यो भविष्यको मिति हो (${date})। स्रोतमा प्रकाशित भएपछि राशिफल यहाँ स्वतः उपलब्ध हुनेछ।`:`यो मितिको दैनिक राशिफल archive मा उपलब्ध छैन (${date})`);return validate(await r.json(),'daily',date)};
const loadWeekly=async week=>{const r=await fetch(`${BASE}data/rashifal-weekly/${encodeURIComponent(week)}.json?${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(week>monday(today())?`यो भविष्यको हप्ता हो (${week})। साप्ताहिक राशिफल प्रकाशित भएपछि यहाँ स्वतः उपलब्ध हुनेछ।`:`यो हप्ताको साप्ताहिक राशिफल archive मा उपलब्ध छैन (${week})`);return validate(await r.json(),'weekly',week)};
const getSaved=()=>{try{return localStorage.getItem('nepaliPatroRashi')||''}catch{return ''}};
const saveRashi=id=>{try{localStorage.setItem('nepaliPatroRashi',id)}catch{}};
const dailyCard=(d,i,selected)=>{const s=signs[i],f=d.signs[i];return `<article class="rashi-card${selected===s[2].toLowerCase()?' selected':''}" data-rashi="${s[2].toLowerCase()}" tabindex="0" role="button" aria-label="${esc(f.nepali)} राशिफल हेर्नुहोस्">${selected===s[2].toLowerCase()?'<span class="selected-badge">तपाईंको राशि</span>':''}<div class="rashi-head"><span>${s[0]}</span><div><h2>${esc(f.nepali)}</h2><small>${esc(f.english)}</small></div></div><p class="forecast-main">${esc(f.prediction)}</p><div class="lucky"><span>📅 ${esc(d.bsDate)}</span><span>📚 दैनिक राशिफल</span></div></article>`};
const weeklyCard=(d,i)=>{const s=signs[i],f=d.signs[i];return `<article class="week-card"><div class="rashi-head"><span>${s[0]}</span><div><h2>${esc(f.nepali)}</h2><small>${esc(f.english)} · साप्ताहिक</small></div></div><p class="forecast-main">${esc(f.prediction)}</p><div class="lucky"><span>📅 ${esc(d.weekLabel||`${d.weekStart} — ${d.weekEnd}`)}</span><span>📚 साप्ताहिक राशिफल</span></div></article>`};
const showPersonal=(selected,data)=>{const box=document.querySelector('#rfPersonal');if(!box)return;if(!selected){box.classList.remove('show');box.innerHTML='';return}const i=signById(selected);if(i<0||!data?.signs?.[i]){box.classList.remove('show');box.innerHTML='';return}const s=signs[i],f=data.signs[i];box.innerHTML=`<div class="rf-personal-top"><span class="rf-personal-icon">${s[0]}</span><div><h2>तपाईंको आजको राशिफल · ${esc(f.nepali)}</h2><small>${esc(f.english)} · ${esc(data.bsDate||'')}</small></div></div><p>${esc(f.prediction)}</p>`;box.classList.add('show')};
const filterCards=selected=>{document.querySelectorAll('#daily .rashi-card').forEach(card=>{const match=!selected||card.dataset.rashi===selected;card.hidden=!match&&!!selected});const clear=document.querySelector('#clearRashi');if(clear)clear.hidden=!selected};
const updateURL=id=>{const u=new URL(location.href);if(id)u.searchParams.set('rashi',id);else u.searchParams.delete('rashi');history.replaceState(null,'',u.href)};
const bindSelection=(data)=>{document.querySelectorAll('#daily .rashi-card').forEach(card=>{const choose=()=>{const id=card.dataset.rashi;saveRashi(id);updateURL(id);filterCards(id);document.querySelectorAll('#daily .rashi-card').forEach(x=>x.classList.toggle('selected',x===card));document.querySelectorAll('.selected-badge').forEach(x=>x.remove());card.insertAdjacentHTML('afterbegin','<span class="selected-badge">तपाईंको राशि</span>');showPersonal(id,data);updateSEO(id,data);syncRashiNav(id)};card.addEventListener('click',choose);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose()}})});document.querySelector('#clearRashi').onclick=()=>{try{localStorage.removeItem('nepaliPatroRashi')}catch{};updateURL('');filterCards('');document.querySelectorAll('#daily .rashi-card').forEach(x=>x.classList.remove('selected'));document.querySelectorAll('.selected-badge').forEach(x=>x.remove());showPersonal('',data);updateSEO('',data);syncRashiNav('')};document.querySelector('#shareRashi').onclick=async()=>{const id=getSaved(),index=signById(id),name=index>=0?signs[index][1]:'राशिफल';const url=new URL(location.href);url.searchParams.set('rashi',id||'all');const text=`${name} राशिफल · ${document.querySelector('#dateTitle').textContent}`;try{if(navigator.share)await navigator.share({title:text,text:`${text} — नेपाली पात्रो`,url:url.href});else{await navigator.clipboard.writeText(url.href);alert('राशिफलको लिंक copy भयो।')}}catch{}}};
const setActive=weekly=>{document.querySelector('#daily').hidden=weekly;document.querySelector('#weekly').hidden=!weekly;document.querySelector('#dailyTab').classList.toggle('active',!weekly);document.querySelector('#weeklyTab').classList.toggle('active',weekly);document.querySelector('#selectedDate').hidden=weekly;document.querySelector('#todayBtn').hidden=weekly;document.querySelector('#prev').textContent=weekly?'← अघिल्लो हप्ता':'← अघिल्लो दिन';document.querySelector('#next').textContent=weekly?'अर्को हप्ता →':'अर्को दिन →';document.querySelector('#rfActions').hidden=weekly;if(weekly)showPersonal('',null)};
async function renderDaily(date){const data=await loadDaily(date);document.querySelector('#dateTitle').textContent=`दैनिक राशिफल · ${data.bsDate}`;document.querySelector('#dateSub').textContent=`${date} · ${data.weekday||''} · स्रोत: ${data.source||'स्रोत'} · ${data.astrologer||''}`;document.querySelector('#selectedDate').value=date;document.querySelector('#selectedDate').max=today();const params=new URLSearchParams(location.search);const requested=params.get('rashi');const saved=getSaved();const selected=validRashi(requested)?requested:(validRashi(saved)?saved:'');document.querySelector('#daily').innerHTML=data.signs.map((_,i)=>dailyCard(data,i,selected)).join('');ensureSEOElements();ensureRashiNav();bindSelection(data);filterCards(selected);showPersonal(selected,data);updateSEO(selected,data);syncRashiNav(selected);document.querySelector('#prev').onclick=()=>location.href=`${location.pathname}?view=daily&date=${shift(date,-1)}${selected?`&rashi=${selected}`:''}`;document.querySelector('#next').onclick=()=>{const n=shift(date,1);if(n<=today())location.href=`${location.pathname}?view=daily&date=${n}${selected?`&rashi=${selected}`:''}`};document.querySelector('#todayBtn').onclick=()=>location.href=`${location.pathname}?view=daily&date=${today()}${selected?`&rashi=${selected}`:''}`;document.querySelector('#selectedDate').onchange=e=>{if(e.target.value&&e.target.value<=today())location.href=`${location.pathname}?view=daily&date=${e.target.value}${selected?`&rashi=${selected}`:''}`};setActive(false)};
async function renderWeekly(week){const data=await loadWeekly(week);document.querySelector('#dateTitle').textContent=`साप्ताहिक राशिफल · ${data.weekLabel||''}`;document.querySelector('#dateSub').textContent=`${data.weekStart} — ${data.weekEnd} · स्रोत: ${data.source||'स्रोत'} · ${data.astrologer||''}`;document.querySelector('#weekly').innerHTML=data.signs.map((_,i)=>weeklyCard(data,i)).join('');ensureSEOElements();updateSEO('',data);setActive(true);document.querySelector('#prev').onclick=()=>location.href=`${location.pathname}?view=weekly&week=${shift(week,-7)}`;document.querySelector('#next').onclick=()=>{const n=shift(week,7);if(n<=monday(today()))location.href=`${location.pathname}?view=weekly&week=${n}`}};
async function init(){const error=document.querySelector('#rashifalError');error.hidden=true;const params=new URLSearchParams(location.search);const weekly=params.get('view')==='weekly';try{if(weekly)await renderWeekly(params.get('week')||monday(today()));else await renderDaily(params.get('date')||today())}catch(e){error.textContent=e.message||'राशिफल उपलब्ध छैन।';error.hidden=false;document.querySelector('#daily').innerHTML='';document.querySelector('#weekly').innerHTML='';showPersonal('',null);setActive(weekly)}}
document.addEventListener('DOMContentLoaded',()=>{document.querySelector('#dailyTab').onclick=()=>location.href=`${location.pathname}?view=daily&date=${today()}`;document.querySelector('#weeklyTab').onclick=()=>location.href=`${location.pathname}?view=weekly&week=${monday(today())}`;init()});
})();
