(()=>{
 const aliases={patro:'calendar',calendar:'calendar',panchanga:'panchang',panchang:'panchang',parba:'festivals',festivals:'festivals',saith:'saait',saait:'saait',rashifal:'rashifal',news:'news',converter:'converter'};
 const parts=location.pathname.split('/').filter(Boolean),i=parts.indexOf('nepali-patro'),raw=i>=0?(parts[i+1]||''):'';
 const section=aliases[raw.toLowerCase()]; if(!section)return;
 const $=s=>document.querySelector(s);
 const esc=v=>String(v??'—').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
 /* The feature pages already have <base href="../"> pointing at the Nepali-Patro root.
    Using document.baseURI here prevents links from escaping to apps.laxmannepal.com.np/calendar/. */
 const base=()=>new URL(document.baseURI);
 const href=(name,q='')=>new URL(`${name}/${q}`,base()).href;
 function addCss(){if(document.querySelector('link[data-route-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href=new URL('css/router-fixes.css',base()).href;l.dataset.routeCss='1';document.head.appendChild(l)}
 function nav(){const old=$('.mobile-nav');if(old)old.remove();const n=document.createElement('nav');n.className='mobile-nav';n.setAttribute('aria-label','मोबाइल मुख्य मेनु');[['calendar','पात्रो','📅'],['panchanga','पञ्चाङ्ग','☀'],['rashifal','राशिफल','♈'],['news','समाचार','📰'],['converter','रूपान्तरण','↔']].forEach(([id,t,ic])=>{const a=document.createElement('a');a.href=href(id);a.className=aliases[raw]===aliases[id]?'active':'';a.innerHTML=`<span>${ic}</span><small>${t}</small>`;n.appendChild(a)});document.body.appendChild(n)}
 function header(){document.querySelectorAll('.desktop-nav [data-section]').forEach(b=>{b.onclick=e=>{e.preventDefault();const s=b.dataset.section;const r=s==='calendar'?'calendar':s==='panchang'?'panchanga':s==='festivals'?'parba':s==='saait'?'saith':s;location.href=href(r)}})}
 function isolate(){document.querySelectorAll('main > section').forEach(s=>s.classList.add('route-hidden'));const t=document.getElementById(section);if(t)t.classList.remove('route-hidden');document.getElementById('homepageNewsSection')?.classList.add('route-hidden');document.getElementById('quick')?.classList.add('route-hidden');document.getElementById('today')?.classList.add('route-hidden');document.getElementById('dayDetail')?.classList.add('route-hidden');document.body.classList.add('feature-route');
   const titles={calendar:['नेपाली पात्रो','२०४०–२१०० BS का सबै दिन'],panchang:['दैनिक पञ्चाङ्ग','चयन गरिएको दिनको विस्तृत पञ्चाङ्ग'],festivals:['पर्व तथा बिदा','नेपाली पर्व, बिदा र आगामी विशेष दिन'],saait:['साइत र शुभ दिन','शुभ कार्यसम्बन्धी उपलब्ध प्रमाणित जानकारी'],rashifal:['दैनिक राशिफल','१२ राशिको मिति अनुसारको सामान्य राशिफल'],news:['समाचार केन्द्र','नेपालका विभिन्न स्रोतबाट नेपाली समाचार'],converter:['मिति रूपान्तरण','BS ↔ AD मिति रूपान्तरण']};
   const meta=titles[section];if(meta){document.title=`${meta[0]} — नेपाली पात्रो`;const target=document.getElementById(section);if(target&&!target.querySelector('.feature-page-heading')){const h=document.createElement('div');h.className='feature-page-heading';h.innerHTML=`<span class="eyebrow">नेपाली पात्रो</span><h1>${meta[0]}</h1><p>${meta[1]}</p>`;target.insertBefore(h,target.firstChild)}}
 }
 function footer(){const f=$('footer');if(!f)return;f.innerHTML=`<div class="footer-grid"><div><b>नेपाली पात्रो</b><p>विक्रम संवत् पात्रो, पञ्चाङ्ग, पर्व, राशिफल र नेपाली समाचारका लागि स्वतन्त्र डिजिटल प्लेटफर्म।</p></div><div><strong>द्रुत लिंक</strong><a href="${href('calendar')}">पात्रो</a><a href="${href('panchanga')}">पञ्चाङ्ग</a><a href="${href('parba')}">पर्व</a><a href="${href('saith')}">साइत</a><a href="${href('rashifal')}">राशिफल</a><a href="${href('news')}">समाचार</a><a href="${href('converter')}">रूपान्तरण</a></div><div><strong>महत्त्वपूर्ण सूचना</strong><p>पञ्चाङ्ग, साइत तथा राशिफल सामान्य जानकारीका लागि मात्र हुन्। महत्वपूर्ण धार्मिक, स्वास्थ्य, कानुनी वा आर्थिक निर्णयअघि सम्बन्धित विज्ञसँग परामर्श गर्नुहोस्। समाचार सामग्री सम्बन्धित स्रोतको हो।</p></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Laxman Nepal</span><span>नेपाली पात्रो · २०४०–२१०० BS</span></div>`}
 function partsDate(v){const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(v||'');return m?{y:+m[1],m:+m[2],d:+m[3]}:null}
 function dayFromData(data,q){return (data?.days||[]).find(x=>x.ad?.date===q)||null}
 async function getDay(){const q=new URLSearchParams(location.search).get('date')||'';if(!q)return null;const p=partsDate(q);if(!p||p.y<2040||p.y>2100)return null;if(window.DATA?.days){const x=dayFromData(DATA,q);if(x)return x}try{const r=await fetch(new URL(`data/calendar/${p.y}.json`,base()),{cache:'no-store'});if(!r.ok)return null;return dayFromData(await r.json(),q)}catch{return null}}
 function adLabel(q){try{return new Intl.DateTimeFormat('en-US',{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'}).format(new Date(q+'T00:00:00Z'))}catch{return q}}
 function panchang(x){const g=$('#panchangGrid');if(!g||!x)return;const rows=[['BS मिति',x.bs?.display],['AD मिति',adLabel(x.ad.date)],['वार',x.weekday?.nepali],['तिथि',x.tithi?.name],['तिथि समाप्ति',x.tithi?.end],['पक्ष',x.tithi?.paksha],['नक्षत्र',x.nakshatra?.name],['नक्षत्र समाप्ति',x.nakshatra?.end],['योग',x.yoga?.name],['योग समाप्ति',x.yoga?.end],['करण',x.karana?.name],['करण समाप्ति',x.karana?.end],['राशि',x.rashi],['सूर्योदय',x.sun?.sunrise],['सूर्यास्त',x.sun?.sunset],['राहुकाल',x.rahuKaal?(x.rahuKaal.start+' – '+x.rahuKaal.end):'—'],['चन्द्रोदय',x.moon?.rise],['चन्द्रास्त',x.moon?.set],['चन्द्र अवस्था',x.moon?.phase],['नेपाल संवत्',x.nepalSambat],['पर्व',x.festival||'—'],['बिदा',x.holiday?'हो':'होइन']];g.innerHTML=rows.map(r=>`<div class="info-card"><span>${esc(r[0])}</span><b>${esc(r[1]||'डेटा उपलब्ध छैन')}</b></div>`).join('');const l=$('.panchanga-date-label');if(l)l.textContent=`${x.bs?.display||''} · ${adLabel(x.ad.date)}`;const h=document.querySelector('.feature-page-heading h1');if(h)h.textContent=`${x.bs?.display||'पञ्चाङ्ग'} को पञ्चाङ्ग`;}
 const zodiac=[['♈','मेष'],['♉','वृष'],['♊','मिथुन'],['♋','कर्कट'],['♌','सिंह'],['♍','कन्या'],['♎','तुला'],['♏','वृश्चिक'],['♐','धनु'],['♑','मकर'],['♒','कुम्भ'],['♓','मीन']];
 const texts=['आज प्राथमिकता स्पष्ट गरेर अघि बढ्नुहोस्।','सम्बन्ध र संवादमा धैर्य राख्नु लाभदायक हुनेछ।','आर्थिक निर्णयमा तथ्य र बजेटलाई प्राथमिकता दिनुहोस्।','नयाँ अवसर आए पनि निर्णयअघि पर्याप्त जानकारी लिनुहोस्।','परिश्रमको परिणाम विस्तारै देखिन सक्छ; निरन्तरता राख्नुहोस्।','परिवार र कामबीच सन्तुलन कायम गर्नु आजको मुख्य कुरा हो।'];
 function hash(s){let h=0;for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))>>>0;return h}
 function rashifal(x){const g=$('#zodiacGrid');if(!g||!x)return;const h=hash(x.ad.date);g.innerHTML=zodiac.map(([s,n],i)=>{const t=texts[(h+i*7)%texts.length],score=3+((h+i*13)%3);return `<article class="zodiac"><span class="symbol">${s}</span><b>${n}</b><p>${t}</p><small>दैनिक राशिफल · ${'★'.repeat(score)}${'☆'.repeat(5-score)}</small></article>`}).join('');const heading=document.querySelector('.feature-page-heading p');if(heading)heading.textContent=`${x.bs?.display||''} · ${adLabel(x.ad.date)} का सामान्य दैनिक राशिफल`}
 function calendarClicks(){document.addEventListener('click',e=>{const d=e.target.closest('.day[data-day]');if(!d)return;const days=window.DATA?.days;if(!days)return;const m=window.viewMonth||1,x=days.find(v=>v.bs?.month===m&&v.bs?.day===+d.dataset.day);if(x){e.preventDefault();e.stopImmediatePropagation();location.href=href('panchanga',`?date=${encodeURIComponent(x.ad.date)}`)}},true)}
 async function boot(){addCss();isolate();nav();header();footer();calendarClicks();if(section==='panchang'||section==='rashifal'){const x=await getDay();if(x){if(section==='panchang')panchang(x);if(section==='rashifal')rashifal(x)}}}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();