(function(){
  const path=location.pathname.replace(/\/+$/,'/');
  if(path.toLowerCase().indexOf('/nepali-patro/')<0)return;
  const key=(path.split('/').filter(Boolean).pop()||'').toLowerCase();
  const routes={calendar:'calendar',patro:'calendar',panchanga:'panchang',panchang:'panchang',parba:'festivals',festivals:'festivals',saith:'saait',saait:'saait',rashifal:'rashifal',news:'news',converter:'converter'};
  const target=routes[key]; const $=s=>document.querySelector(s);
  function href(name,query){const base=location.pathname.split('/nepali-patro/')[0]+'/nepali-patro/';return base+name+'/'+(query||'')}
  function setActive(name){document.querySelectorAll('[data-site-nav]').forEach(a=>a.classList.toggle('active',a.dataset.siteNav===name));}
  function showOnly(id){const main=$('main');if(!main)return;const sections=[...main.querySelectorAll(':scope > section')];if(!target){sections.forEach(s=>s.classList.remove('route-hidden'));return}const keep=new Set([target]);sections.forEach(s=>s.classList.toggle('route-hidden',!keep.has(s.id)));$('#homepageNewsSection')?.classList.add('route-hidden');$('#quick')?.classList.add('route-hidden');}
  function queryDate(){return new URLSearchParams(location.search).get('date')||''}
  function dateParts(q){let m=q.match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?{y:+m[1],m:+m[2],d:+m[3]}:null}
  function formatAd(q){try{return new Intl.DateTimeFormat('en-US',{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'}).format(new Date(q+'T00:00:00Z'))}catch{return q}}
  async function getDay(){const q=queryDate();if(!q)return null;const local=window.DATA&&Array.isArray(DATA.days)?DATA.days.find(x=>x.ad?.date===q):null;if(local)return local;const p=dateParts(q);if(!p||p.y<2040||p.y>2100)return null;try{const r=await fetch(new URL(`data/calendar/${p.y}.json`,document.baseURI),{cache:'no-store'});if(!r.ok)throw Error('calendar data unavailable');const data=await r.json();return (data.days||[]).find(x=>x.ad?.date===q)||null}catch(e){console.error(e);return null}}
  function renderPanchangDay(x){if(!x)return;const g=$('#panchangGrid');if(!g)return;const rows=[['BS मिति',x.bs?.display],['AD मिति',formatAd(x.ad.date)],['वार',x.weekday?.nepali],['तिथि',x.tithi?.name],['तिथि समाप्ति',x.tithi?.end],['पक्ष',x.tithi?.paksha],['नक्षत्र',x.nakshatra?.name],['नक्षत्र समाप्ति',x.nakshatra?.end],['योग',x.yoga?.name],['योग समाप्ति',x.yoga?.end],['करण',x.karana?.name],['करण समाप्ति',x.karana?.end],['राशि',x.rashi],['सूर्योदय',x.sun?.sunrise],['सूर्यास्त',x.sun?.sunset],['राहुकाल',x.rahuKaal?(x.rahuKaal.start+' – '+x.rahuKaal.end):'—'],['चन्द्रोदय',x.moon?.rise],['चन्द्रास्त',x.moon?.set],['चन्द्र अवस्था',x.moon?.phase],['नेपाल संवत्',x.nepalSambat],['पर्व',x.festival||'—'],['बिदा',x.holiday?'हो':'होइन']];g.innerHTML=rows.map(([a,b])=>`<div class="info-card"><span>${a}</span><b>${String(b||'डेटा उपलब्ध छैन').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]) )}</b></div>`).join('');const label=$('.panchanga-date-label');if(label)label.textContent=`${x.bs.display} · ${formatAd(x.ad.date)}`}
  const zodiac=[['♈','मेष'],['♉','वृष'],['♊','मिथुन'],['♋','कर्कट'],['♌','सिंह'],['♍','कन्या'],['♎','तुला'],['♏','वृश्चिक'],['♐','धनु'],['♑','मकर'],['♒','कुम्भ'],['♓','मीन']];
  const texts=['आज प्राथमिकता स्पष्ट गरेर अघि बढ्नुहोस्।','सम्बन्ध र संवादमा धैर्य राख्नु लाभदायक हुनेछ।','आर्थिक निर्णयमा तथ्य र बजेटलाई प्राथमिकता दिनुहोस्।','नयाँ अवसर आए पनि निर्णयअघि पर्याप्त जानकारी लिनुहोस्।','परिश्रमको परिणाम विस्तारै देखिन सक्छ; निरन्तरता राख्नुहोस्।','परिवार र कामबीच सन्तुलन कायम गर्नु आजको मुख्य कुरा हो।'];
  function hash(s){let h=0;for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))>>>0;return h}
  function renderDateRashifal(x){const g=$('#zodiacGrid');if(!g||!x)return;const h=hash(x.ad.date);g.innerHTML=zodiac.map(([s,n],i)=>{const t=texts[(h+i*7)%texts.length];const score=3+((h+i*13)%3);return `<article class="zodiac"><span class="symbol">${s}</span><b>${n}</b><p>${t}</p><small>दैनिक राशिफल · ${'★'.repeat(score)}${'☆'.repeat(5-score)}</small></article>`}).join('')}
  function installNav(){const nav=$('.desktop-nav');if(!nav)return;if(!document.querySelector('.mobile-nav')){const m=document.createElement('nav');m.className='mobile-nav';m.setAttribute('aria-label','मोबाइल मुख्य मेनु');[['calendar','पात्रो','📅'],['panchang','पञ्चाङ्ग','☀'],['rashifal','राशिफल','♈'],['news','समाचार','📰'],['converter','रूपान्तरण','↔']].forEach(([id,label,icon])=>{const a=document.createElement('a');a.dataset.siteNav=id;a.href=href(id);a.innerHTML=`<span>${icon}</span><small>${label}</small>`;m.appendChild(a)});document.body.appendChild(m)}nav.querySelectorAll('button[data-section]').forEach(b=>{const sec=b.dataset.section;const rn=sec==='calendar'?'calendar':sec==='panchang'?'panchanga':sec==='festivals'?'parba':sec==='saait'?'saith':sec;b.onclick=e=>{e.preventDefault();location.href=href(rn)}});document.querySelectorAll('[data-section]').forEach(b=>{if(b.closest('.desktop-nav'))return;b.addEventListener('click',e=>{const sec=b.dataset.section;if(!sec)return;e.preventDefault();const rn=sec==='calendar'?'calendar':sec==='panchang'?'panchanga':sec==='festivals'?'parba':sec==='saait'?'saith':sec;location.href=href(rn)})})}
  function installDateNavigation(){document.addEventListener('click',e=>{const btn=e.target.closest('.day[data-day]');if(!btn||!window.DATA)return;e.preventDefault();e.stopImmediatePropagation();const m=window.viewMonth||1,d=+btn.dataset.day;const x=DATA.days.find(v=>v.bs?.month===m&&v.bs?.day===d);if(x)location.href=href('panchanga',`?date=${x.ad.date}`)},true)}
  function installFooter(){const f=$('footer');if(!f)return;f.innerHTML=`<div class="footer-grid"><div><b>नेपाली पात्रो</b><p>विक्रम संवत् पात्रो, पञ्चाङ्ग, पर्व, राशिफल र नेपाली समाचारका लागि स्वतन्त्र डिजिटल प्लेटफर्म।</p></div><div><strong>द्रुत लिंक</strong><a href="${href('calendar')}">पात्रो</a><a href="${href('panchanga')}">पञ्चाङ्ग</a><a href="${href('rashifal')}">राशिफल</a><a href="${href('news')}">समाचार</a></div><div><strong>महत्त्वपूर्ण सूचना</strong><p>पञ्चाङ्ग तथा ज्योतिषीय सामग्री सामान्य जानकारीका लागि मात्र हुन्। साइत, मुहूर्त, स्वास्थ्य, आर्थिक वा अन्य महत्वपूर्ण निर्णयअघि सम्बन्धित विज्ञसँग परामर्श गर्नुहोस्। समाचार सामग्री सम्बन्धित स्रोतको हो।</p></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Laxman Nepal</span><span>नेपाली पात्रो · २०४०–२१०० BS</span></div>`}
  async function boot(){installNav();installDateNavigation();installFooter();showOnly(target);setActive(target||'');if(target==='panchang'||target==='rashifal'){const x=await getDay();if(x){renderPanchangDay(x);renderDateRashifal(x)}}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();