import { SwissEphemeris, Planet, SiderealMode, CalculationFlag, LunarPoint, HouseSystem } from 'https://esm.unpkg.com/@swisseph/browser@1.3.1';

const $ = id => document.getElementById(id);
const SIGNS = ['मेष','वृष','मिथुन','कर्कट','सिंह','कन्या','तुला','वृश्चिक','धनु','मकर','कुम्भ','मीन'];
const SIGN_EN = ['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'];
const NAKS = ['अश्विनी','भरणी','कृत्तिका','रोहिणी','मृगशिरा','आर्द्रा','पुनर्वसु','पुष्य','आश्लेषा','मघा','पूर्वाफाल्गुनी','उत्तराफाल्गुनी','हस्त','चित्रा','स्वाती','विशाखा','अनुराधा','ज्येष्ठा','मूल','पूर्वाषाढा','उत्तराषाढा','श्रवण','धनिष्ठा','शतभिषा','पूर्वाभाद्रपदा','उत्तराभाद्रपदा','रेवती'];
const NAK_LORDS = ['केतु','शुक्र','सूर्य','चन्द्र','मंगल','राहु','गुरु','शनि','बुध'];
const GRAHAS = [['sun','सूर्य','☉',Planet.Sun],['moon','चन्द्र','☽',Planet.Moon],['mars','मंगल','♂',Planet.Mars],['mercury','बुध','☿',Planet.Mercury],['jupiter','गुरु','♃',Planet.Jupiter],['venus','शुक्र','♀',Planet.Venus],['saturn','शनि','♄',Planet.Saturn]];
const NUM=['०','१','२','३','४','५','६','७','८','९'];
const nep = n => String(n).replace(/\d/g,d=>NUM[d]);
const norm = x => ((x%360)+360)%360;
const signOf = x => Math.floor(norm(x)/30);
const degInSign = x => norm(x)%30;
const dms = x => { let d=degInSign(x), di=Math.floor(d), m=Math.floor((d-di)*60), s=Math.round((((d-di)*60)-m)*60); if(s===60){s=0;m++} if(m===60){m=0;di++} return `${nep(di)}° ${nep(m)}′ ${nep(s)}″`; };
const nak = lon => { const u=360/27, i=Math.min(26,Math.floor(norm(lon)/u)), p=Math.min(4,Math.floor((norm(lon)%u)/(u/4))+1); return {name:NAKS[i],index:i,pada:p,lord:NAK_LORDS[i%9]}; };
const navamsa = lon => { const s=signOf(lon), p=Math.min(8,Math.floor(degInSign(lon)/(30/9))); return (s*9+p)%12; };
let swe=null,last=null;

async function init(){ swe=new SwissEphemeris(); await swe.init(); $('engineState').textContent='✓ गणना इन्जिन तयार'; $('engineMeta').textContent='Swiss Ephemeris WASM · Sidereal'; }
async function loadYear(y){ const r=await fetch(`../data/calendar/${y}.json`,{cache:'force-cache'}); if(!r.ok) throw Error(`BS ${y} calendar data भेटिएन।`); const j=await r.json(); return j.days||[]; }
async function bsToAd(y,m,d){ const days=await loadYear(y); const row=days.find(x=>x.bs?.year===y && x.bs?.month===m && x.bs?.day===d); if(!row) throw Error('दिइएको BS मिति calendar data मा भेटिएन।'); return row.ad.date; }
function selectedSidereal(){ const v=$('ayan').value; if(v==='raman') return SiderealMode.Raman; if(v==='krishnamurti') return SiderealMode.Krishnamurti; return SiderealMode.Lahiri; }
function readInput(){ const y=+$('year').value,m=+$('month').value,d=+$('day').value; const [hh,mm]=($('time').value||'12:00').split(':').map(Number); const x={name:$('name').value.trim()||'जन्मकुण्डली',cal:$('calendar').value,y,m,d,hh,mm,place:$('place').value.trim(),lat:+$('lat').value,lon:+$('lon').value,tz:+$('tz').value}; if(!y||!m||!d||!Number.isFinite(x.lat)||!Number.isFinite(x.lon)||!Number.isFinite(x.tz)) throw Error('मिति, समय, latitude, longitude र UTC offset जाँच गर्नुहोस्।'); if(x.lat<-90||x.lat>90||x.lon<-180||x.lon>180||x.tz<-14||x.tz>14) throw Error('स्थान वा UTC offset को मान अमान्य छ।'); return x; }
async function toDate(x){ let y=x.y,m=x.m,d=x.d; if(x.cal==='bs'){ const ad=await bsToAd(y,m,d); [y,m,d]=ad.split('-').map(Number); } return {date:new Date(Date.UTC(y,m-1,d,x.hh,x.mm)-x.tz*3600000),ad:`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`}; }
function calcPlanet(jd,body){ const p=swe.calculatePosition(jd,body,CalculationFlag.SwissEphemeris|CalculationFlag.Speed|CalculationFlag.Sidereal); return {longitude:norm(p.longitude),latitude:p.latitude,speed:p.longitudeSpeed,retrograde:p.longitudeSpeed<0}; }
function calculate(x,jd){ swe.setSiderealMode(selectedSidereal()); const planets={}; for(const [id,name,symbol,body] of GRAHAS) planets[id]={id,name,symbol,body,...calcPlanet(jd,body)}; const node=swe.calculatePosition(jd,$('nodes').value==='true'?LunarPoint.TrueNode:LunarPoint.MeanNode,CalculationFlag.SwissEphemeris|CalculationFlag.Speed|CalculationFlag.Sidereal); const rahu=norm(node.longitude), ketu=norm(rahu+180); planets.rahu={id:'rahu',name:'राहु',symbol:'☊',longitude:rahu,latitude:node.latitude,speed:node.longitudeSpeed,retrograde:node.longitudeSpeed<0}; planets.ketu={id:'ketu',name:'केतु',symbol:'☋',longitude:ketu,latitude:-node.latitude,speed:-node.longitudeSpeed,retrograde:node.longitudeSpeed>0};
 const hs=swe.calculateHouses(jd,x.lat,x.lon,HouseSystem.WholeSign); const asc=norm(hs.ascendant), ascSign=signOf(asc); Object.values(planets).forEach(p=>{p.sign=signOf(p.longitude);p.degree=degInSign(p.longitude);p.house=((p.sign-ascSign+12)%12)+1;p.nak=nak(p.longitude);p.d9=navamsa(p.longitude);}); return {planets,asc,ascSign,jd,ayan:swe.getAyanamsa(jd),date:x}; }
function chartSvg(core){ const hp=Array.from({length:12},()=>[]); Object.values(core.planets).forEach(p=>hp[p.house-1].push(`${p.symbol}`)); const pos=[[250,105],[395,170],[395,330],[250,395],[105,330],[105,170],[250,180],[320,250],[250,320],[180,250],[110,110],[390,110]]; let s=`<svg viewBox="0 0 500 500" role="img" aria-label="D1 जन्म कुण्डली"><rect x="25" y="25" width="450" height="450" fill="none" stroke="currentColor" stroke-width="2"/><path d="M25 25L475 475M475 25L25 475M25 250H475M250 25V475M25 250L250 25L475 250L250 475Z" fill="none" stroke="currentColor" stroke-width="1.7"/>`; for(let h=1;h<=12;h++){const [x,y]=pos[h-1],sign=(core.ascSign+h-1)%12;s+=`<text x="${x}" y="${y-16}" text-anchor="middle" font-size="12">${h} · ${SIGNS[sign]}</text><text x="${x}" y="${y+10}" text-anchor="middle" font-size="20" font-weight="700">${hp[h-1].join(' ')||'·'}</text>`} return s+'</svg>'; }
function tableRows(core){ return Object.values(core.planets).map(p=>`<tr><td><b>${p.symbol} ${p.name}</b></td><td>${SIGNS[p.sign]}</td><td>${dms(p.longitude)}</td><td>${p.nak.name} · पाद ${nep(p.nak.pada)}</td><td>${nep(p.house)}</td><td>${SIGN_EN[p.d9]}</td><td>${p.retrograde?'वक्री':'मार्गी'}</td></tr>`).join(''); }
function dashaRows(core){ const moon=core.planets.moon, seq=['केतु','शुक्र','सूर्य','चन्द्र','मंगल','राहु','गुरु','शनि','बुध'], years={केतु:7,शुक्र:20,सूर्य:6,चन्द्र:10,मंगल:7,राहु:18,गुरु:16,शनि:19,बुध:17}, start=seq.indexOf(moon.nak.lord), span=360/27, elapsed=(norm(moon.longitude)%span)/span, birth=core.dateObj; let cursor=birth.getTime()-years[seq[start]]*(1-elapsed)*365.2425*86400000; return Array.from({length:9},(_,i)=>{const lord=seq[(start+i)%9], dur=years[lord]*(i===0?1-elapsed:1), from=new Date(cursor), to=new Date(cursor+dur*365.2425*86400000); cursor=to.getTime(); return `<tr><td>${lord}</td><td>${dur.toFixed(2)} वर्ष</td><td>${from.toISOString().slice(0,10)}</td><td>${to.toISOString().slice(0,10)}</td></tr>`}).join(''); }
function render(core,ad){ const moon=core.planets.moon,sun=core.planets.sun; $('results').hidden=false; $('personTitle').textContent=core.date.name; $('birthSummary').textContent=`${ad} · ${String(core.date.hh).padStart(2,'0')}:${String(core.date.mm).padStart(2,'0')} · ${core.date.place}`; $('method').innerHTML=[`Sidereal`,`अयनांश: ${$('ayan').selectedOptions[0].text}`,`भाव: Whole Sign`,`Node: ${$('nodes').selectedOptions[0].text}`,`JD: ${core.jd.toFixed(5)}`].map(x=>`<span>${x}</span>`).join(''); $('chart').innerHTML=chartSvg(core); $('facts').innerHTML=[['लग्न',`${SIGNS[core.ascSign]} · ${dms(core.asc)}`],['चन्द्र राशि',SIGNS[moon.sign]],['जन्म नक्षत्र',`${moon.nak.name} · पाद ${nep(moon.nak.pada)}`],['नक्षत्र स्वामी',moon.nak.lord],['सूर्य राशि',SIGNS[sun.sign]],['अयनांश',dms(core.ayan)],['राहु',`${SIGNS[core.planets.rahu.sign]} · ${dms(core.planets.rahu.longitude)}`],['केतु',`${SIGNS[core.planets.ketu.sign]} · ${dms(core.planets.ketu.longitude)}`]].map(([a,b])=>`<div class="fact"><small>${a}</small><b>${b}</b></div>`).join(''); $('tabContent').innerHTML=`<div class="table-wrap"><table class="data-table"><thead><tr><th>ग्रह</th><th>राशि</th><th>अंश</th><th>नक्षत्र</th><th>भाव</th><th>D9</th><th>गति</th></tr></thead><tbody>${tableRows(core)}</tbody></table></div>`; last={core,ad}; }
function renderTab(name){ if(!last)return; const c=last.core; if(name==='planets') return render(c,last.ad); if(name==='houses'){ $('tabContent').innerHTML=`<div class="houses-grid">${Array.from({length:12},(_,i)=>{const sign=(c.ascSign+i)%12, ps=Object.values(c.planets).filter(p=>p.house===i+1).map(p=>`${p.symbol} ${p.name}`).join(' · ')||'—';return `<article><b>भाव ${nep(i+1)}</b><strong>${SIGNS[sign]}</strong><p>${ps}</p></article>`}).join('')}</div>`; } else if(name==='nakshatra'){ $('tabContent').innerHTML=`<div class="table-wrap"><table class="data-table"><thead><tr><th>ग्रह</th><th>नक्षत्र</th><th>पाद</th><th>स्वामी</th></tr></thead><tbody>${Object.values(c.planets).map(p=>`<tr><td>${p.symbol} ${p.name}</td><td>${p.nak.name}</td><td>${nep(p.nak.pada)}</td><td>${p.nak.lord}</td></tr>`).join('')}</tbody></table></div>`; } else if(name==='navamsa'){ $('tabContent').innerHTML=`<div class="houses-grid">${Array.from({length:12},(_,i)=>`<article><b>${SIGNS[i]}</b><strong>D9</strong><p>${Object.values(c.planets).filter(p=>p.d9===i).map(p=>`${p.symbol} ${p.name}`).join(' · ')||'—'}</p></article>`).join('')}</div>`; } else if(name==='dasha'){ $('tabContent').innerHTML=`<p class="notice">विंशोत्तरी दशा चन्द्रको जन्म नक्षत्रको बाँकी अंशबाट सुरु हुन्छ। मिति astronomy day length को आधारमा देखाइएको हो; अत्यन्त सूक्ष्म अन्तरदशाका लागि अलग validation आवश्यक हुन्छ।</p><div class="table-wrap"><table class="data-table"><thead><tr><th>महादशा</th><th>अवधि</th><th>सुरु</th><th>अन्त्य</th></tr></thead><tbody>${dashaRows(c)}</tbody></table></div>`; } else if(name==='points'){ $('tabContent').innerHTML=`<div class="point-grid"><div><b>राहु</b><strong>${SIGNS[c.planets.rahu.sign]} ${dms(c.planets.rahu.longitude)}</strong></div><div><b>केतु</b><strong>${SIGNS[c.planets.ketu.sign]} ${dms(c.planets.ketu.longitude)}</strong></div><div><b>लग्न</b><strong>${SIGNS[c.ascSign]} ${dms(c.asc)}</strong></div></div>`; } else if(name==='panchanga'){ $('tabContent').innerHTML=`<div class="point-grid"><div><b>जन्म मिति</b><strong>${last.ad}</strong></div><div><b>समय</b><strong>${String(c.date.hh).padStart(2,'0')}:${String(c.date.mm).padStart(2,'0')}</strong></div><div><b>स्थान</b><strong>${c.date.place}</strong></div></div><p class="notice">तिथि/करण/योग/सूर्योदयजस्ता जन्म-पञ्चाङ्गका सूक्ष्म मानहरू स्थान र स्थानीय सूर्योदयमा निर्भर हुन्छन्। तिनीहरूलाई calendar/panchanga engine सँग जोडेर अर्को validation चरणमा विस्तार गर्न सकिन्छ।</p>`; } else $('tabContent').innerHTML=`<div class="notice">Swiss Ephemeris · ${$('ayan').selectedOptions[0].text} · Whole Sign. ग्रह गणना browser-side हुन्छ। महत्वपूर्ण ज्योतिषीय निर्णयका लागि विशेषज्ञसँग cross-check गर्नुहोस्।</div>`; }
async function generate(){ $('generate').disabled=true; $('error').hidden=true; try{ const x=readInput(), {date,ad}=await toDate(x); swe.setSiderealMode(selectedSidereal()); const jd=swe.julianDay(date.getUTCFullYear(),date.getUTCMonth()+1,date.getUTCDate(),date.getUTCHours()+date.getUTCMinutes()/60+date.getUTCSeconds()/3600); const core=calculate(x,jd); core.dateObj=date; render(core,ad); }catch(e){ $('error').hidden=false; $('error').textContent=e.message; }finally{$('generate').disabled=false;} }
$('generate').onclick=generate; $('sample').onclick=()=>{ $('name').value='लक्ष्मण नेपाल'; $('calendar').value='ad'; $('year').value='2002'; $('month').value='3'; $('day').value='18'; $('time').value='12:00'; $('place').value='Kathmandu, Nepal'; $('lat').value='27.7172'; $('lon').value='85.3240'; $('tz').value='5.75'; };
$('print').onclick=()=>window.print(); $('save').onclick=()=>{ if(last){localStorage.setItem('nepali-patro-kundali',JSON.stringify({input:readInput(),ad:last.ad,savedAt:new Date().toISOString()})); alert('कुण्डली विवरण यस ब्राउजरमा सेभ भयो।');} };
$('downloadChart').onclick=()=>{if(!last)return; const blob=new Blob([chartSvg(last.core)],{type:'image/svg+xml'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kundali-d1.svg';a.click();URL.revokeObjectURL(a.href);};
$('tabs').onclick=e=>{const b=e.target.closest('.tab');if(!b)return;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTab(b.dataset.tab);};
$('theme').onclick=()=>document.body.classList.toggle('dark');
(async()=>{try{await init()}catch(e){$('engineState').textContent='✕ इन्जिन लोड भएन';$('engineMeta').textContent=e.message}})();