import { SwissEphemeris, Planet, SiderealMode, CalculationFlag, LunarPoint, HouseSystem } from 'https://cdn.jsdelivr.net/npm/@swisseph/browser@1.3.1/+esm';

const $=id=>document.getElementById(id);
const SIGNS=['मेष','वृष','मिथुन','कर्कट','सिंह','कन्या','तुला','वृश्चिक','धनु','मकर','कुम्भ','मीन'];
const SIGN_EN=['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'];
const NAKS=['अश्विनी','भरणी','कृत्तिका','रोहिणी','मृगशिरा','आर्द्रा','पुनर्वसु','पुष्य','आश्लेषा','मघा','पूर्वाफाल्गुनी','उत्तराफाल्गुनी','हस्त','चित्रा','स्वाती','विशाखा','अनुराधा','ज्येष्ठा','मूल','पूर्वाषाढा','उत्तराषाढा','श्रवण','धनिष्ठा','शतभिषा','पूर्वाभाद्रपदा','उत्तराभाद्रपदा','रेवती'];
const NAK_LORDS=['केतु','शुक्र','सूर्य','चन्द्र','मंगल','राहु','गुरु','शनि','बुध'];
const VIM_ORDER=['केतु','शुक्र','सूर्य','चन्द्र','मंगल','राहु','गुरु','शनि','बुध'];
const VIM_YEARS={केतु:7,शुक्र:20,सूर्य:6,चन्द्र:10,मंगल:7,राहु:18,गुरु:16,शनि:19,बुध:17};
const PLANETS=[['sun','सूर्य','सू',Planet.Sun],['moon','चन्द्र','चं',Planet.Moon],['mars','मंगल','मं',Planet.Mars],['mercury','बुध','बु',Planet.Mercury],['jupiter','गुरु','बृ',Planet.Jupiter],['venus','शुक्र','शु',Planet.Venus],['saturn','शनि','श',Planet.Saturn]];
const DIG=['०','१','२','३','४','५','६','७','८','९'];
const nep=x=>String(x).replace(/\d/g,d=>DIG[d]);
const norm=x=>((x%360)+360)%360;
const sign=x=>Math.floor(norm(x)/30);
const deg=x=>norm(x)%30;
const dms=x=>{let d=deg(x),a=Math.floor(d),m=Math.floor((d-a)*60),s=Math.round((d-a-m/60)*3600);if(s>=60){s-=60;m++;}if(m>=60){m-=60;a++;}return `${nep(a)}° ${nep(m)}′ ${nep(s)}″`};
const nak=x=>{const span=360/27,i=Math.min(26,Math.floor(norm(x)/span)),p=Math.min(4,Math.floor((norm(x)%span)/(span/4))+1);return{name:NAKS[i],pada:p,lord:NAK_LORDS[i%9],index:i}};
function d9Sign(lon){const r=norm(lon),s=Math.floor(r/30),part=Math.floor((r%30)/(10/3));let start;if([0,3,6,9].includes(s))start=s;else if([1,4,7,10].includes(s))start=(s+8)%12;else if([2,5,8,11].includes(s))start=(s+4)%12;return(start+part)%12}
function d10Sign(lon){const s=sign(lon),part=Math.min(9,Math.floor(deg(lon)/3));return (s%2===0?(s+part):(s+8+part))%12}
function d2Sign(lon){const s=sign(lon),part=Math.floor(deg(lon)/15);return part===0?(s%2===0?s:((s+4)%12)):((s%2===0?(s+8)%12:s%12))}
let swe=null,ready=null,last=null,usingFiles=false,locationTimer=null,locationAbort=null;
async function init(){if(ready)return ready;ready=(async()=>{swe=new SwissEphemeris();await swe.init();$('engineState').textContent='✓ गणना इन्जिन तयार';$('engineMeta').textContent='Swiss Ephemeris WASM';try{await swe.loadStandardEphemeris();usingFiles=true;$('engineMeta').textContent='Swiss Ephemeris · Standard files'}catch{$('engineMeta').textContent='Swiss Ephemeris · Moshier fallback'}return swe})().catch(e=>{ready=null;$('engineState').textContent='✕ इन्जिन लोड भएन';$('engineMeta').textContent=e.message||String(e);throw e});return ready}
function flags(){let f=CalculationFlag.Sidereal|CalculationFlag.Speed;if(usingFiles)f|=CalculationFlag.SwissEphemeris;return f}
function ayanMode(){const v=$('ayan').value;return v==='raman'?SiderealMode.Raman:v==='krishnamurti'?SiderealMode.Krishnamurti:SiderealMode.Lahiri}
async function bsToAd(y,m,d){const r=await fetch(`../data/calendar/${y}.json`,{cache:'force-cache'});if(!r.ok)throw Error(`BS ${y} calendar data भेटिएन।`);const rows=(await r.json()).days||[];const row=rows.find(x=>x.bs?.year===y&&x.bs?.month===m&&x.bs?.day===d);if(!row)throw Error('दिइएको BS मिति calendar data मा भेटिएन।');return row.ad.date}
function input(){const y=+$('year').value,m=+$('month').value,d=+$('day').value,[hh,mm]=($('time').value||'12:00').split(':').map(Number);const x={name:$('name').value.trim()||'जन्मकुण्डली',cal:$('calendar').value,y,m,d,hh,mm,place:$('place').value.trim(),lat:+$('lat').value,lon:+$('lon').value,tz:+$('tz').value};if(!y||!m||!d||!Number.isFinite(x.lat)||!Number.isFinite(x.lon)||!Number.isFinite(x.tz))throw Error('मिति, समय, जन्मस्थान र timezone जाँच गर्नुहोस्।');if(x.lat<-90||x.lat>90||x.lon<-180||x.lon>180||x.tz<-14||x.tz>14)throw Error('स्थान वा timezone को मान अमान्य छ।');return x}
async function utcDate(x){let y=x.y,m=x.m,d=x.d;if(x.cal==='bs'){const ad=await bsToAd(y,m,d);[y,m,d]=ad.split('-').map(Number)}const localMs=Date.UTC(y,m-1,d,x.hh,x.mm,0);const utc=new Date(localMs-x.tz*3600000);return{utc,y,m,d,ad:`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`}}
function planet(jd,id,body){const p=swe.calculatePosition(jd,body,flags()),longitude=norm(p.longitude);return{id,name:id,symbol:'',longitude,latitude:p.latitude,speed:p.longitudeSpeed,retrograde:p.longitudeSpeed<0,sign:sign(longitude),degree:deg(longitude),nak:nak(longitude),d9:d9Sign(longitude),d10:d10Sign(longitude),d2:d2Sign(longitude)}}
function calc(x,bd){swe.setSiderealMode(ayanMode());const u=bd.utc,hour=u.getUTCHours()+u.getUTCMinutes()/60+u.getUTCSeconds()/3600,jd=swe.julianDay(u.getUTCFullYear(),u.getUTCMonth()+1,u.getUTCDate(),hour);const planets={};for(const [id,name,symbol,body] of PLANETS){const p=planet(jd,id,body);p.name=name;p.symbol=symbol;planets[id]=p}const node=swe.calculatePosition(jd,$('nodes').value==='true'?LunarPoint.TrueNode:LunarPoint.MeanNode,flags()),rahu=norm(node.longitude),ketu=norm(rahu+180);for(const [id,name,symbol,longitude,speed] of [['rahu','राहु','रा',rahu,node.longitudeSpeed],['ketu','केतु','के',ketu,-node.longitudeSpeed]])planets[id]={id,name,symbol,longitude,latitude:node.latitude,speed,retrograde:true,sign:sign(longitude),degree:deg(longitude),nak:nak(longitude),d9:d9Sign(longitude),d10:d10Sign(longitude),d2:d2Sign(longitude)};const hs=swe.calculateHouses(jd,x.lat,x.lon,HouseSystem.WholeSign),asc=norm(hs.ascendant),ascSign=sign(asc);Object.values(planets).forEach(p=>p.house=((p.sign-ascSign+12)%12)+1);return{planets,asc,ascSign,jd,ayan:swe.getAyanamsa(jd),utc:u.toISOString(),local:`${bd.ad} ${String(x.hh).padStart(2,'0')}:${String(x.mm).padStart(2,'0')}`,input:x}}
function addYears(date,years){const d=new Date(date);d.setUTCDate(d.getUTCDate()+Math.round(years*365.2425));return d}
function fmtDate(d){return d.toISOString().slice(0,10)}
function dasha(c){const moon=c.planets.moon,span=360/27,n=moon.nak.index,firstIndex=n%9,fraction=(moon.longitude-(n*span))/span;let start=firstIndex,cur=new Date(c.utc),balance=VIM_YEARS[VIM_ORDER[start]]*(1-fraction),rows=[];let end=addYears(cur,balance);rows.push({lord:VIM_ORDER[start],start:new Date(cur),end:new Date(end),active:true});cur=end;for(let i=1;i<18;i++){const lord=VIM_ORDER[(start+i)%9],e=addYears(cur,VIM_YEARS[lord]);rows.push({lord,start:new Date(cur),end:new Date(e),active:false});cur=e}const now=new Date();const active=rows.find(r=>now>=r.start&&now<r.end);if(active)rows.forEach(r=>r.active=r===active);const ad=[];if(active){const total=(active.end-active.start),elapsed=Math.max(0,Math.min(total,now-active.start)),ratio=elapsed/total,ai=VIM_ORDER.indexOf(active.lord);for(let i=0;i<9;i++){const lord=VIM_ORDER[(ai+i)%9],dur=total*(VIM_YEARS[lord]/120),s=new Date(active.start.getTime()+total*VIM_YEARS[lord]/120*i);ad.push({lord,start:s,end:new Date(s.getTime()+dur),active:now>=s&&now<new Date(s.getTime()+dur),progress:ratio})}}return{rows,antardasha:ad}}
function chart(c,division=1){const hp=Array.from({length:12},()=>[]);const divSign=p=>division===9?p.d9:division===10?p.d10:division===2?p.d2:p.sign;const ascDiv=division===9?d9Sign(c.asc):division===10?d10Sign(c.asc):division===2?d2Sign(c.asc):c.ascSign;Object.values(c.planets).forEach(p=>{const s=divSign(p);const house=division===1?p.house-1:(s-ascDiv+12)%12;hp[house].push(p.symbol)});const pos=[[250,95],[400,165],[400,335],[250,405],[100,335],[100,165],[250,170],[330,250],[250,330],[170,250],[115,115],[385,115]];let s='<svg viewBox="0 0 500 500" role="img" aria-label="North Indian Kundali"><rect x="25" y="25" width="450" height="450" fill="none" stroke="currentColor" stroke-width="2"/><path d="M25 25L475 475M475 25L25 475M25 250H475M250 25V475M25 250L250 25L475 250L250 475Z" fill="none" stroke="currentColor" stroke-width="1.8"/>';for(let h=1;h<=12;h++){const [x,y]=pos[h-1],sg=(ascDiv+h-1)%12;s+=`<text x="${x}" y="${y-16}" text-anchor="middle" font-size="12" fill="currentColor">${nep(h)} · ${SIGNS[sg]}</text><text x="${x}" y="${y+12}" text-anchor="middle" font-size="20" font-weight="700" fill="currentColor">${hp[h-1].join(' ')||'·'}</text>`}return s+'</svg>'}
function table(c){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>ग्रह</th><th>राशि</th><th>अंश</th><th>नक्षत्र</th><th>भाव</th><th>D9</th><th>D10</th><th>गति</th></tr></thead><tbody>${Object.values(c.planets).map(p=>`<tr><td>${p.symbol} ${p.name}</td><td>${SIGNS[p.sign]}</td><td>${dms(p.longitude)}</td><td>${p.nak.name} · पाद ${nep(p.nak.pada)}</td><td>${nep(p.house)}</td><td>${SIGNS[p.d9]}</td><td>${SIGNS[p.d10]}</td><td>${p.retrograde?'वक्री':'मार्गी'}</td></tr>`).join('')}</tbody></table></div>`}
function facts(c){const m=c.planets.moon;return [['लग्न',`${SIGNS[c.ascSign]} · ${dms(c.asc)}`],['चन्द्र राशि',`${SIGNS[m.sign]} · ${SIGN_EN[m.sign]}`],['सूर्य राशि',`${SIGNS[c.planets.sun.sign]} · ${SIGN_EN[c.planets.sun.sign]}`],['नक्षत्र',`${m.nak.name} · पाद ${nep(m.nak.pada)}`],['नक्षत्र स्वामी',m.nak.lord],['नामाक्षर',nameLetter(m.nak.name,m.nak.pada)],['राहु',`${SIGNS[c.planets.rahu.sign]} · ${dms(c.planets.rahu.longitude)}`],['केतु',`${SIGNS[c.planets.ketu.sign]} · ${dms(c.planets.ketu.longitude)}`]].map(([a,b])=>`<div class="fact"><small>${a}</small><b>${b}</b></div>`).join('')}
function nameLetter(n,p){const map={'अश्विनी':['चु','चे','चो','ला'],'भरणी':['ली','लू','ले','लो'],'कृत्तिका':['अ','ई','उ','ए'],'रोहिणी':['ओ','वा','वी','वु'],'मृगशिरा':['वे','वो','का','की'],'आर्द्रा':['कु','घ','ङ','छ'],'पुनर्वसु':['के','को','हा','ही'],'पुष्य':['हु','हे','हो','डा'],'आश्लेषा':['डी','डू','डे','डो'],'मघा':['मा','मी','मु','मे'],'पूर्वाफाल्गुनी':['मो','टा','टी','टू'],'उत्तराफाल्गुनी':['टे','टो','पा','पी'],'हस्त':['पू','ष','ण','ठ'],'चित्रा':['पे','पो','रा','री'],'स्वाती':['रू','रे','रो','ता'],'विशाखा':['ती','तू','ते','तो'],'अनुराधा':['ना','नी','नू','ने'],'ज्येष्ठा':['नो','या','यी','यू'],'मूल':['ये','यो','भा','भी'],'पूर्वाषाढा':['भू','धा','फा','ढा'],'उत्तराषाढा':['भे','भो','जा','जी'],'श्रवण':['जू','जे','जो','घा'],'धनिष्ठा':['गा','गी','गु','गे'],'शतभिषा':['गो','सा','सी','सू'],'पूर्वाभाद्रपदा':['से','सो','दा','दी'],'उत्तराभाद्रपदा':['दू','थ','झ','ञ'],'रेवती':['दे','दो','चा','ची']};return(map[n]||['—','—','—','—'])[p-1]}
function render(c,bd){last={core:c,bd};$('results').hidden=false;$('personTitle').textContent=c.input.name;$('birthSummary').textContent=`${bd.ad} · ${String(c.input.hh).padStart(2,'0')}:${String(c.input.mm).padStart(2,'0')} · ${c.input.place}`;$('method').innerHTML=[`Sidereal`,`अयनांश: ${$('ayan').selectedOptions[0].text}`,`भाव: Whole Sign`,`Node: ${$('nodes').selectedOptions[0].text}`,usingFiles?'Swiss ephemeris files':'Moshier fallback',`JD: ${c.jd.toFixed(6)}`,`UTC: ${c.utc}`].map(x=>`<span>${x}</span>`).join('');$('chart').innerHTML=chart(c,1);$('facts').innerHTML=facts(c);tab('planets')}
function tab(name){if(!last)return;const c=last.core;if(name==='planets')$('tabContent').innerHTML=table(c);else if(name==='houses')$('tabContent').innerHTML=`<div class="houses-grid">${Array.from({length:12},(_,i)=>`<article><b>भाव ${nep(i+1)}</b><strong>${SIGNS[(c.ascSign+i)%12]}</strong><p>${Object.values(c.planets).filter(p=>p.house===i+1).map(p=>p.symbol+' '+p.name).join(' · ')||'—'}</p></article>`).join('')}</div>`;else if(name==='nakshatra')$('tabContent').innerHTML=`<div class="table-wrap"><table class="data-table"><thead><tr><th>ग्रह</th><th>नक्षत्र</th><th>पाद</th><th>स्वामी</th></tr></thead><tbody>${Object.values(c.planets).map(p=>`<tr><td>${p.symbol} ${p.name}</td><td>${p.nak.name}</td><td>${nep(p.nak.pada)}</td><td>${p.nak.lord}</td></tr>`).join('')}</tbody></table></div>`;else if(name==='navamsa')$('tabContent').innerHTML=`<div class="chart-card"><div class="card-title"><h3>D9 · नवमांश</h3></div><div class="chart">${chart(c,9)}</div></div>`;else if(name==='dasha'){const ds=dasha(c);$('tabContent').innerHTML=`<section><h3>महादशा समयरेखा</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>ग्रह</th><th>सुरु</th><th>समाप्त</th><th>स्थिति</th></tr></thead><tbody>${ds.rows.map(r=>`<tr><td><b>${r.lord}</b></td><td>${fmtDate(r.start)}</td><td>${fmtDate(r.end)}</td><td>${r.active?'🟢 सक्रिय':'—'}</td></tr>`).join('')}</tbody></table></div></section><section><h3>अन्तर्दशा</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>ग्रह</th><th>सुरु</th><th>समाप्त</th><th>स्थिति</th></tr></thead><tbody>${ds.antardasha.map(r=>`<tr><td>${r.lord}</td><td>${fmtDate(r.start)}</td><td>${fmtDate(r.end)}</td><td>${r.active?'🟢 सक्रिय':'—'}</td></tr>`).join('')}</tbody></table></div></section>`}else if(name==='points')$('tabContent').innerHTML=`<div class="point-grid"><div><b>लग्न</b><strong>${SIGNS[c.ascSign]} ${dms(c.asc)}</strong></div><div><b>अयनांश</b><strong>${c.ayan.toFixed(6)}°</strong></div><div><b>Julian Day</b><strong>${c.jd.toFixed(6)}</strong></div></div>`;else if(name==='panchanga')$('tabContent').innerHTML=`<div class="point-grid"><div><b>स्थानीय समय</b><strong>${c.local}</strong></div><div><b>UTC</b><strong>${c.utc}</strong></div><div><b>स्थान</b><strong>${c.input.place}</strong></div><div><b>निर्देशांक</b><strong>${c.input.lat.toFixed(6)}, ${c.input.lon.toFixed(6)}</strong></div></div>`;else $('tabContent').innerHTML='<div class="notice">यो परिणाम Swiss Ephemeris sidereal calculation बाट तयार गरिएको हो। गणना boundary मा भए विशेषज्ञसँग cross-check गर्नु उचित हुन्छ।</div>'}
async function generate(){const b=$('generate');b.disabled=true;$('error').hidden=true;try{await init();const x=input(),bd=await utcDate(x);render(calc(x,bd),bd)}catch(e){$('error').hidden=false;$('error').textContent=e?.message||String(e)}finally{b.disabled=false}}
function fmtTz(v){const n=Number(v);if(!Number.isFinite(n))return '';const s=n>=0?'+':'−',a=Math.abs(n),h=Math.floor(a),m=Math.round((a-h)*60);return `UTC${s}${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`}
async function timezone(la,lo){try{const r=await fetch(`https://timeapi.io/api/timezone/coordinate?latitude=${encodeURIComponent(la)}&longitude=${encodeURIComponent(lo)}`);if(r.ok){const j=await r.json(),off=j.currentUtcOffset?.seconds??j.currentUtcOffset?.totalSeconds;if(Number.isFinite(off))return off/3600}}catch{}return null}
function setLocation(name,la,lo,offset){$('lat').value=la;$('lon').value=lo;if(Number.isFinite(offset))$('tz').value=offset;$('locationBadge').textContent='📍 '+name;$('coordBadge').textContent=`${Number(la).toFixed(4)}, ${Number(lo).toFixed(4)} · ${fmtTz($('tz').value)}`;$('locationStatus').textContent='✓ जन्मस्थान पहिचान भयो';$('generate').disabled=false}
async function searchLocation(q){if(locationAbort)locationAbort.abort();locationAbort=new AbortController();$('locationStatus').textContent='स्थान खोज्दै…';$('generate').disabled=true;try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=6&accept-language=ne,en&q=${encodeURIComponent(q)}`,{signal:locationAbort.signal,headers:{Accept:'application/json'}});if(!r.ok)throw Error('location');const items=await r.json(),box=$('locationSuggestions');box.innerHTML='';if(!items.length){box.hidden=true;$('locationStatus').textContent='स्थान भेटिएन।';return}for(const item of items){const btn=document.createElement('button');btn.type='button';btn.className='location-option';btn.textContent=item.display_name;btn.onclick=async()=>{box.hidden=true;const la=Number(item.lat),lo=Number(item.lon);setLocation(item.display_name,la,lo,5.75);const off=await timezone(la,lo);if(off!==null){$('tz').value=off;$('coordBadge').textContent=`${la.toFixed(4)}, ${lo.toFixed(4)} · ${fmtTz(off)}`}};box.appendChild(btn)}box.hidden=false}catch(e){if(e.name!=='AbortError')$('locationStatus').textContent='स्थान खोज्न सकिएन।'}}
$('generate').addEventListener('click',generate);$('sample').addEventListener('click',()=>{ $('name').value='नमुना';$('calendar').value='ad';$('year').value='2002';$('month').value='3';$('day').value='18';$('time').value='12:00';$('place').value='Hetauda, Nepal';searchLocation('Hetauda, Nepal')});$('place').addEventListener('input',()=>{clearTimeout(locationTimer);const q=$('place').value.trim();$('generate').disabled=true;if(q.length<3){$('locationSuggestions').hidden=true;$('locationStatus').textContent='कम्तीमा ३ अक्षर लेख्नुहोस्।';return}locationTimer=setTimeout(()=>searchLocation(q),450)});document.addEventListener('click',e=>{if(!e.target.closest('.location-field'))$('locationSuggestions').hidden=true});$('tabs').addEventListener('click',e=>{const t=e.target.closest('.tab');if(!t)return;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===t));tab(t.dataset.tab)});$('print').onclick=()=>window.print();$('save').onclick=()=>{if(last)localStorage.setItem('nepali-patro-kundali-v3',JSON.stringify({input:last.core.input,utc:last.core.utc,savedAt:new Date().toISOString()}))};$('downloadChart').onclick=()=>{if(!last)return;const blob=new Blob([chart(last.core)],{type:'image/svg+xml'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kundali-d1.svg';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};$('theme').onclick=()=>document.body.classList.toggle('dark');setLocation('काठमाडौं, नेपाल',27.7172,85.3240,5.75);init().catch(()=>{});
