import {calculate,signs} from './kundali-engine.js';
const $=id=>document.getElementById(id);const state=$('engineState'),meta=$('engineMeta'),error=$('error'),results=$('results');
state.textContent='✓ गणना इन्जिन तयार';meta.textContent='Offline-safe fallback · approximate calculations';
function read(){const cal=$('calendar').value,y=+$('year').value,m=+$('month').value,d=+$('day').value,t=$('time').value||'12:00';if(cal!=='ad')throw Error('अहिले ई.सं. मिति मात्र समर्थित छ।');if(!y||m<1||m>12||d<1||d>31)throw Error('कृपया सही जन्म मिति राख्नुहोस्।');const [h,mi]=t.split(':').map(Number);if(h>23||mi>59)throw Error('कृपया सही जन्म समय राख्नुहोस्।');return{date:new Date(Date.UTC(y,m-1,d,h,mi)-5.75*3600000),lat:+$('lat').value,lon:+$('lon').value,ayanamsa:$('ayan').value}}
function fmt(x){return `${Math.floor(x)}° ${Math.floor((x%1)*60)}′`}
function dateFmt(d){return new Intl.DateTimeFormat('en-GB',{year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
function render(c){const p=c.planets;const asc=c.ascendant;$('personTitle').textContent=$('name').value||'जन्मकुण्डली';$('birthSummary').textContent=`${$('year').value}-${$('month').value}-${$('day').value} · ${$('time').value}`;$('method').innerHTML=`<span>${c.engine}</span><span>${c.precision}</span><span>${c.ayanamsa}</span>`;$('facts').innerHTML=`<div class="fact"><small>लग्न</small><b>${signs[asc.sign]} ${fmt(asc.degree)}</b></div><div class="fact"><small>चन्द्र</small><b>${signs[p.Moon.sign]} ${fmt(p.Moon.degree)}</b></div><div class="fact"><small>सूर्य</small><b>${signs[p.Sun.sign]} ${fmt(p.Sun.degree)}</b></div><div class="fact"><small>नक्षत्र</small><b>${p.Moon.nakshatra.name} · पाद ${p.Moon.nakshatra.pada}</b></div>`;
$('tabContent').innerHTML=`<section><h3>ग्रह स्थिति</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>ग्रह</th><th>राशि</th><th>अंश</th><th>नक्षत्र</th></tr></thead><tbody>${Object.entries(p).map(([n,v])=>`<tr><td>${n}</td><td>${signs[v.sign]}</td><td>${fmt(v.degree)}</td><td>${v.nakshatra.name} · पाद ${v.nakshatra.pada}</td></tr>`).join('')}</tbody></table></div></section><section><h3>लग्न र भाव</h3><div class="houses-grid">${c.houses.map(h=>`<article><b>भाव ${h.house}</b><strong>${signs[h.sign]}</strong><p>${h.house===1?`लग्न ${fmt(h.degree)}`:'Whole-sign house'}</p></article>`).join('')}</div></section><section><h3>विम्शोत्तरी दशा</h3><div class="notice">जन्म नक्षत्र: <b>${p.Moon.nakshatra.name}</b> · प्रारम्भिक दशा: <b>${c.dasha.birthLord}</b> · बाँकी अवधि: <b>${c.dasha.balanceYears.toFixed(2)} वर्ष</b></div><div class="table-wrap"><table class="data-table"><thead><tr><th>महादशा</th><th>अवधि</th><th>सुरु</th><th>समाप्त</th></tr></thead><tbody>${c.dasha.periods.map(x=>`<tr><td><b>${x.lord}</b></td><td>${x.years.toFixed(2)} वर्ष</td><td>${dateFmt(x.start)}</td><td>${dateFmt(x.end)}</td></tr>`).join('')}</tbody></table></div></section>`;results.hidden=false}
$('generate').addEventListener('click',()=>{error.hidden=true;try{render(calculate(read()))}catch(e){error.textContent=e.message||'गणना गर्न सकिएन।';error.hidden=false}});$('theme')?.addEventListener('click',()=>document.body.classList.toggle('dark'));$('print')?.addEventListener('click',()=>print());
