const CACHE_NAME='nepali-patro-v2026-09-11-05';
const OFFLINE_URL='./offline.html';
const APP_SHELL=['./','./index.html','./manifest.json','./assets/logo.svg','./offline.html','./css/main.css','./css/homepage-redesign.css','./css/mobile-nav.css','./css/extra-tools.css','./css/homepage-performance-ui.css','./css/homepage-ui-v2.css','./css/homepage-dashboard-v3.css','./css/homepage-ui-v4.css','./css/homepage-pwa-v5.css','./js/homepage-controller.js','./js/homepage-runtime.js','./js/homepage-calendar-preview.js','./js/homepage-calendar-v7.js','./js/homepage-calendar-v8.js','./js/homepage-finance.js','./js/rashifal-home.js','./js/homepage-history.js','./js/homepage-converter.js','./js/homepage-ui-v2.js','./js/homepage-dashboard-v3.js','./js/homepage-ui-v4.js','./js/homepage-pwa-v5.js'];
const sameOrigin=u=>u.origin===self.location.origin;
const isCacheable=res=>res&&res.ok&&(res.type==='basic'||res.type==='default');
const cacheRequest=req=>{const u=new URL(req.url);u.searchParams.delete('v');u.searchParams.delete('parba');return new Request(u.toString(),{method:'GET',headers:req.headers,mode:'same-origin',credentials:req.credentials,redirect:'follow'});};
async function put(req,res){if(!isCacheable(res))return res;try{const c=await caches.open(CACHE_NAME);await c.put(req,res.clone());}catch{}return res;}
async function networkFirst(req){const key=cacheRequest(req);try{return await put(key,await fetch(req,{cache:'no-store'}));}catch{const cached=await caches.match(key);return cached||new Response('',{status:503,statusText:'Offline'});}}
async function staleWhileRevalidate(req){const key=cacheRequest(req);const cached=await caches.match(key);const network=fetch(req,{cache:'no-store'}).then(r=>put(key,r)).catch(()=>null);return cached||await network||new Response('',{status:503,statusText:'Offline'});}
async function networkFirstNavigation(req){const key=cacheRequest(req);try{return await put(key,await fetch(req,{cache:'no-store'}));}catch{const cached=await caches.match(key);if(cached)return cached;const offline=await caches.match(OFFLINE_URL);return offline||new Response('<!doctype html><title>अफलाइन</title><h1>नेपाली पात्रो</h1><p>इन्टरनेट उपलब्ध छैन।</p>',{status:503,headers:{'Content-Type':'text/html;charset=utf-8'}});}}
async function calendarNetworkFirst(req){const key=cacheRequest(req);try{return await put(key,await fetch(req,{cache:'no-store'}));}catch{const cached=await caches.match(key);return cached||new Response('',{status:503,statusText:'Offline'});}}
self.addEventListener('install',e=>e.waitUntil((async()=>{const c=await caches.open(CACHE_NAME);await Promise.all(APP_SHELL.map(async path=>{try{await c.add(path);}catch{}}));await self.skipWaiting();})()));
self.addEventListener('activate',e=>e.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k)));await self.clients.claim();})()));
self.addEventListener('message',e=>{if(e.data?.type==='SKIP_WAITING')self.skipWaiting();});
self.addEventListener('fetch',e=>{const r=e.request;if(r.method!=='GET')return;const u=new URL(r.url);if(!sameOrigin(u))return;if(r.mode==='navigate'||r.destination==='document'){e.respondWith(networkFirstNavigation(r));return}const path=u.pathname;const calendarData=/\/data\/calendar\/\d+\.json$/.test(path);const yearIndex=/\/data\/years\.json$/.test(path);const feed=path.includes('/feeds/')||path.endsWith('.json');const asset=['script','style','font','image','manifest'].includes(r.destination);if(calendarData){e.respondWith(calendarNetworkFirst(r));return}if(yearIndex||feed){e.respondWith(networkFirst(r));return}if(asset){e.respondWith(staleWhileRevalidate(r));}});
