const CACHE_NAME='nepali-patro-v2026-09-16-offline-01';
const OFFLINE_URL='/Nepali-Patro/offline.html';
const MANIFEST_URL='/Nepali-Patro/offline-manifest.json';
const FALLBACK_SHELL=['/Nepali-Patro/','/Nepali-Patro/index.html','/Nepali-Patro/offline.html','/Nepali-Patro/manifest.json','/Nepali-Patro/css/shared-shell.css','/Nepali-Patro/js/shared-shell.js'];
const sameOrigin=u=>u.origin===self.location.origin;
const isCacheable=res=>res&&res.ok&&(res.type==='basic'||res.type==='default');
const cacheRequest=req=>{const u=new URL(req.url);u.searchParams.delete('v');return new Request(u.toString(),{method:'GET',headers:req.headers,mode:'same-origin',credentials:req.credentials,redirect:'follow'});};
async function put(req,res){if(!isCacheable(res))return res;try{const c=await caches.open(CACHE_NAME);await c.put(cacheRequest(req),res.clone());}catch{}return res;}
async function networkFirst(req){const key=cacheRequest(req);try{return await put(key,await fetch(req,{cache:'no-store'}));}catch{const cached=await caches.match(key);return cached||new Response('',{status:503,statusText:'Offline'});}}
async function staleWhileRevalidate(req){const key=cacheRequest(req);const cached=await caches.match(key);const network=fetch(req,{cache:'no-store'}).then(r=>put(key,r)).catch(()=>null);return cached||await network||new Response('',{status:503,statusText:'Offline'});}
async function navigation(req){const key=cacheRequest(req);try{return await put(key,await fetch(req,{cache:'no-store'}));}catch{const cached=await caches.match(key);if(cached)return cached;return await caches.match(OFFLINE_URL)||await caches.match('/Nepali-Patro/');}}
self.addEventListener('install',e=>e.waitUntil((async()=>{const c=await caches.open(CACHE_NAME);try{const r=await fetch(MANIFEST_URL,{cache:'no-store'});const m=await r.json();const urls=[...(m.routes||[]),...(m.assets||[]),MANIFEST_URL];await Promise.all(urls.map(async u=>{try{const r=await fetch(u,{cache:'no-store'});if(isCacheable(r))await c.put(u,r.clone());}catch{}}));}catch{await Promise.all(FALLBACK_SHELL.map(async u=>{try{const r=await fetch(u);if(isCacheable(r))await c.put(u,r.clone());}catch{}}));}await self.skipWaiting();})()));
self.addEventListener('activate',e=>e.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k)));await self.clients.claim();})()));
self.addEventListener('message',e=>{if(e.data?.type==='SKIP_WAITING')self.skipWaiting();});
self.addEventListener('fetch',e=>{const r=e.request;if(r.method!=='GET')return;const u=new URL(r.url);if(!sameOrigin(u))return;if(r.mode==='navigate'||r.destination==='document'){e.respondWith(navigation(r));return}const path=u.pathname;const calendarData=/\/data\/calendar\/\d+\.json$/.test(path);const yearIndex=/\/data\/years\.json$/.test(path);const feed=path.includes('/feeds/')||path.endsWith('.json');const asset=['script','style','font','image','manifest'].includes(r.destination);if(calendarData||yearIndex||feed){e.respondWith(networkFirst(r));return}if(asset){e.respondWith(staleWhileRevalidate(r));}});
