(() => {
  const baseSites=Array.isArray(window.GOVERNMENT_SITES)?window.GOVERNMENT_SITES:[];
  const provinceSites=Array.isArray(window.GOVERNMENT_PROVINCES)?window.GOVERNMENT_PROVINCES:[];
  const generatedLocals=Array.isArray(window.GOVERNMENT_LOCAL_GOVERNMENTS)?window.GOVERNMENT_LOCAL_GOVERNMENTS:[];
  const curatedLocals=Array.isArray(window.GOVERNMENT_LOCALS)?window.GOVERNMENT_LOCALS:[];
  const localSites=[...generatedLocals,...curatedLocals];
  const sites=[...new Map([...baseSites,...provinceSites,...localSites].filter(s=>s?.u).map(s=>[s.u,s])).values()];
  const services=Array.isArray(window.GOVERNMENT_SERVICES)?window.GOVERNMENT_SERVICES:[],locations=window.GOVERNMENT_LOCATIONS||{};
  const $=id=>document.getElementById(id),grid=$('govGrid'),search=$('search'),clear=$('clearSearch'),category=$('categoryFilter'),level=$('levelFilter'),favBtn=$('favoritesOnly'),stats=$('stats'),strip=$('categoryStrip'),tags=$('quickTags'),empty=$('empty');
  const key='nepaliPatroGovFavorites',recentKey='nepaliPatroGovRecent';let favorites=new Set(JSON.parse(localStorage.getItem(key)||'[]')),recent=JSON.parse(localStorage.getItem(recentKey)||'[]');
  let activeCategory='all',activeProvince='all',activeDistrict='all',favoritesOnly=false,sortMode='name';
  const labels={'सरकार':'🏛️ सरकार','प्रदेश सरकार':'🏛️ प्रदेश सरकार','स्थानीय सरकार':'🏘️ स्थानीय सरकार','स्थानीय शासन':'🏘️ स्थानीय शासन','गृह तथा सुरक्षा':'🛡️ गृह तथा सुरक्षा','परराष्ट्र':'🌐 परराष्ट्र','अर्थ तथा राजस्व':'💰 अर्थ तथा राजस्व','पूर्वाधार':'🛣️ पूर्वाधार','शिक्षा':'🎓 शिक्षा','स्वास्थ्य':'🏥 स्वास्थ्य','डिजिटल तथा IT':'💻 डिजिटल तथा IT','कृषि':'🌾 कृषि','उद्योग तथा व्यापार':'🏭 उद्योग तथा व्यापार','श्रम तथा रोजगार':'👷 श्रम तथा रोजगार','भूमि तथा सहकारी':'🏠 भूमि तथा सहकारी','पर्यटन तथा उड्डयन':'✈️ पर्यटन तथा उड्डयन','ऊर्जा तथा जलस्रोत':'⚡ ऊर्जा तथा जलस्रोत','वन तथा वातावरण':'🌿 वन तथा वातावरण','कानुन तथा न्याय':'⚖️ कानुन तथा न्याय','सामाजिक सेवा':'🤝 सामाजिक सेवा','युवा तथा खेलकुद':'🏃 युवा तथा खेलकुद','बैंकिङ तथा वित्त':'🏦 बैंकिङ तथा वित्त','संवैधानिक निकाय':'🏛️ संवैधानिक निकाय','सुरक्षा':'🚨 सुरक्षा','नागरिक सेवा':'🪪 नागरिक सेवा','व्यवसाय सेवा':'💼 व्यवसाय सेवा','रोजगार तथा परीक्षा':'📝 रोजगार तथा परीक्षा','डिजिटल सेवा':'📱 डिजिटल सेवा','ऊर्जा तथा उपयोगिता':'💡 ऊर्जा तथा उपयोगिता','पर्यटन':'🏔️ पर्यटन','विज्ञान तथा मौसम':'🌦️ विज्ञान तथा मौसम','विपद् व्यवस्थापन':'🚑 विपद् व्यवस्थापन','तथ्याङ्क':'📊 तथ्याङ्क'};
  const levels={federal:'संघीय',constitutional:'संवैधानिक',security:'सुरक्षा',provincial:'प्रदेश',local:'स्थानीय',service:'सेवा'};
  const icons={'प्रदेश सरकार':'🏛️','स्थानीय सरकार':'🏘️','स्थानीय शासन':'🏘️','गृह तथा सुरक्षा':'🛡️','परराष्ट्र':'🌐','अर्थ तथा राजस्व':'💰','शिक्षा':'🎓','स्वास्थ्य':'🏥','कृषि':'🌾','उद्योग तथा व्यापार':'🏭','श्रम तथा रोजगार':'👷','बैंकिङ तथा वित्त':'🏦','नागरिक सेवा':'🪪','व्यवसाय सेवा':'💼','रोजगार तथा परीक्षा':'📝','डिजिटल सेवा':'📱','विपद् व्यवस्थापन':'🚑','तथ्याङ्क':'📊','ऊर्जा तथा उपयोगिता':'⚡','पर्यटन':'🏔️'};
  const normalize=s=>String(s||'').toLocaleLowerCase('ne-NP').replace(/[\s\-_/.,]+/g,''),hay=s=>normalize([s.n,s.e,s.c,s.d,s.k,s.u,s.p,s.district,s.type,s.email,s.phone].join(' ')),save=()=>localStorage.setItem(key,JSON.stringify([...favorites]));
  const addRecent=u=>{recent=[u,...recent.filter(x=>x!==u)].slice(0,8);localStorage.setItem(recentKey,JSON.stringify(recent))};
  function filtered(){const q=normalize(search.value);return sites.filter(s=>{const textOk=!q||hay(s).includes(q),catOk=activeCategory==='all'||s.c===activeCategory,levelOk=level.value==='all'||s.l===level.value,provinceOk=activeProvince==='all'||s.p===activeProvince,districtOk=activeDistrict==='all'||s.district===activeDistrict,savedOk=!favoritesOnly||favorites.has(s.u);return textOk&&catOk&&levelOk&&provinceOk&&districtOk&&savedOk}).sort((a,b)=>sortMode==='recent'?(recent.indexOf(a.u)+99)-(recent.indexOf(b.u)+99):String(a.n).localeCompare(String(b.n),'ne-NP'))}
  function render(){const list=filtered();stats.textContent=`${list.length} वटा वेबसाइट · कुल ${sites.length} वटा सूचीबद्ध`;grid.innerHTML='';empty.hidden=list.length>0;list.forEach(s=>{const saved=favorites.has(s.u),card=document.createElement('article');card.className='gov-card';const loc=s.p?((locations.provinces||[]).find(p=>p.id===s.p)?.name||s.p):'';card.innerHTML=`<div class="gov-card-top"><span class="gov-icon">${icons[s.c]||'🇳🇵'}</span><button class="star ${saved?'saved':''}" aria-label="${saved?'मनपर्नेबाट हटाउनुहोस्':'मनपर्नेमा राख्नुहोस्'}">${saved?'★':'☆'}</button></div><h2>${esc(s.n)}</h2><div class="en">${esc(s.e||'')}</div><p>${esc(s.d||s.desc||(s.type?`${s.type} — ${s.district||''}`:'आधिकारिक सरकारी वेबसाइट।'))}</p><div class="gov-meta"><span class="pill official">✓ आधिकारिक लिंक</span><span class="pill">${esc(levels[s.l]||s.l||'')}</span><span class="pill">${esc(s.c||'')}</span>${loc?`<span class="pill">${esc(loc)}</span>`:''}${s.district?`<span class="pill">${esc(s.district)}</span>`:''}${s.type?`<span class="pill">${esc(s.type)}</span>`:''}</div>${s.email||s.phone?`<div class="gov-contact">${esc(s.email||'')}${s.email&&s.phone?' · ':''}${esc(s.phone||'')}</div>`:''}<div class="card-actions"><a class="gov-open" href="${escAttr(s.u)}" target="_blank" rel="noopener noreferrer">वेबसाइट खोल्नुहोस् <span>↗</span></a><button class="copy-btn" type="button">कपी</button></div>`;card.querySelector('.star').onclick=()=>{favorites.has(s.u)?favorites.delete(s.u):favorites.add(s.u);save();render()};card.querySelector('.gov-open').onclick=()=>addRecent(s.u);card.querySelector('.copy-btn').onclick=async()=>{try{await navigator.clipboard.writeText(s.u);card.querySelector('.copy-btn').textContent='कपी भयो ✓';setTimeout(()=>card.querySelector('.copy-btn').textContent='कपी',1200)}catch{}};grid.appendChild(card)})}
  function esc(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}const escAttr=esc;
  const cats=[...new Set(sites.map(s=>s.c).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ne-NP'));cats.forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=labels[c]||c;category.appendChild(o)});
  ['पासपोर्ट','नागरिकता','PAN','कर','लोक सेवा','जग्गा','वैदेशिक रोजगार','बिजुली','परीक्षाफल','नगरपालिका','गाउँपालिका'].forEach(q=>{const b=document.createElement('button');b.textContent=q;b.onclick=()=>{search.value=q;render()};tags.appendChild(b)});
  const tools=document.querySelector('.filters'),sort=document.createElement('select');sort.setAttribute('aria-label','क्रम');sort.innerHTML='<option value="name">नामअनुसार</option><option value="recent">हालै हेरेका</option>';sort.onchange=()=>{sortMode=sort.value;render()};tools.appendChild(sort);
  const geo=document.createElement('div');geo.className='geo-filters';geo.innerHTML='<select id="provinceFilter" aria-label="प्रदेश छान्नुहोस्"><option value="all">सबै प्रदेश</option></select><select id="districtFilter" aria-label="जिल्ला छान्नुहोस्"><option value="all">सबै जिल्ला</option></select>';tools.appendChild(geo);const province=$('provinceFilter'),district=$('districtFilter');
  (locations.provinces||[]).forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name;province.appendChild(o)});
  function fillDistricts(){district.innerHTML='<option value="all">सबै जिल्ला</option>';const p=(locations.provinces||[]).find(x=>x.id===activeProvince);(p?.districts||[]).forEach(d=>{const o=document.createElement('option');o.value=d;o.textContent=d;district.appendChild(o)});district.value=activeDistrict}
  province.onchange=()=>{activeProvince=province.value;activeDistrict='all';fillDistricts();render()};district.onchange=()=>{activeDistrict=district.value;render()};fillDistricts();
  const serviceWrap=document.createElement('section');serviceWrap.className='service-intents';serviceWrap.innerHTML='<div class="section-heading"><div><span>छिटो सेवा खोज्नुहोस्</span><small>तपाईंलाई चाहिएको कामबाट सरकारी वेबसाइट भेटाउनुहोस्</small></div></div><div class="service-grid"></div>';document.querySelector('.directory-tools').after(serviceWrap);const serviceGrid=serviceWrap.querySelector('.service-grid');services.forEach(s=>{const b=document.createElement('button');b.className='service-card';b.innerHTML=`<span>${s.icon}</span><strong>${esc(s.title)}</strong><small>${esc(s.description)}</small>`;b.onclick=()=>{search.value=s.queries[0];render()};serviceGrid.appendChild(b)});
  const all=document.createElement('button');all.className='active';all.dataset.cat='all';all.textContent='सबै';strip.appendChild(all);cats.forEach(c=>{const b=document.createElement('button');b.dataset.cat=c;b.textContent=labels[c]||c;b.onclick=()=>{activeCategory=c;category.value=c;syncStrip();render()};strip.appendChild(b)});const syncStrip=()=>[...strip.children].forEach(x=>x.classList.toggle('active',x.dataset.cat===activeCategory));all.onclick=()=>{activeCategory='all';category.value='all';syncStrip();render()};category.onchange=()=>{activeCategory=category.value;syncStrip();render()};level.onchange=render;search.oninput=render;clear.onclick=()=>{search.value='';render();search.focus()};favBtn.onclick=()=>{favoritesOnly=!favoritesOnly;favBtn.classList.toggle('active',favoritesOnly);favBtn.textContent=favoritesOnly?'★ सबै हेर्नुहोस्':'☆ मनपर्ने मात्र';render()};
  const params=new URLSearchParams(location.search);if(params.get('q'))search.value=params.get('q');if(params.get('category')&&cats.includes(params.get('category'))){activeCategory=params.get('category');category.value=activeCategory}if(params.get('level'))level.value=params.get('level');if(params.get('province')&&(locations.provinces||[]).some(p=>p.id===params.get('province'))){activeProvince=params.get('province');province.value=activeProvince;fillDistricts()}if(params.get('district')){activeDistrict=params.get('district');district.value=activeDistrict};syncStrip();if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();
})();
