(()=>{'use strict';
const Q=s=>document.querySelector(s),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ROOT='../../data/nepse/';
const PARAM=new URLSearchParams(location.search);const SYMBOL=(PARAM.get('symbol')||location.pathname.split('/').filter(Boolean).at(-1)||'').toUpperCase();
const arr=x=>Array.isArray(x)?x:(x?.data||x?.results||x?.companies||x?.items||[]),sym=x=>String(x?.symbol??x?.ticker??x?.securityCode??'').toUpperCase(),find=(a,s)=>arr(a).find(x=>sym(x)===s)||null;
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const field=(o,re)=>{for(const [k,v] of Object.entries(o||{}))if(re.test(k)&&v!==null&&v!==''&&typeof v!=='object'&&num(v)!==null)return num(v);return null};
const money=v=>num(v)===null?'—':num(v).toLocaleString('en-IN',{maximumFractionDigits:2}),pct=v=>num(v)===null?'—':(num(v)>=0?'+':'')+num(v).toFixed(2)+'%';
async function get(path){const r=await fetch(ROOT+path+'?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(r.status);return r.json()}
function closes(rows){return rows.map(x=>num(x.ltp)).filter(v=>v!==null)}
function sma(a,n){if(a.length<n)return null;return a.slice(-n).reduce((x,y)=>x+y,0)/n}
function rsi(a,n=14){if(a.length<=n)return null;let g=0,l=0;for(let i=a.length-n;i<a.length;i++){const d=a[i]-a[i-1];if(d>0)g+=d;else l-=d}if(l===0)return 100;return 100-(100/(1+g/l))}
function stats(rows){const c=closes(rows),last=c.at(-1),prev=c.at(-2),high=Math.max(...c),low=Math.min(...c),s20=sma(c,20),s50=sma(c,50),rr=rsi(c),mom=c.length>20&&c.at(-21)?(last/c.at(-21)-1)*100:null;let peak=-Infinity,maxDD=0;for(const v of c){peak=Math.max(peak,v);if(peak>0)maxDD=Math.min(maxDD,(v/peak-1)*100)}return {last,prev,high,low,s20,s50,rsi:rr,mom20:mom,maxDD}}
function score(st,f,stock){let score=50,parts=[];const add=(name,points,reason)=>parts.push({name,points,reason});
if(st.s20!==null&&st.s50!==null&&st.last!==null){if(st.last>st.s20&&st.s20>st.s50)add('Trend',12,'Price is above the 20-day and 50-day averages, with the shorter average above the longer one.');else if(st.last>st.s20)add('Trend',6,'Price is above the 20-day average.');else if(st.last<st.s20&&st.s20<st.s50)add('Trend',-12,'Price is below both moving averages and the shorter average is below the longer one.');else add('Trend',-4,'Trend signals are mixed.')}
if(st.rsi!==null){if(st.rsi>=55&&st.rsi<=70)add('Momentum',8,'RSI shows positive momentum without entering an extreme zone.');else if(st.rsi>75)add('Momentum',-6,'RSI is elevated; reversal risk is higher.');else if(st.rsi<30)add('Momentum',-4,'RSI is weak/oversold; trend confirmation is missing.');else add('Momentum',2,'RSI is broadly neutral.')}
const eps=field(f,/^eps$|earnings.?per.?share/i),bvps=field(f,/book.?value.?per.?share|^bvps$/i),profit=field(f,/net.?profit|profit.?after.?tax|profit.?loss/i),equity=field(f,/total.?equity|shareholders.?equity/i),assets=field(f,/total.?assets/i),revenue=field(f,/revenue|total.?income|sales/i),debt=field(f,/total.?debt|borrow|loan/i);const pe=field(f,/^pe$|p.?e.?ratio|price.?earnings/i)??(num(stock.ltp)&&eps?num(stock.ltp)/eps:null),pb=field(f,/^pb$|p.?b.?ratio|price.?book/i)??(num(stock.ltp)&&bvps?num(stock.ltp)/bvps:null),roe=field(f,/return.?on.?equity|^roe$/i)??(profit!==null&&equity?profit/equity*100:null),roa=field(f,/return.?on.?assets|^roa$/i)??(profit!==null&&assets?profit/assets*100:null);
if(eps!==null)add('EPS',eps>0?7:-8,eps>0?'Latest reported EPS is positive.':'Latest reported EPS is negative.');
if(roe!==null)add('ROE',roe>=15?8:roe>=8?3:-5,`ROE is ${roe.toFixed(2)}%.`);
if(roa!==null)add('ROA',roa>=8?5:roa>=3?2:-3,`ROA is ${roa.toFixed(2)}%.`);
if(pe!==null)add('Valuation',pe>0&&pe<15?7:pe<25?3:pe<0?-5:-4,pe>0?`P/E is ${pe.toFixed(2)}x.`:'P/E is not meaningful from the available earnings data.');
if(pb!==null)add('Book valuation',pb>0&&pb<2?5:pb<4?2:-3,`P/B is ${pb.toFixed(2)}x.`);
if(profit!==null)add('Profitability',profit>0?5:-7,profit>0?'Reported net profit is positive.':'Reported net profit is negative.');
if(revenue!==null&&profit!==null&&revenue>0)add('Profit margin',profit/revenue>=.1?5:profit/revenue>=0?2:-4,`Derived net margin is ${(profit/revenue*100).toFixed(2)}%.`);
if(debt!==null&&equity!==null&&equity!==0){const de=debt/equity;add('Leverage',de<.5?5:de<1?2:-5,`Debt/equity is ${de.toFixed(2)}x.`)}
if(st.mom20!==null)add('20D momentum',st.mom20>8?5:st.mom20>0?2:st.mom20<-10?-6:-2,`20-session price momentum is ${st.mom20.toFixed(2)}%.`);
if(st.maxDD!==0)add('Drawdown',st.maxDD>-15?3:st.maxDD>-30?0:-5,`Observed peak-to-trough drawdown is ${st.maxDD.toFixed(2)}%.`);
score=Math.max(0,Math.min(100,Math.round(score)));const label=score>=75?'Strong research setup':score>=60?'Positive research setup':score>=45?'Neutral / mixed':score>=30?'Caution':'Weak research setup';return {score,label,parts}}
function render(ad,st,rows){const positive=ad.parts.filter(x=>x.points>0).sort((a,b)=>b.points-a.points).slice(0,4),negative=ad.parts.filter(x=>x.points<0).sort((a,b)=>a.points-b.points).slice(0,4),latest=rows.at(-1),old=rows.length>20?rows.at(-21):rows[0],p20=old&&latest?((latest.ltp-old.ltp)/old.ltp*100):null;return `<section class="deep financial-advisor" id="financialAdvisor"><div class="advisor-top"><div><span class="eyebrow">RULE-BASED FINANCIAL ADVISOR</span><h2>Financial Advisor</h2><p>Automatic market + financial data analysis.</p></div><div class="advisor-score"><strong>${ad.score}</strong><span>/100</span><small>${E(ad.label)}</small></div></div><div class="advisor-grid"><div class="advisor-card"><h3>What the data says</h3><div class="advisor-metrics"><div><span>RSI (14)</span><b>${st.rsi===null?'—':st.rsi.toFixed(1)}</b></div><div><span>20D momentum</span><b>${pct(p20)}</b></div><div><span>20D average</span><b>${money(st.s20)}</b></div><div><span>50D average</span><b>${money(st.s50)}</b></div><div><span>Loaded high</span><b>${money(st.high)}</b></div><div><span>Loaded low</span><b>${money(st.low)}</b></div></div></div><div class="advisor-card"><h3>Positive signals</h3>${positive.length?positive.map(x=>`<div class="advisor-signal good"><b>+${x.points} · ${E(x.name)}</b><span>${E(x.reason)}</span></div>`).join(''):'<p class="empty-note">No strong positive signal available.</p>'}</div><div class="advisor-card"><h3>Risk signals</h3>${negative.length?negative.map(x=>`<div class="advisor-signal risk"><b>${x.points} · ${E(x.name)}</b><span>${E(x.reason)}</span></div>`).join(''):'<p class="empty-note">No major negative rule triggered.</p>'}</div></div><div class="advisor-action"><strong>Research stance: ${E(ad.label)}</strong><span>Transparent scoring only — not a guaranteed forecast or personalized buy/sell instruction. Verify current reports and your risk tolerance before acting.</span></div><details class="advisor-details"><summary>How this score is calculated</summary><p>Starting score: 50. The model combines price trend, RSI, 20-session momentum, EPS, ROE, ROA, P/E, P/B, profitability, leverage and historical drawdown. Missing source fields are not invented.</p></details><small class="advisor-source">Local synchronized NEPSE dataset · ${new Date().toLocaleString('ne-NP')}</small></section>`}
async function run(){try{const [market,financials]=await Promise.all([get('nepse_data.json'),get('company/financials.json')]);const stock=find(market,SYMBOL)||{},f=find(financials,SYMBOL)||{};let rows=[];try{const man=await get('ltp/manifest.json');for(const m of (man.availableMonths||[]).slice(-13)){try{const d=await get('ltp/monthly/'+m+'.json'),dates=d?.dates||[],cols=d?.columns||[],ser=d?.series?.[SYMBOL]||[],ix=k=>cols.indexOf(k);for(const r of ser){const date=dates[r[ix('dateIndex')]],ltp=num(r[ix('ltp')]);if(date&&ltp!==null)rows.push({date,ltp})}}catch{}}}catch{}rows=[...new Map(rows.map(x=>[x.date,x])).values()].sort((a,b)=>a.date.localeCompare(b.date));const st=stats(rows),ad=score(st,f,stock),company=Q('#company');if(company){const n=document.createElement('div');n.innerHTML=render(ad,st,rows);company.appendChild(n.firstElementChild)}}catch(e){console.warn('Financial advisor unavailable',e)}}let tries=0;const wait=()=>{if(Q('#company')?.querySelector('.analysis-head'))run();else if(tries++<30)setTimeout(wait,250)};wait();
})();
